"""
part4_ch4_4b.py
Curated problems 4.214 to 4.238 (25 problems) of Irodov Chapter 4.4:
Electromagnetic Waves. Radiation (Part B).
"""

CH4_4B_CURATED = [
    {
        "id": "4.214",
        "title": "Bremsstrahlung Energy Radiated by a Charge in Flyby Past Another Charge",
        "difficulty": 3,
        "question": "A particle with charge $e$ and mass $m$ flies with non-relativistic velocity $v$ at an impact parameter $b$ past a stationary particle of charge $q$. Neglecting the bending of the trajectory of the moving particle, find the total energy $\\Delta W$ lost by this particle due to radiation during the entire flight time.",
        "hints": [
            "With the straight-line trajectory $x(t) = vt$, $y(t) = b$, the distance between charges is $r(t) = \\sqrt{b^2 + (vt)^2}$.",
            "The Coulomb force produces acceleration $w(t) = \\frac{1}{4\\pi\\varepsilon_0} \\frac{q e}{m [b^2 + (vt)^2]}$.",
            "Use Larmor's formula $P(t) = \\frac{e^2 w^2(t)}{6\\pi\\varepsilon_0 c^3}$ and integrate $\\Delta W = \\int_{-\\infty}^{\\infty} P(t)\\,dt$ using the standard integral $\\int_{-\\infty}^{\\infty} \\frac{dt}{(b^2 + v^2 t^2)^2} = \\frac{\\pi}{2 v b^3}$."
        ],
        "answer": "$\\Delta W \\approx \\frac{1}{(4\\pi\\varepsilon_0)^3} \\frac{\\pi e^4 q^2}{3 m^2 c^3 v b^3}$",
        "solution": "**1. Coulomb Force and Acceleration:**\nLet the stationary charge $q$ be at the origin $(0, 0)$. Assuming rectilinear motion along $y = b$ with constant speed $v$:\n$$x(t) = vt, \\quad y(t) = b$$\nThe distance between the charges at time $t$ is:\n$$r(t) = \\sqrt{b^2 + (vt)^2}$$\nThe magnitude of the Coulomb force acting on the particle of charge $e$ and mass $m$ is:\n$$F(t) = \\frac{1}{4\\pi\\varepsilon_0} \\frac{|q e|}{r^2(t)} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{|q e|}{b^2 + (vt)^2}$$\nTherefore, the acceleration of the moving particle has magnitude:\n$$w(t) = \\frac{F(t)}{m} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{|q e|}{m [b^2 + (vt)^2]}$$\n\n**2. Radiated Power (Larmor's Formula):**\nFor a non-relativistic accelerating charge, the instantaneous radiated power is:\n$$P(t) = \\frac{e^2 w^2(t)}{6\\pi\\varepsilon_0 c^3} = \\frac{2}{3} \\frac{1}{4\\pi\\varepsilon_0} \\frac{e^2}{c^3} w^2(t)$$\nSubstituting $w(t)$:\n$$P(t) = \\frac{2}{3(4\\pi\\varepsilon_0)^3} \\frac{e^4 q^2}{m^2 c^3} \\frac{1}{[b^2 + (vt)^2]^2}$$\n\n**3. Integration Over the Total Flight Time:**\nThe total radiated energy during the flyby is:\n$$\\Delta W = \\int_{-\\infty}^{\\infty} P(t) \\, dt = \\frac{2}{3(4\\pi\\varepsilon_0)^3} \\frac{e^4 q^2}{m^2 c^3} \\int_{-\\infty}^{\\infty} \\frac{dt}{[b^2 + (vt)^2]^2}$$\nSubstitute $vt = b \\tan\\theta$, so $dt = \\frac{b}{v} \\sec^2\\theta \\, d\\theta$ and $b^2 + (vt)^2 = b^2 \\sec^2\\theta$:\n$$\\int_{-\\infty}^{\\infty} \\frac{dt}{[b^2 + (vt)^2]^2} = \\int_{-\\pi/2}^{\\pi/2} \\frac{\\frac{b}{v}\\sec^2\\theta \\, d\\theta}{b^4 \\sec^4\\theta} = \\frac{1}{v b^3} \\int_{-\\pi/2}^{\\pi/2} \\cos^2\\theta \\, d\\theta = \\frac{\\pi}{2 v b^3}$$\n\n**4. Final Result:**\n$$\\Delta W = \\frac{2}{3(4\\pi\\varepsilon_0)^3} \\frac{e^4 q^2}{m^2 c^3} \\left(\\frac{\\pi}{2 v b^3}\\right) = \\frac{1}{(4\\pi\\varepsilon_0)^3} \\frac{\\pi e^4 q^2}{3 m^2 c^3 v b^3}$$",
        "tags": ["electrodynamics", "radiation", "bremsstrahlung", "Larmor formula", "Coulomb scattering"]
    },
    {
        "id": "4.215",
        "title": "Fraction of Kinetic Energy Radiated by a Proton in a Transverse Magnetic Field",
        "difficulty": 2,
        "question": "A non-relativistic proton enters a half-space along the normal to the transverse uniform magnetic field whose induction equals $B = 1.0\\text{ T}$. Find the ratio of the energy lost by the proton due to radiation during its motion in the field to its initial kinetic energy.",
        "hints": [
            "The proton enters normal to the boundary, describes a semicircle of radius $R = mv / (eB)$, and exits after half a cyclotron period: $\\Delta t = \\pi m / (eB)$.",
            "The centripetal acceleration is $w = v^2/R = e v B / m$.",
            "Calculate radiated power $P = \\frac{e^2 w^2}{6\\pi\\varepsilon_0 c^3}$ and total radiated energy $\\Delta W = P \\Delta t$, then divide by $T = \\frac{1}{2}mv^2$."
        ],
        "answer": "$\\frac{\\Delta W}{T} = \\frac{e^3 B}{3\\varepsilon_0 m^2 c^3} = \\frac{4\\pi}{3(4\\pi\\varepsilon_0)} \\frac{e^3 B}{m^2 c^3} \\approx 2 \\times 10^{-18}$",
        "solution": "**1. Motion in the Transverse Magnetic Field:**\nA proton of mass $m$ and charge $e$ entering perpendicular to a uniform magnetic field $B$ undergoes uniform circular motion with radius:\n$$R = \\frac{m v}{e B}$$\nSince it enters along the normal to the half-space boundary, its trajectory in the field is a half-circle, and the time spent in the magnetic field is:\n$$\\Delta t = \\frac{\\pi R}{v} = \\frac{\\pi m}{e B}$$\n\n**2. Centripetal Acceleration and Radiated Power:**\nThe acceleration of the proton is purely centripetal:\n$$w = \\frac{v^2}{R} = \\frac{e v B}{m}$$\nBy Larmor's formula, the rate of energy radiation is:\n$$P = \\frac{e^2 w^2}{6\\pi\\varepsilon_0 c^3} = \\frac{e^2}{6\\pi\\varepsilon_0 c^3} \\left(\\frac{e v B}{m}\\right)^2 = \\frac{e^4 v^2 B^2}{6\\pi\\varepsilon_0 m^2 c^3}$$\n\n**3. Radiated Energy and Energy Ratio:**\nThe total energy lost during the time $\\Delta t$ is:\n$$\\Delta W = P \\Delta t = \\frac{e^4 v^2 B^2}{6\\pi\\varepsilon_0 m^2 c^3} \\left(\\frac{\\pi m}{e B}\\right) = \\frac{e^3 B v^2}{6\\varepsilon_0 m c^3}$$\nThe initial kinetic energy of the proton is $T = \\frac{1}{2} m v^2$, so $v^2 = \\frac{2T}{m}$. Substituting into the expression for $\\Delta W$:\n$$\\Delta W = \\frac{e^3 B}{6\\varepsilon_0 m c^3} \\left(\\frac{2T}{m}\\right) = \\frac{e^3 B}{3\\varepsilon_0 m^2 c^3} T$$\nThus, the relative energy loss is:\n$$\\frac{\\Delta W}{T} = \\frac{e^3 B}{3\\varepsilon_0 m^2 c^3} = \\frac{4\\pi}{3(4\\pi\\varepsilon_0)} \\frac{e^3 B}{m^2 c^3}$$\n\n**4. Numerical Calculation:**\nUsing $e = 1.602 \\times 10^{-19}\\text{ C}$, $B = 1.0\\text{ T}$, $m_p = 1.673 \\times 10^{-27}\\text{ kg}$, $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ F/m}$, and $c = 3.0 \\times 10^8\\text{ m/s}$:\n$$\\frac{\\Delta W}{T} = \\frac{(1.602 \\times 10^{-19})^3 \\times 1.0}{3 (8.854 \\times 10^{-12}) (1.673 \\times 10^{-27})^2 (3.0 \\times 10^8)^3} \\approx 2.05 \\times 10^{-18} \\approx 2 \\times 10^{-18}$$",
        "tags": ["magnetic field", "cyclotron radiation", "Larmor formula", "proton", "synchrotron power"]
    },
    {
        "id": "4.216",
        "title": "Radiative Decay of Kinetic Energy for a Charged Particle in a Magnetic Field",
        "difficulty": 2,
        "question": "A non-relativistic charged particle moves in a transverse uniform magnetic field with induction $B$. Find the time dependence of the particle's kinetic energy diminishing due to radiation. How soon will its kinetic energy decrease $e$-fold? Calculate this time interval for the case:\n(a) of an electron,\n(b) of a proton.",
        "hints": [
            "The radiated power is $P = -\\frac{dT}{dt} = \\frac{q^4 B^2 v^2}{6\\pi\\varepsilon_0 m^2 c^3}$. Express $v^2 = 2T/m$.",
            "This gives $-\\frac{dT}{dt} = \\alpha T$, with damping constant $\\alpha = \\frac{q^4 B^2}{3\\pi\\varepsilon_0 m^3 c^3}$.",
            "The decay law is $T(t) = T_0 e^{-\\alpha t}$, and the $e$-folding time is $\\tau = 1/\\alpha = \\frac{3\\pi\\varepsilon_0 m^3 c^3}{q^4 B^2} \\propto m^3$."
        ],
        "answer": "$T(t) = T_0 e^{-\\alpha t}$, where $\\alpha = \\frac{e^4 B^2}{3\\pi\\varepsilon_0 m^3 c^3}$; $e$-fold decay time $\\tau = 1/\\alpha \\approx 2.5\\text{ s}$ for an electron, and $\\tau \\approx 1.6 \\times 10^{10}\\text{ s} \\approx 0.5 \\times 10^3\\text{ years}$ for a proton (with $B = 1.0\\text{ T}$).",
        "solution": "**1. Radiative Energy Loss Rate:**\nFor a non-relativistic particle of mass $m$ and charge $e$ moving in a transverse magnetic field $B$, the acceleration is centripetal:\n$$w = \\frac{e v B}{m}$$\nBy Larmor's formula, the energy radiated per unit time is:\n$$-\\frac{dT}{dt} = P = \\frac{e^2 w^2}{6\\pi\\varepsilon_0 c^3} = \\frac{e^4 B^2 v^2}{6\\pi\\varepsilon_0 m^2 c^3}$$\nSince the kinetic energy is $T = \\frac{1}{2}mv^2$, we have $v^2 = \\frac{2T}{m}$, giving:\n$$-\\frac{dT}{dt} = \\left(\\frac{e^4 B^2}{3\\pi\\varepsilon_0 m^3 c^3}\\right) T = \\alpha T$$\nwhere the damping constant $\\alpha$ is:\n$$\\alpha = \\frac{e^4 B^2}{3\\pi\\varepsilon_0 m^3 c^3} = \\frac{4}{3(4\\pi\\varepsilon_0)} \\frac{e^4 B^2}{m^3 c^3}$$\n\n**2. Time Dependence and $e$-folding Time:**\nIntegrating the differential equation $-\\frac{dT}{T} = \\alpha \\, dt$ yields:\n$$T(t) = T_0 e^{-\\alpha t}$$\nThe kinetic energy decreases by a factor of $e$ when $t = \\tau = 1/\\alpha$:\n$$\\tau = \\frac{3\\pi\\varepsilon_0 m^3 c^3}{e^4 B^2}$$\n\n**3. Numerical Evaluation (for $B = 1.0\\text{ T}$):**\n**(a) For an electron** ($m_e = 9.109 \\times 10^{-31}\\text{ kg}$):\n$$\\tau_e = \\frac{3\\pi (8.854 \\times 10^{-12})(9.109 \\times 10^{-31})^3 (3.0 \\times 10^8)^3}{(1.602 \\times 10^{-19})^4 (1.0)^2} \\approx 2.5\\text{ s}$$\n**(b) For a proton** ($m_p = 1.673 \\times 10^{-27}\\text{ kg}$):\nSince $\\tau \\propto m^3$,\n$$\\tau_p = \\tau_e \\left(\\frac{m_p}{m_e}\\right)^3 = 2.5 \\times (1836)^3 \\approx 2.5 \\times 6.19 \\times 10^9 \\approx 1.55 \\times 10^{10}\\text{ s} \\approx 0.5 \\times 10^3\\text{ years}$$",
        "tags": ["magnetic field", "radiation damping", "Larmor formula", "electron", "proton"]
    },
    {
        "id": "4.217",
        "title": "Ratio of Poynting Vector Magnitudes from an Oscillating Charge at Retarded Moments",
        "difficulty": 2,
        "question": "A charged particle moves along the $y$ axis according to the law $y = a \\cos\\omega t$, and the point of observation $P$ is located on the $x$ axis at a distance $l$ from the particle ($l \\gg a$). Find the ratio of electromagnetic radiation flow densities $S_1 / S_2$ at the point $P$ at the moments when the coordinate of the particle $y_1 = 0$ and $y_2 = a$. Calculate that ratio if $\\omega = 3.3 \\times 10^6\\text{ s}^{-1}$ and $l = 190\\text{ m}$.",
        "hints": [
            "The radiation detected at observation time $t_{\\text{obs}}$ was emitted at the retarded time $t' = t_{\\text{obs}} - l/c$.",
            "The radiation energy flow density at $P$ is proportional to the square of the particle's acceleration at the retarded time: $S \\propto w_y^2(t')$.",
            "Find $w_y(t') = -\\omega^2 a \\cos(\\omega t_{\\text{obs}} - \\omega l / c)$ for $\\omega t_{\\text{obs},1} = \\pi/2$ (when $y = 0$) and $\\omega t_{\\text{obs},2} = 0$ (when $y = a$)."
        ],
        "answer": "$\\frac{S_1}{S_2} = \\tan^2\\left(\\frac{\\omega l}{c}\\right) = 3.0$",
        "solution": "**1. Retarded Time and Acceleration:**\nThe position of the particle along the $y$-axis is $y(t) = a \\cos\\omega t$, and its acceleration at any emission time $t'$ is:\n$$w_y(t') = \\ddot{y}(t') = -\\omega^2 a \\cos\\omega t'$$\nSince the observer at $P$ is situated on the $x$-axis at distance $l \\gg a$, the time taken for electromagnetic radiation to travel from the particle to $P$ is $l/c$. Therefore, radiation received at observation time $t$ was emitted at the retarded time:\n$$t' = t - \\frac{l}{c}$$\nThe acceleration responsible for the field at $P$ at observation time $t$ is:\n$$w_y(t') = -\\omega^2 a \\cos\\left(\\omega t - \\frac{\\omega l}{c}\\right)$$\n\n**2. Radiation Energy Flow Density:**\nThe Poynting vector magnitude in the wave zone is proportional to the square of the acceleration at the retarded time:\n$$S(t) \\propto [w_y(t')]^2$$\n- At the moment when the particle passes $y_1 = 0$, $\\cos\\omega t_1 = 0$, so $\\omega t_1 = \\pi/2$. The acceleration at emission was:\n$$w_y(t_1') = -\\omega^2 a \\cos\\left(\\frac{\\pi}{2} - \\frac{\\omega l}{c}\\right) = -\\omega^2 a \\sin\\left(\\frac{\\omega l}{c}\\right)$$\n- At the moment when the particle reaches $y_2 = a$, $\\cos\\omega t_2 = 1$, so $\\omega t_2 = 0$. The acceleration at emission was:\n$$w_y(t_2') = -\\omega^2 a \\cos\\left(-\\frac{\\omega l}{c}\\right) = -\\omega^2 a \\cos\\left(\\frac{\\omega l}{c}\\right)$$\n\n**3. Ratio of Flow Densities:**\n$$\\frac{S_1}{S_2} = \\frac{[w_y(t_1')]^2}{[w_y(t_2')]^2} = \\frac{\\sin^2(\\omega l / c)}{\\cos^2(\\omega l / c)} = \\tan^2\\left(\\frac{\\omega l}{c}\\right)$$\n\n**4. Numerical Evaluation:**\nGiven $\\omega = 3.3 \\times 10^6\\text{ s}^{-1}$, $l = 190\\text{ m}$, and $c = 3.0 \\times 10^8\\text{ m/s}$:\n$$\\frac{\\omega l}{c} = \\frac{(3.3 \\times 10^6)(190)}{3.0 \\times 10^8} = \\frac{6.27 \\times 10^8}{3.0 \\times 10^8} = 2.09\\text{ rad} \\approx \\frac{2\\pi}{3} = 120^\\circ$$\nSince $\\tan(120^\\circ) = -\\sqrt{3}$:\n$$\\frac{S_1}{S_2} = (-\\sqrt{3})^2 = 3.0$$",
        "tags": ["electromagnetic waves", "retarded time", "Poynting vector", "dipole radiation"]
    },
    {
        "id": "4.218",
        "title": "Observed Acceleration and Radiation Asymmetry of a Charge in Circular Motion",
        "difficulty": 3,
        "question": "A charged particle moves uniformly with velocity $v$ along a circle of radius $R$ in the $(x, y)$ plane. An observer is located on the $x$ axis at a point $P$ removed from the centre of the circle by a distance $l \\gg R$. Find:\n(a) the relationship between the observed values of the $y$ projection of the particle's acceleration and the $y$ coordinate of the particle;\n(b) the ratio of electromagnetic radiation flow densities $S_1 / S_2$ at the point $P$ at the moments of time when the particle moves, from the standpoint of the observer $P$, toward him and away from him.",
        "hints": [
            "Let $t$ be the emission time and $t' = t + \\frac{l - x(t)}{c}$ the arrival time at observer $P$.",
            "Differentiate the observed coordinate $y'(t') = y(t)$ using $\\frac{dt'}{dt} = 1 - \\frac{v_x}{c} = 1 - \\frac{v y}{c R}$.",
            "The radiation energy flow density satisfies $S \\propto (w_y')^2 \\propto (1 \\mp v/c)^{-4}$ when moving toward ($-$) or away ($+$) from the observer."
        ],
        "answer": "(a) $w_y' = -\\frac{v^2}{R} \\frac{y/R}{(1 - v y / c R)^3}$;\n(b) $\\frac{S_1}{S_2} = \\left(\\frac{1 + v/c}{1 - v/c}\\right)^4$",
        "solution": "**(a) Observed Acceleration:**\nLet the circle be $x(t) = R \\sin\\omega t$ and $y(t) = R \\cos\\omega t$, where $\\omega = v/R$.\nRadiation emitted at time $t$ from position $(x, y)$ arrives at observer $P(l, 0)$ at time:\n$$t' = t + \\frac{l - x(t)}{c}$$\nTaking the differential with respect to emission time $t$:\n$$\\frac{dt'}{dt} = 1 - \\frac{\\dot{x}(t)}{c} = 1 - \\frac{\\omega R \\cos\\omega t}{c} = 1 - \\frac{v}{c}\\frac{y}{R}$$\nThe observed velocity component is:\n$$\\frac{dy'}{dt'} = \\frac{dy/dt}{dt'/dt} = \\frac{-\\omega R \\sin\\omega t}{1 - \\frac{v y}{c R}}$$\nDifferentiating again with respect to $t'$ using $\\frac{d}{dt'} = \\frac{1}{dt'/dt} \\frac{d}{dt}$:\n$$w_y' = \\frac{d^2 y'}{dt'^2} = \\frac{1}{1 - \\frac{v y}{c R}} \\frac{d}{dt}\\left(\\frac{-\\omega R \\sin\\omega t}{1 - \\frac{v y}{c R}}\\right)$$\nCarrying out the differentiation, at positions where the centripetal acceleration dominates along the $y$-axis:\n$$w_y' = -\\frac{v^2}{R} \\frac{y/R}{\\left(1 - \\frac{v y}{c R}\\right)^3}$$\n\n**(b) Ratio of Radiation Flow Densities:**\nThe energy flow density $S$ received at the observer is proportional to the square of the observed apparent transverse acceleration:\n$$S \\propto (w_y')^2$$\nWhen the particle moves along the line of sight toward the observer ($v_x = +v$, so $dt'/dt = 1 - v/c$), the observed acceleration is amplified by $(1 - v/c)^{-2}$, giving radiation density $S_1 \\propto (1 - v/c)^{-4}$.\nConversely, when moving directly away ($v_x = -v$, so $dt'/dt = 1 + v/c$), $S_2 \\propto (1 + v/c)^{-4}$.\nTherefore, the ratio of the energy flow densities is:\n$$\\frac{S_1}{S_2} = \\frac{(1 - v/c)^{-4}}{(1 + v/c)^{-4}} = \\left(\\frac{1 + v/c}{1 - v/c}\\right)^4$$",
        "tags": ["synchrotron radiation", "Doppler beaming", "retarded time", "Poynting vector"]
    },
    {
        "id": "4.219",
        "title": "Total Radiated Power of an Elementary Dipole from Peak Equatorial Intensity",
        "difficulty": 2,
        "question": "An electromagnetic wave emitted by an elementary dipole propagates in vacuum so that in the far field zone the mean value of the energy flow density is equal to $S_0$ at the point removed from the dipole by a distance $r$ along the perpendicular drawn to the dipole's axis. Find the mean radiation power $P$ of the dipole.",
        "hints": [
            "The angular distribution of the Poynting vector magnitude for an electric dipole is $S(\\theta) = S_0 \\sin^2\\theta$, where $\\theta$ is the polar angle relative to the dipole axis.",
            "Integrate $S(\\theta)$ over a sphere of radius $r$: $P = \\int_0^\\pi S_0 \\sin^2\\theta (2\\pi r^2 \\sin\\theta \\, d\\theta)$.",
            "Use $\\int_0^\\pi \\sin^3\\theta \\, d\\theta = 4/3$."
        ],
        "answer": "$P = \\frac{8\\pi}{3} r^2 S_0$",
        "solution": "**1. Angular Distribution of Dipole Radiation:**\nThe time-averaged Poynting vector of an elementary dipole in the wave zone at distance $r$ depends on the polar angle $\\theta$ measured from the dipole axis:\n$$\\langle S(\\theta) \\rangle = \\frac{1}{4\\pi\\varepsilon_0} \\frac{\\omega^4 p_0^2}{32\\pi^2 c^3 r^2} \\sin^2\\theta = S_0 \\sin^2\\theta$$\nwhere $S_0$ is the intensity in the equatorial plane ($\\theta = \\pi/2$, perpendicular to the dipole axis).\n\n**2. Integration Over the Enclosing Sphere:**\nThe total mean radiated power $P$ is the integral of $\\langle S(\\theta) \\rangle$ over the surface of a sphere of radius $r$:\n$$P = \\oint \\langle S \\rangle \\, dA = \\int_0^\\pi (S_0 \\sin^2\\theta) (2\\pi r^2 \\sin\\theta \\, d\\theta) = 2\\pi r^2 S_0 \\int_0^\\pi \\sin^3\\theta \\, d\\theta$$\n\n**3. Evaluation of the Angular Integral:**\n$$\\int_0^\\pi \\sin^3\\theta \\, d\\theta = \\int_{-1}^1 (1 - \\mu^2) \\, d\\mu = \\left[\\mu - \\frac{\\mu^3}{3}\\right]_{-1}^1 = \\frac{4}{3}$$\n\n**4. Final Power:**\n$$P = 2\\pi r^2 S_0 \\left(\\frac{4}{3}\\right) = \\frac{8\\pi}{3} r^2 S_0$$",
        "tags": ["dipole radiation", "Poynting vector", "radiation pattern", "total radiated power"]
    },
    {
        "id": "4.220",
        "title": "Mean Electromagnetic Energy Density in the Equatorial Plane of a Dipole",
        "difficulty": 2,
        "question": "The mean power radiated by an elementary dipole is equal to $P_0$. Find the mean space density of energy $\\langle w \\rangle$ of the electromagnetic field in vacuum in the far field zone at the point removed from the dipole by a distance $r$ along the perpendicular drawn to the dipole's axis.",
        "hints": [
            "From the previous problem, the peak equatorial energy flow density $S_0$ is related to total power by $P_0 = \\frac{8\\pi}{3} r^2 S_0$.",
            "In vacuum, the Poynting vector magnitude and the energy density of a plane or spherical wave in the wave zone are related by $S = c w$.",
            "Combine to express $\\langle w \\rangle = S_0 / c$ in terms of $P_0$."
        ],
        "answer": "$\\langle w \\rangle = \\frac{3 P_0}{8\\pi r^2 c}$",
        "solution": "**1. Relation Between Power and Equatorial Intensity:**\nFor an elementary dipole in vacuum, the angular distribution of radiated intensity is $\\langle S(\\theta) \\rangle = S_0 \\sin^2\\theta$, where $S_0$ is the mean energy flow density in the plane perpendicular to the dipole axis ($\\theta = \\pi/2$).\nIntegrating over a sphere of radius $r$ gives the total radiated power:\n$$P_0 = \\frac{8\\pi}{3} r^2 S_0 \\implies S_0 = \\frac{3 P_0}{8\\pi r^2}$$\n\n**2. Relation Between Energy Flow Density and Energy Density:**\nIn the far field (wave zone), the electromagnetic wave is locally a transverse plane wave propagating at speed $c$. The Poynting vector magnitude and the electromagnetic energy density $w = \\frac{1}{2}(\\varepsilon_0 E^2 + \\mu_0 H^2)$ satisfy:\n$$S = c w$$\nTherefore, the time-averaged energy density at equatorial distance $r$ is:\n$$\\langle w \\rangle = \\frac{S_0}{c}$$\n\n**3. Substitution:**\n$$\\langle w \\rangle = \\frac{3 P_0}{8\\pi r^2 c}$$",
        "tags": ["dipole radiation", "energy density", "Poynting vector", "wave zone"]
    },
    {
        "id": "4.221",
        "title": "Radiated Power of a Rotating Electric Dipole",
        "difficulty": 2,
        "question": "An electric dipole whose modulus is constant and whose moment is equal to $p$ rotates with constant angular velocity $\\omega$ about the axis drawn at right angles to the axis of the dipole and passing through its midpoint. Find the power $P$ radiated by such a dipole.",
        "hints": [
            "In Cartesian coordinates with the rotation axis along $z$, the dipole moment vector is $\\vec{p}(t) = p(\\cos\\omega t \\, \\hat{i} + \\sin\\omega t \\, \\hat{j})$.",
            "Calculate $\\ddot{\\vec{p}}(t) = -\\omega^2 \\vec{p}(t)$ and its modulus squared: $|\\ddot{\\vec{p}}|^2 = p^2 \\omega^4$.",
            "Apply the dipole radiation formula $P = \\frac{1}{4\\pi\\varepsilon_0} \\frac{2|\\ddot{\\vec{p}}|^2}{3 c^3}$."
        ],
        "answer": "$P = \\frac{p^2 \\omega^4}{6\\pi\\varepsilon_0 c^3} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{2 p^2 \\omega^4}{3 c^3}$",
        "solution": "**1. Dipole Moment Vector:**\nLet the rotation axis be the $z$-axis. In the $(x, y)$ plane perpendicular to the rotation axis, the components of the rotating dipole of constant modulus $p$ are:\n$$p_x(t) = p \\cos\\omega t, \\quad p_y(t) = p \\sin\\omega t, \\quad p_z(t) = 0$$\n\n**2. Second Time Derivative:**\nDifferentiating twice with respect to time:\n$$\\ddot{p}_x(t) = -\\omega^2 p \\cos\\omega t$$\n$$\\ddot{p}_y(t) = -\\omega^2 p \\sin\\omega t$$\n$$\\ddot{p}_z(t) = 0$$\nThe square of the second derivative is:\n$$|\\ddot{\\vec{p}}(t)|^2 = \\ddot{p}_x^2 + \\ddot{p}_y^2 = \\omega^4 p^2 (\\cos^2\\omega t + \\sin^2\\omega t) = p^2 \\omega^4$$\nRemarkably, $|\\ddot{\\vec{p}}(t)|^2$ is independent of time!\n\n**3. Radiated Power:**\nThe total power radiated by an arbitrary accelerating dipole moment $\\vec{p}(t)$ in vacuum is given by Larmor's dipole formula:\n$$P = \\frac{1}{4\\pi\\varepsilon_0} \\frac{2 |\\ddot{\\vec{p}}|^2}{3 c^3}$$\nSubstituting $|\\ddot{\\vec{p}}|^2 = p^2 \\omega^4$:\n$$P = \\frac{2 p^2 \\omega^4}{3 (4\\pi\\varepsilon_0) c^3} = \\frac{p^2 \\omega^4}{6\\pi\\varepsilon_0 c^3}$$",
        "tags": ["rotating dipole", "dipole radiation", "Larmor formula", "radiated power"]
    },
    {
        "id": "4.222",
        "title": "Thomson Scattering Cross Section of a Free Electron in an EM Wave",
        "difficulty": 2,
        "question": "A free electron is located in the field of a plane monochromatic electromagnetic wave. Neglecting the magnetic component of the Lorentz force, find the ratio of the mean energy radiated by the oscillating electron per unit time to the mean value of the energy flow density of the incident wave.",
        "hints": [
            "The equation of motion driven by the wave electric field $E(t) = E_0 \\cos\\omega t$ is $m \\ddot{x} = -e E_0 \\cos\\omega t$.",
            "The acceleration is $\\ddot{x} = -\\frac{e E_0}{m} \\cos\\omega t$, giving mean radiated power $\\langle P \\rangle = \\frac{e^2 \\langle \\ddot{x}^2 \\rangle}{6\\pi\\varepsilon_0 c^3} = \\frac{e^4 E_0^2}{12\\pi\\varepsilon_0 m^2 c^3}$.",
            "Divide by the incident wave intensity $\\langle S \\rangle = \\frac{1}{2} \\varepsilon_0 c E_0^2$ to find the scattering cross-section $\\sigma_T = \\frac{8\\pi}{3} r_e^2$."
        ],
        "answer": "$\\frac{\\langle P \\rangle}{\\langle S \\rangle} = \\frac{e^4}{6\\pi\\varepsilon_0^2 m^2 c^4} = \\frac{8\\pi}{3} r_e^2 \\approx 6.65 \\times 10^{-29}\\text{ m}^2$",
        "solution": "**1. Equation of Motion of the Free Electron:**\nIn the presence of the incident wave's linearly polarized electric field $E(t) = E_0 \\cos\\omega t$, Newton's second law for the electron is:\n$$m \\ddot{x} = -e E_0 \\cos\\omega t \\implies \\ddot{x}(t) = -\\frac{e E_0}{m} \\cos\\omega t$$\n\n**2. Mean Radiated Power:**\nThe instantaneous power radiated by the accelerating electron is given by Larmor's formula:\n$$P(t) = \\frac{e^2 [\\ddot{x}(t)]^2}{6\\pi\\varepsilon_0 c^3} = \\frac{e^4 E_0^2}{6\\pi\\varepsilon_0 m^2 c^3} \\cos^2\\omega t$$\nTaking the time average over an oscillation cycle (using $\\langle \\cos^2\\omega t \\rangle = 1/2$):\n$$\\langle P \\rangle = \\frac{e^4 E_0^2}{12\\pi\\varepsilon_0 m^2 c^3}$$\n\n**3. Incident Wave Intensity:**\nThe time-averaged energy flow density (Poynting vector magnitude) of the incident wave in vacuum is:\n$$\\langle S \\rangle = \\frac{1}{2} \\varepsilon_0 c E_0^2$$\n\n**4. Ratio of Radiated Power to Incident Intensity:**\nThe ratio has the dimensions of an area and represents the Thomson scattering cross section $\\sigma_T$:\n$$\\sigma_T = \\frac{\\langle P \\rangle}{\\langle S \\rangle} = \\frac{\\frac{e^4 E_0^2}{12\\pi\\varepsilon_0 m^2 c^3}}{\\frac{1}{2} \\varepsilon_0 c E_0^2} = \\frac{e^4}{6\\pi\\varepsilon_0^2 m^2 c^4}$$\nIn terms of the classical electron radius $r_e = \\frac{e^2}{4\\pi\\varepsilon_0 m c^2} \\approx 2.82 \\times 10^{-15}\\text{ m}$:\n$$\\sigma_T = \\frac{8\\pi}{3} r_e^2 \\approx \\frac{8\\pi}{3} (2.818 \\times 10^{-15}\\text{ m})^2 \\approx 6.65 \\times 10^{-29}\\text{ m}^2 = 0.665\\text{ barn}$$",
        "tags": ["Thomson scattering", "cross section", "free electron", "radiation power", "Larmor formula"]
    },
    {
        "id": "4.223",
        "title": "Resonant and Rayleigh Scattering by an Elastically Bound Electron",
        "difficulty": 2,
        "question": "A plane electromagnetic wave with frequency $\\omega$ falls upon an elastically bound electron whose natural frequency equals $\\omega_0$. Neglecting the damping of oscillations, find the ratio of the mean energy dissipated (scattered) by the electron per unit time to the mean value of the energy flow density of the incident wave.",
        "hints": [
            "The equation of forced oscillation is $\\ddot{x} + \\omega_0^2 x = -\\frac{e E_0}{m} \\cos\\omega t$.",
            "The steady-state solution is $x(t) = \\frac{-e E_0 / m}{\\omega_0^2 - \\omega^2} \\cos\\omega t$, with acceleration $\\ddot{x}(t) = \\frac{\\omega^2 e E_0 / m}{\\omega_0^2 - \\omega^2} \\cos\\omega t$.",
            "Calculate $\\langle P \\rangle$ via Larmor's formula and divide by $\\langle S \\rangle = \\frac{1}{2}\\varepsilon_0 c E_0^2$ to find $\\sigma(\\omega) = \\sigma_T \\frac{\\omega^4}{(\\omega^2 - \\omega_0^2)^2}$."
        ],
        "answer": "$\\frac{\\langle P \\rangle}{\\langle S \\rangle} = \\frac{e^4}{6\\pi\\varepsilon_0^2 m^2 c^4} \\left(\\frac{\\omega^2}{\\omega^2 - \\omega_0^2}\\right)^2 = \\frac{8\\pi}{3} r_e^2 \\frac{\\omega^4}{(\\omega^2 - \\omega_0^2)^2}$",
        "solution": "**1. Forced Oscillations of the Bound Electron:**\nThe equation of motion for an electron of mass $m$, charge $e$, and natural frequency $\\omega_0$ driven by the electric field $E(t) = E_0 \\cos\\omega t$ (neglecting radiative damping) is:\n$$\\ddot{x} + \\omega_0^2 x = -\\frac{e E_0}{m} \\cos\\omega t$$\nSeeking a steady-state harmonic solution $x(t) = x_0 \\cos\\omega t$:\n$$(-\\omega^2 + \\omega_0^2) x_0 = -\\frac{e E_0}{m} \\implies x_0 = \\frac{e E_0 / m}{\\omega^2 - \\omega_0^2}$$\nThe acceleration is:\n$$\\ddot{x}(t) = -\\omega^2 x(t) = -\\frac{\\omega^2 e E_0 / m}{\\omega^2 - \\omega_0^2} \\cos\\omega t$$\n\n**2. Mean Radiated Power:**\nUsing Larmor's formula for the oscillating charge:\n$$P(t) = \\frac{e^2 [\\ddot{x}(t)]^2}{6\\pi\\varepsilon_0 c^3} = \\frac{e^4 E_0^2}{6\\pi\\varepsilon_0 m^2 c^3} \\frac{\\omega^4}{(\\omega^2 - \\omega_0^2)^2} \\cos^2\\omega t$$\nTime-averaging yields:\n$$\\langle P \\rangle = \\frac{e^4 E_0^2}{12\\pi\\varepsilon_0 m^2 c^3} \\frac{\\omega^4}{(\\omega^2 - \\omega_0^2)^2}$$\n\n**3. Ratio to Incident Flow Density:**\nThe incident wave intensity is $\\langle S \\rangle = \\frac{1}{2} \\varepsilon_0 c E_0^2$. Therefore, the scattering cross section is:\n$$\\sigma(\\omega) = \\frac{\\langle P \\rangle}{\\langle S \\rangle} = \\frac{e^4}{6\\pi\\varepsilon_0^2 m^2 c^4} \\left(\\frac{\\omega^2}{\\omega^2 - \\omega_0^2}\\right)^2 = \\frac{8\\pi}{3} r_e^2 \\frac{\\omega^4}{(\\omega^2 - \\omega_0^2)^2}$$\n\n**Note on Physical Limits:**\n- When $\\omega \\ll \\omega_0$, $\\sigma \\propto \\omega^4 \\propto 1/\\lambda^4$, which is the famous Rayleigh scattering law explaining the blue color of the sky.\n- When $\\omega \\gg \\omega_0$, $\\sigma \\to \\frac{8\\pi}{3} r_e^2 = \\sigma_T$, recovering Thomson scattering for a free electron.",
        "tags": ["Rayleigh scattering", "bound electron", "resonance", "scattering cross section"]
    },
    {
        "id": "4.224",
        "title": "Critical Radius of a Spherical Particle in Solar Radiation Pressure and Gravity Balance",
        "difficulty": 2,
        "question": "Assuming an interplanetary dust particle to have the form of a sphere that absorbs all incident light, find the radius $R$ of the particle for which its gravitational attraction to the Sun is precisely counterbalanced by the force that solar light exerts on it. The total power of light radiated by the Sun equals $P = 4.0 \\times 10^{26}\\text{ W}$, and the density of the particle is $\\rho = 1.0\\text{ g/cm}^3$.",
        "hints": [
            "At distance $r$ from the Sun, the light intensity is $I = P / (4\\pi r^2)$.",
            "A perfectly absorbing sphere of radius $R$ intercepts cross-sectional area $\\pi R^2$, experiencing radiation force $F_{\\text{rad}} = \\frac{I \\pi R^2}{c} = \\frac{P R^2}{4 c r^2}$.",
            "Equate $F_{\\text{rad}}$ to the solar gravitational attraction $F_g = \\frac{\\gamma M_{\\odot} m}{r^2} = \\frac{4\\pi \\gamma M_{\\odot} \\rho R^3}{3 r^2}$ and solve for $R$."
        ],
        "answer": "$R = \\frac{3 P}{16 \\pi \\gamma \\rho M_{\\odot} c} \\approx 0.6\\,\\mu\\text{m}$",
        "solution": "**1. Radiation Force on an Absorbing Sphere:**\nAt a distance $r$ from the Sun, the solar flux (Poynting vector magnitude) is:\n$$I(r) = \\frac{P}{4\\pi r^2}$$\nSince the spherical particle of radius $R$ is completely absorbing, the radiation pressure is $p = I/c$. The cross-sectional area projected normal to the incident rays is $\\pi R^2$. Hence, the outward radiation force is:\n$$F_{\\text{rad}} = p (\\pi R^2) = \\frac{I \\pi R^2}{c} = \\frac{P \\pi R^2}{4\\pi r^2 c} = \\frac{P R^2}{4 c r^2}$$\n\n**2. Gravitational Attraction to the Sun:**\nThe inward gravitational force exerted by the Sun of mass $M_{\\odot}$ on the particle of mass $m = \\frac{4}{3}\\pi R^3 \\rho$ is:\n$$F_g = \\frac{\\gamma M_{\\odot} m}{r^2} = \\frac{\\gamma M_{\\odot} \\left(\\frac{4}{3}\\pi R^3 \\rho\\right)}{r^2} = \\frac{4\\pi \\gamma M_{\\odot} \\rho R^3}{3 r^2}$$\nwhere $\\gamma$ is the universal gravitational constant.\n\n**3. Equilibrium Condition:**\nSetting $F_{\\text{rad}} = F_g$:\n$$\\frac{P R^2}{4 c r^2} = \\frac{4\\pi \\gamma M_{\\odot} \\rho R^3}{3 r^2}$$\nNotice that the distance $r$ cancels out completely! Solving for the radius $R$:\n$$R = \\frac{3 P}{16 \\pi \\gamma \\rho M_{\\odot} c}$$\n\n**4. Numerical Evaluation:**\nGiven:\n- $P = 4.0 \\times 10^{26}\\text{ W}$\n- $\\gamma = 6.674 \\times 10^{-11}\\text{ m}^3/(\\text{kg}\\cdot\\text{s}^2)$\n- $\\rho = 1.0\\text{ g/cm}^3 = 1000\\text{ kg/m}^3$\n- $M_{\\odot} = 1.989 \\times 10^{30}\\text{ kg}$\n- $c = 3.0 \\times 10^8\\text{ m/s}$\n\n$$R = \\frac{3 \\times 4.0 \\times 10^{26}}{16 \\pi (6.674 \\times 10^{-11})(1000)(1.989 \\times 10^{30})(3.0 \\times 10^8)} \\approx \\frac{1.2 \\times 10^{27}}{2.00 \\times 10^{33}} \\approx 0.60 \\times 10^{-6}\\text{ m} = 0.6\\,\\mu\\text{m}$$",
        "tags": ["radiation pressure", "solar radiation", "gravitational balance", "Poynting-Robertson effect"]
    },
    {
        "id": "4.225",
        "title": "Radiation Damping and Natural Spectral Line Width of an Atomic Oscillator",
        "difficulty": 2,
        "question": "An electron undergoes damped natural harmonic oscillations with frequency $\\omega_0$ under the action of its own radiation reaction force (radiation damping). Find:\n(a) the radiation damping coefficient $\\gamma_{\\text{rad}}$ and the lifetime $\\tau$ of the oscillating state;\n(b) the natural spectral line width $\\Delta\\omega$ and the quality factor $Q$ of this atomic oscillator for an optical transition with wavelength $\\lambda = 0.60\\,\\mu\\text{m}$.",
        "hints": [
            "The energy radiated per period $T = 2\\pi / \\omega_0$ by an oscillator of energy $E = \\frac{1}{2}m\\omega_0^2 a^2$ is $\\Delta E = \\frac{e^2 \\omega_0^4 a^2}{12\\pi\\varepsilon_0 c^3} T$.",
            "The damping rate is $\\gamma_{\\text{rad}} = \\frac{1}{2E}\\frac{dE}{dt} = \\frac{e^2 \\omega_0^2}{6\\pi\\varepsilon_0 m c^3} = \\frac{2 r_e \\omega_0^2}{3 c}$.",
            "The natural line width is $\\Delta\\omega = 2\\gamma_{\\text{rad}}$ (or the full width at half maximum FWHM), and the quality factor is $Q = \\omega_0 / (2\\gamma_{\\text{rad}})$."
        ],
        "answer": "(a) $\\gamma_{\\text{rad}} = \\frac{e^2 \\omega_0^2}{6\\pi\\varepsilon_0 m c^3} = \\frac{2 r_e \\omega_0^2}{3 c}$, $\\tau = \\frac{1}{2\\gamma_{\\text{rad}}}$;\n(b) $\\Delta\\omega = \\frac{e^2 \\omega_0^2}{6\\pi\\varepsilon_0 m c^3} \\approx 1.2 \\times 10^8\\text{ s}^{-1}$, $Q = \\frac{3 c}{4 r_e \\omega_0} \\approx 2.6 \\times 10^7$",
        "solution": "**(a) Radiative Damping Coefficient:**\nFor an electron oscillating as $x(t) = a \\cos\\omega_0 t$, its total mechanical energy is $E = \\frac{1}{2} m \\omega_0^2 a^2$.\nThe mean rate of energy loss through dipole radiation is:\n$$\\langle P \\rangle = -\\frac{dE}{dt} = \\frac{e^2 \\langle \\ddot{x}^2 \\rangle}{6\\pi\\varepsilon_0 c^3} = \\frac{e^2 \\omega_0^4 a^2}{12\\pi\\varepsilon_0 c^3} = \\left(\\frac{e^2 \\omega_0^2}{6\\pi\\varepsilon_0 m c^3}\\right) E$$\nComparing with the energy decay equation $E(t) = E_0 e^{-2\\gamma t} \\implies \\frac{dE}{dt} = -2\\gamma E$, we identify the radiative damping coefficient:\n$$\\gamma_{\\text{rad}} = \\frac{e^2 \\omega_0^2}{12\\pi\\varepsilon_0 m c^3} = \\frac{r_e \\omega_0^2}{3 c}$$\n(In standard spectroscopy literature, the full intensity decay rate is $\\Gamma = 2\\gamma_{\\text{rad}} = \\frac{e^2 \\omega_0^2}{6\\pi\\varepsilon_0 m c^3}$.)\nThe radiative lifetime of the excited state is:\n$$\\tau = \\frac{1}{\\Gamma} = \\frac{6\\pi\\varepsilon_0 m c^3}{e^2 \\omega_0^2} = \\frac{3 c}{2 r_e \\omega_0^2}$$\n\n**(b) Natural Line Width and Quality Factor:**\nFor an optical transition with $\\lambda = 0.60\\,\\mu\\text{m} = 6.0 \\times 10^{-7}\\text{ m}$:\n$$\\omega_0 = \\frac{2\\pi c}{\\lambda} = \\frac{2\\pi (3.0 \\times 10^8)}{6.0 \\times 10^{-7}} = 3.14 \\times 10^{15}\\text{ rad/s}$$\nThe full width at half-maximum (natural line width) of the radiated spectrum is:\n$$\\Delta\\omega = \\Gamma = \\frac{e^2 \\omega_0^2}{6\\pi\\varepsilon_0 m c^3} = \\frac{2 r_e \\omega_0^2}{3 c}$$\nWith $r_e = 2.82 \\times 10^{-15}\\text{ m}$:\n$$\\Delta\\omega = \\frac{2 (2.82 \\times 10^{-15})(3.14 \\times 10^{15})^2}{3 (3.0 \\times 10^8)} \\approx 1.23 \\times 10^8\\text{ rad/s}$$\nThe quality factor $Q$ of the oscillator is:\n$$Q = \\frac{\\omega_0}{\\Delta\\omega} = \\frac{3.14 \\times 10^{15}}{1.23 \\times 10^8} \\approx 2.6 \\times 10^7$$",
        "tags": ["radiation reaction", "Abraham-Lorentz force", "natural line width", "lifetime", "Q-factor"]
    },
    {
        "id": "4.226",
        "title": "Radiation Resistance of a Thin Linear Half-Wave Antenna",
        "difficulty": 3,
        "question": "A thin linear center-fed antenna has total length $l = \\lambda / 2$ (half-wave dipole). The current distribution along the antenna wire (lying on $-l/2 \\le z \\le l/2$) is sinusoidal: $I(z) = I_0 \\cos(k z)$, where $k = 2\\pi / \\lambda$. Find the total power $P$ radiated by the antenna in vacuum and its radiation resistance $R_{\\text{rad}} = 2P / I_0^2$.",
        "hints": [
            "The electric field in the far zone at polar angle $\\theta$ is $E_\\theta = \\frac{I_0}{2\\pi \\varepsilon_0 c r} \\frac{\\cos\\left(\\frac{\\pi}{2} \\cos\\theta\\right)}{\\sin\\theta}$.",
            "Integrate the Poynting vector $S(\\theta) = \\frac{1}{2} \\varepsilon_0 c |E_\\theta|^2$ over the sphere: $P = \\frac{I_0^2}{4\\pi \\varepsilon_0 c} \\int_0^\\pi \\frac{\\cos^2\\left(\\frac{\\pi}{2}\\cos\\theta\\right)}{\\sin\\theta} \\, d\\theta$.",
            "Evaluate the standard integral $\\int_0^\\pi \\frac{\\cos^2\\left(\\frac{\\pi}{2}\\cos\\theta\\right)}{\\sin\\theta} \\, d\\theta = \\frac{\\text{Cin}(2\\pi)}{2} \\approx 1.2188$ to find $R_{\\text{rad}} \\approx 73.1\\,\\Omega$."
        ],
        "answer": "$R_{\\text{rad}} = \\frac{1}{2\\pi} \\sqrt{\\frac{\\mu_0}{\\varepsilon_0}} \\int_0^{2\\pi} \\frac{1 - \\cos u}{u} \\, du \\approx 73.1\\,\\Omega$",
        "solution": "**1. Far-Field Amplitude of Half-Wave Dipole:**\nFor an antenna along the $z$-axis with $l = \\lambda/2$ carrying current $I(z) = I_0 \\cos(kz)$, each segment $dz$ radiates as an elementary dipole. Superposition in the wave zone gives the electric field:\n$$E_\\theta(r, \\theta) = \\frac{i \\sqrt{\\mu_0 / \\varepsilon_0} I_0}{2\\pi r} \\frac{\\cos\\left(\\frac{\\pi}{2}\\cos\\theta\\right)}{\\sin\\theta} e^{i(kr - \\omega t)}$$\n\n**2. Poynting Vector and Total Radiated Power:**\nThe time-averaged Poynting vector magnitude is:\n$$\\langle S(\\theta) \\rangle = \\frac{1}{2} \\sqrt{\\frac{\\varepsilon_0}{\\mu_0}} |E_\\theta|^2 = \\frac{I_0^2}{8\\pi^2 r^2} \\sqrt{\\frac{\\mu_0}{\\varepsilon_0}} \\frac{\\cos^2\\left(\\frac{\\pi}{2}\\cos\\theta\\right)}{\\sin^2\\theta}$$\nIntegrating over the sphere of radius $r$:\n$$P = \\int_0^\\pi \\langle S(\\theta) \\rangle (2\\pi r^2 \\sin\\theta \\, d\\theta) = \\frac{I_0^2}{4\\pi} \\sqrt{\\frac{\\mu_0}{\\varepsilon_0}} \\int_0^\\pi \\frac{\\cos^2\\left(\\frac{\\pi}{2}\\cos\\theta\\right)}{\\sin\\theta} \\, d\\theta$$\n\n**3. Evaluation of the Angular Integral:**\nLet $u = \\pi(1 - \\cos\\theta)$ or using standard cosine integral identities:\n$$\\int_0^\\pi \\frac{\\cos^2\\left(\\frac{\\pi}{2}\\cos\\theta\\right)}{\\sin\\theta} \\, d\\theta = \\frac{1}{2} \\int_0^{2\\pi} \\frac{1 - \\cos u}{u} \\, du = \\frac{\\text{Cin}(2\\pi)}{2} \\approx \\frac{2.4377}{2} \\approx 1.2188$$\n\n**4. Radiation Resistance:**\nWith vacuum wave impedance $Z_0 = \\sqrt{\\frac{\\mu_0}{\\varepsilon_0}} \\approx 376.73\\,\\Omega$:\n$$P = \\frac{I_0^2}{4\\pi} (376.73)(1.2188) \\approx 36.56 I_0^2$$\nBy definition, $P = \\frac{1}{2} I_0^2 R_{\\text{rad}}$, so:\n$$R_{\\text{rad}} = \\frac{2P}{I_0^2} \\approx 2 \\times 36.56 \\approx 73.1\\,\\Omega$$",
        "tags": ["half-wave antenna", "radiation resistance", "antenna theory", "Poynting vector"]
    },
    {
        "id": "4.227",
        "title": "Relativistic Bremsstrahlung Power of an Electron in a Collinear Electric Field",
        "difficulty": 3,
        "question": "A relativistic electron with mass $m$, charge $e$, and Lorentz factor $\\gamma = 1 / \\sqrt{1 - v^2/c^2} \\gg 1$ moves along a straight line in a uniform longitudinal electric field $E$. Find the total power $P$ radiated by the electron in the laboratory reference frame, and compare it with the mechanical work done per second by the electric force.",
        "hints": [
            "Use the relativistic Liénard generalization of Larmor's formula: $P = \\frac{e^2 \\gamma^6}{6\\pi\\varepsilon_0 c^3} [\\dot{\\vec{v}}^2 - (\\vec{\\beta} \\times \\dot{\\vec{v}})^2]$.",
            "For rectilinear motion parallel to the field, $\\vec{\\beta} \\times \\dot{\\vec{v}} = 0$, and the relativistic equation of motion gives $\\frac{d(m\\gamma v)}{dt} = e E \\implies m\\gamma^3 \\dot{v} = e E$.",
            "Substitute $\\dot{v} = \\frac{e E}{m\\gamma^3}$ into Liénard's formula and calculate the ratio $P / (e E v)$."
        ],
        "answer": "$P = \\frac{e^4 E^2}{6\\pi\\varepsilon_0 m^2 c^3}$; ratio $\\frac{P}{F v} = \\frac{2}{3} \\frac{r_e e E}{m c^2} \\frac{c}{v} \\ll 1$",
        "solution": "**1. Relativistic Acceleration in a Longitudinal Field:**\nThe relativistic equation of motion for a particle of charge $e$ and rest mass $m$ in a longitudinal electric field $E$ parallel to its velocity $\\vec{v}$ is:\n$$\\frac{dp}{dt} = \\frac{d(m\\gamma v)}{dt} = e E$$\nSince $\\frac{d\\gamma}{dt} = \\gamma^3 \\frac{v \\dot{v}}{c^2}$, we have:\n$$\\frac{d(m\\gamma v)}{dt} = m\\gamma \\dot{v} + m\\dot{\\gamma} v = m\\gamma \\dot{v} + m\\gamma^3 \\frac{v^2 \\dot{v}}{c^2} = m\\gamma^3 \\dot{v}\\left(\\frac{1}{\\gamma^2} + \\frac{v^2}{c^2}\\right) = m\\gamma^3 \\dot{v}$$\nThus, the coordinate acceleration is:\n$$\\dot{v} = \\frac{e E}{m\\gamma^3}$$\n\n**2. Relativistic Radiated Power (Liénard's Formula):**\nThe total power radiated by an accelerating relativistic charge in the laboratory frame is given by Liénard's formula:\n$$P = \\frac{e^2 \\gamma^6}{6\\pi\\varepsilon_0 c^3} \\left[\\dot{\\vec{v}}^2 - (\\vec{\\beta} \\times \\dot{\\vec{v}})^2\\right]$$\nSince $\\vec{v}$ and $\\dot{\\vec{v}}$ are collinear, the cross product vanishes:\n$$P = \\frac{e^2 \\gamma^6 \\dot{v}^2}{6\\pi\\varepsilon_0 c^3}$$\nSubstituting $\\dot{v} = \\frac{e E}{m\\gamma^3}$:\n$$P = \\frac{e^2 \\gamma^6}{6\\pi\\varepsilon_0 c^3} \\left(\\frac{e E}{m\\gamma^3}\\right)^2 = \\frac{e^4 E^2}{6\\pi\\varepsilon_0 m^2 c^3}$$\nRemarkably, for longitudinal acceleration, the radiated power is completely independent of the Lorentz factor $\\gamma$ and particle energy!\n\n**3. Comparison with Mechanical Power:**\nThe mechanical rate of work done by the field is $P_{\\text{mech}} = F v = e E v$.\nThe ratio of radiative energy loss to mechanical work is:\n$$\\frac{P}{P_{\\text{mech}}} = \\frac{e^4 E^2}{6\\pi\\varepsilon_0 m^2 c^3 e E v} = \\frac{e^3 E}{6\\pi\\varepsilon_0 m^2 c^3 v} = \\frac{2}{3} \\left(\\frac{e^2}{4\\pi\\varepsilon_0 m c^2}\\right) \\frac{e E}{m c^2} \\frac{c}{v} = \\frac{2}{3} \\frac{r_e (e E)}{m c^2} \\frac{c}{v}$$\nFor macroscopic electric fields ($e E r_e \\ll m c^2$), radiation loss in linear accelerators is negligible.",
        "tags": ["relativistic electrodynamics", "bremsstrahlung", "Lienard formula", "linear accelerator"]
    },
    {
        "id": "4.228",
        "title": "Synchrotron Radiation Power and Energy Loss per Revolution",
        "difficulty": 3,
        "question": "A relativistic electron with rest mass $m$, charge $e$, and energy $E = \\gamma m c^2 \\gg m c^2$ revolves along a circle of radius $R$ in a uniform transverse magnetic field $B$. Find:\n(a) the total power $P$ radiated by the electron;\n(b) the energy $\\Delta E$ lost by the electron through radiation per single revolution.",
        "hints": [
            "For circular motion, the acceleration is transverse: $\\dot{v} = \\frac{v^2}{R} = \\frac{e v B}{\\gamma m}$, and $\\vec{v} \\perp \\dot{\\vec{v}}$.",
            "In Liénard's formula with $\\vec{\\beta} \\perp \\dot{\\vec{v}}$: $P = \\frac{e^2 \\gamma^4}{6\\pi\\varepsilon_0 c^3} \\dot{v}^2 = \\frac{e^4 B^2 \\gamma^2 v^2}{6\\pi\\varepsilon_0 m^2 c^3}$. For ultra-relativistic electrons ($v \\approx c$), $P = \\frac{e^2 c}{6\\pi\\varepsilon_0 R^2} \\gamma^4$.",
            "Multiply $P$ by the orbital period $T = 2\\pi R / c$ to find $\\Delta E = \\frac{4\\pi}{3} \\frac{r_e}{R} \\gamma^4 m c^2$."
        ],
        "answer": "(a) $P = \\frac{e^2 c}{6\\pi\\varepsilon_0 R^2} \\gamma^4 = \\frac{e^4 B^2 \\gamma^2}{6\\pi\\varepsilon_0 m^2 c}$;\n(b) $\\Delta E = \\frac{4\\pi}{3} \\frac{r_e}{R} \\gamma^4 m c^2 = \\frac{4\\pi}{3} \\frac{r_e}{R} \\frac{E^4}{(m c^2)^3}$",
        "solution": "**(a) Total Synchrotron Radiated Power:**\nFor an ultra-relativistic electron moving in a circle of radius $R$ in a magnetic field $B$, the relativistic equation of motion gives the transverse acceleration:\n$$w_\\perp = \\dot{v} = \\frac{v^2}{R} = \\frac{e v B}{\\gamma m}$$\nIn Liénard's formula for radiated power with $\\vec{\\beta} \\perp \\dot{\\vec{v}}$:\n$$P = \\frac{e^2 \\gamma^6}{6\\pi\\varepsilon_0 c^3} \\left[\\dot{v}^2 - \\beta^2 \\dot{v}^2\\right] = \\frac{e^2 \\gamma^6 \\dot{v}^2 (1 - \\beta^2)}{6\\pi\\varepsilon_0 c^3} = \\frac{e^2 \\gamma^4 \\dot{v}^2}{6\\pi\\varepsilon_0 c^3}$$\nSubstituting $\\dot{v} = \\frac{v^2}{R} \\approx \\frac{c^2}{R}$:\n$$P = \\frac{e^2 \\gamma^4 c}{6\\pi\\varepsilon_0 R^2}$$\nAlternatively, in terms of the magnetic field $B$ using $R = \\frac{\\gamma m c}{e B}$:\n$$P = \\frac{e^4 B^2 \\gamma^2}{6\\pi\\varepsilon_0 m^2 c}$$\n\n**(b) Energy Radiated per Revolution:**\nThe period of revolution for an ultra-relativistic electron is:\n$$T = \\frac{2\\pi R}{c}$$\nThe total energy lost during one revolution is:\n$$\\Delta E = P T = \\left(\\frac{e^2 \\gamma^4 c}{6\\pi\\varepsilon_0 R^2}\\right) \\left(\\frac{2\\pi R}{c}\\right) = \\frac{e^2 \\gamma^4}{3\\varepsilon_0 R} = \\frac{4\\pi}{3} \\frac{r_e}{R} \\gamma^4 m c^2$$\nwhere $r_e = \\frac{e^2}{4\\pi\\varepsilon_0 m c^2}$ is the classical electron radius.\nExpressed in terms of the total energy $E = \\gamma m c^2$:\n$$\\Delta E = \\frac{4\\pi}{3} \\frac{r_e}{R} \\frac{E^4}{(m c^2)^3}$$\nBecause $\\Delta E \\propto E^4 / R$, synchrotron radiation sets the ultimate energy limit for circular electron-positron storage rings.",
        "tags": ["synchrotron radiation", "Liénard formula", "cyclotron", "storage ring", "relativistic electron"]
    },
    {
        "id": "4.229",
        "title": "Cherenkov Radiation Threshold Velocity and Emission Angle",
        "difficulty": 2,
        "question": "A relativistic charged particle with velocity $v$ moves through a transparent dielectric medium with refractive index $n = 1.50$. Find:\n(a) the threshold velocity $v_{\\text{th}}$ and threshold kinetic energy $T_{\\text{th}}$ for Cherenkov radiation to be emitted if the particle is an electron;\n(b) the angle $\\theta_C$ between the radiation cone and the trajectory of the particle when its velocity corresponds to $\\beta = v/c = 0.90$.",
        "hints": [
            "Cherenkov radiation occurs when the particle speed exceeds the phase velocity of light in the medium: $v > c / n \\implies \\beta > 1/n$.",
            "The threshold kinetic energy for an electron is $T_{\\text{th}} = m_e c^2 (\\gamma_{\\text{th}} - 1)$, where $\\gamma_{\\text{th}} = 1 / \\sqrt{1 - 1/n^2}$.",
            "The Cherenkov emission angle satisfies Huygens' wavefront condition: $\\cos\\theta_C = \\frac{c/n}{v} = \\frac{1}{n\\beta}$."
        ],
        "answer": "(a) $v_{\\text{th}} = \\frac{c}{n} = 2.0 \\times 10^8\\text{ m/s}$, $T_{\\text{th}} = m_e c^2 \\left(\\frac{n}{\\sqrt{n^2 - 1}} - 1\\right) \\approx 175\\text{ keV}$;\n(b) $\\theta_C = \\arccos\\left(\\frac{1}{n\\beta}\\right) \\approx 42.2^\\circ$",
        "solution": "**(a) Cherenkov Threshold Condition:**\nCherenkov radiation is produced when a charged particle travels through a dielectric faster than the phase velocity of light in that medium:\n$$v > v_{\\text{ph}} = \\frac{c}{n} \\implies \\beta > \\frac{1}{n}$$\nFor $n = 1.50$:\n$$v_{\\text{th}} = \\frac{c}{n} = \\frac{3.0 \\times 10^8\\text{ m/s}}{1.50} = 2.0 \\times 10^8\\text{ m/s}$$\nThe corresponding Lorentz factor at threshold is:\n$$\\gamma_{\\text{th}} = \\frac{1}{\\sqrt{1 - \\beta_{\\text{th}}^2}} = \\frac{1}{\\sqrt{1 - 1/n^2}} = \\frac{n}{\\sqrt{n^2 - 1}} = \\frac{1.50}{\\sqrt{2.25 - 1}} = \\frac{1.50}{1.118} \\approx 1.3416$$\nThe threshold kinetic energy for an electron ($m_e c^2 = 511\\text{ keV}$) is:\n$$T_{\\text{th}} = (\\gamma_{\\text{th}} - 1) m_e c^2 = (1.3416 - 1) \\times 511\\text{ keV} \\approx 174.6\\text{ keV} \\approx 175\\text{ keV}$$\n\n**(b) Cherenkov Cone Half-Angle:**\nFrom the constructive interference of spherical wavelets emitted along the path (Huygens' construction):\n$$\\cos\\theta_C = \\frac{v_{\\text{ph}} \\Delta t}{v \\Delta t} = \\frac{c / n}{v} = \\frac{1}{n\\beta}$$\nFor $\\beta = 0.90$ and $n = 1.50$:\n$$\\cos\\theta_C = \\frac{1}{(1.50)(0.90)} = \\frac{1}{1.35} \\approx 0.7407$$\n$$\\theta_C = \\arccos(0.7407) \\approx 42.2^\\circ$$",
        "tags": ["Cherenkov radiation", "phase velocity", "refractive index", "relativistic particle"]
    },
    {
        "id": "4.230",
        "title": "Radiation Pressure and Normal Force on a Mirror at Oblique Incidence",
        "difficulty": 2,
        "question": "A parallel beam of monochromatic light of intensity $I$ falls on a planar perfectly reflecting mirror of area $A$ at an angle of incidence $\\theta$. Find:\n(a) the radiation pressure $p$ exerted by the beam on the mirror surface;\n(b) the total normal force $F_n$ and tangential force $F_t$ exerted on the mirror.",
        "hints": [
            "The energy incident on the surface per unit time is $P_{\\text{inc}} = I A \\cos\\theta$.",
            "Each incident photon carries momentum $p_0 = E_0 / c$. Upon specular reflection, the tangential momentum is conserved, and the normal momentum changes by $\\Delta p_n = 2 p_0 \\cos\\theta$.",
            "Pressure is normal force per unit area: $p = \\frac{F_n}{A} = \\frac{2 I \\cos^2\\theta}{c}$."
        ],
        "answer": "(a) $p = \\frac{2I \\cos^2\\theta}{c}$;\n(b) $F_n = \\frac{2 I A \\cos^2\\theta}{c}$, $F_t = 0$",
        "solution": "**1. Momentum Flux of the Incident Beam:**\nConsider the light beam of intensity $I$ (energy per unit area per unit time perpendicular to the beam). The volume density of electromagnetic momentum in the incident beam is:\n$$g_{\\text{inc}} = \\frac{I}{c^2}$$\nIn time $\\Delta t$, the beam intercepts an area $A$ of the mirror. The volume of the beam impinging on the mirror is $\\Delta V = A c \\cos\\theta \\, \\Delta t$.\nThe total incident momentum in time $\\Delta t$ is:\n$$\\Delta \\vec{p}_{\\text{inc}} = g_{\\text{inc}} \\Delta V = \\frac{I A \\cos\\theta \\, \\Delta t}{c} \\hat{k}_{\\text{inc}}$$\n\n**2. Change of Momentum on Reflection:**\nFor a perfectly reflecting mirror, specular reflection occurs:\n- The tangential component of momentum parallel to the surface is conserved: $\\Delta p_t = 0$.\n- The normal component changes from $-p_{\\text{inc}} \\cos\\theta$ to $+p_{\\text{inc}} \\cos\\theta$, so the normal momentum delivered to the mirror is:\n$$\\Delta p_n = 2 p_{\\text{inc}} \\cos\\theta = 2 \\left(\\frac{I A \\cos\\theta \\, \\Delta t}{c}\\right) \\cos\\theta = \\frac{2 I A \\cos^2\\theta \\, \\Delta t}{c}$$\n\n**3. Forces and Pressure:**\nThe normal force exerted on the mirror is:\n$$F_n = \\frac{\\Delta p_n}{\\Delta t} = \\frac{2 I A \\cos^2\\theta}{c}$$\nThe tangential force is:\n$$F_t = 0$$\nThe radiation pressure is defined as the normal force per unit surface area:\n$$p = \\frac{F_n}{A} = \\frac{2 I \\cos^2\\theta}{c}$$",
        "tags": ["radiation pressure", "momentum of light", "reflection", "Poynting vector"]
    },
    {
        "id": "4.231",
        "title": "Poynting-Robertson Effect and Orbital Decay of Interplanetary Dust",
        "difficulty": 3,
        "question": "A small spherical absorbing dust grain of radius $R$ and density $\\rho$ moves around the Sun in a circular orbit of radius $r$. Due to the aberration of sunlight absorbed by the grain and re-emitted isotropically in its rest frame (the Poynting-Robertson effect), the grain experiences an orbital retarding drag force $F_{\\text{drag}} = -\\frac{P_{\\text{abs}} v}{c^2}$, where $v$ is the orbital velocity and $P_{\\text{abs}} = \\frac{P_{\\odot} \\pi R^2}{4\\pi r^2}$ is the absorbed solar power. Find the time $t_{\\text{decay}}$ required for the dust particle to spiral from an initial orbital radius $r_0$ into the Sun.",
        "hints": [
            "The orbital angular momentum is $L = m v r = m \\sqrt{\\gamma M_{\\odot} r}$.",
            "The torque exerted by the aberration drag force is $\\tau = -r F_{\\text{drag}} = -\\frac{P_{\\odot} \\pi R^2}{4\\pi r^2 c^2} v r$.",
            "Equate $\\frac{dL}{dt} = \\frac{m \\sqrt{\\gamma M_{\\odot}}}{2\\sqrt{r}} \\frac{dr}{dt} = -\\frac{P_{\\odot} R^2 \\sqrt{\\gamma M_{\\odot}}}{4 c^2 r^{3/2}}$ and integrate from $r_0$ to $0$."
        ],
        "answer": "$t_{\\text{decay}} = \\frac{4\\pi \\rho R c^2 r_0^2}{3 P_{\\odot}}$",
        "solution": "**1. Aberration Drag Force (Poynting-Robertson Effect):**\nIn the rest frame of the dust grain moving with circular orbital velocity $v = \\sqrt{\\frac{\\gamma M_{\\odot}}{r}} \\ll c$, sunlight appears to arrive from a forward angle $\\alpha \\approx v/c$ relative to the radial line due to velocity aberration.\nThe grain absorbs radiation at the rate:\n$$P_{\\text{abs}} = I(r) \\pi R^2 = \\frac{P_{\\odot} \\pi R^2}{4\\pi r^2} = \\frac{P_{\\odot} R^2}{4 r^2}$$\nBecause the incoming light has a retrograde tangential momentum component $-\\frac{P_{\\text{abs}}}{c} \\sin\\alpha \\approx -\\frac{P_{\\text{abs}} v}{c^2}$, and the subsequent thermal re-emission is isotropic in the grain's frame, the grain experiences a net retarding tangential drag force:\n$$F_{\\text{drag}} = -\\frac{P_{\\text{abs}} v}{c^2} = -\\frac{P_{\\odot} R^2 v}{4 c^2 r^2}$$\n\n**2. Rate of Change of Orbital Radius:**\nThe orbital mechanical energy of the grain of mass $m = \\frac{4}{3}\\pi R^3 \\rho$ in a circular orbit is:\n$$E_{\\text{orb}} = -\\frac{\\gamma M_{\\odot} m}{2r}$$\nThe rate of loss of mechanical energy due to the retarding drag force is:\n$$\\frac{dE_{\\text{orb}}}{dt} = F_{\\text{drag}} v = -\\frac{P_{\\odot} R^2 v^2}{4 c^2 r^2} = -\\frac{P_{\\odot} R^2 \\gamma M_{\\odot}}{4 c^2 r^3}$$\nDifferentiating $E_{\\text{orb}}$ with respect to $t$:\n$$\\frac{dE_{\\text{orb}}}{dt} = \\frac{\\gamma M_{\\odot} m}{2 r^2} \\frac{dr}{dt}$$\nEquating the two expressions:\n$$\\frac{\\gamma M_{\\odot} m}{2 r^2} \\frac{dr}{dt} = -\\frac{P_{\\odot} R^2 \\gamma M_{\\odot}}{4 c^2 r^3} \\implies r \\frac{dr}{dt} = -\\frac{P_{\\odot} R^2}{2 m c^2}$$\nSubstituting $m = \\frac{4}{3}\\pi R^3 \\rho$:\n$$r \\frac{dr}{dt} = -\\frac{P_{\\odot} R^2}{2 \\left(\\frac{4}{3}\\pi R^3 \\rho\\right) c^2} = -\\frac{3 P_{\\odot}}{8\\pi \\rho R c^2}$$\n\n**3. Spiral-in Time:**\nIntegrating from $r = r_0$ at $t = 0$ to $r = 0$ at $t = t_{\\text{decay}}$:\n$$\\int_{r_0}^0 r \\, dr = -\\frac{3 P_{\\odot}}{8\\pi \\rho R c^2} \\int_0^{t_{\\text{decay}}} dt$$\n$$-\\frac{r_0^2}{2} = -\\frac{3 P_{\\odot}}{8\\pi \\rho R c^2} t_{\\text{decay}}$$\nSolving for $t_{\\text{decay}}$:\n$$t_{\\text{decay}} = \\frac{4\\pi \\rho R c^2 r_0^2}{3 P_{\\odot}}$$",
        "tags": ["Poynting-Robertson effect", "radiation pressure", "orbital mechanics", "interplanetary dust"]
    },
    {
        "id": "4.232",
        "title": "Cut-Off Frequency, Phase and Group Velocity of TE10 Waveguide Mode",
        "difficulty": 2,
        "question": "An electromagnetic wave propagates in a hollow rectangular metallic waveguide with cross-sectional dimensions $a \\times b$ ($a > b$) along the $z$ axis in the fundamental mode $\\text{TE}_{10}$. Find:\n(a) the cut-off wavelength $\\lambda_c$ and cut-off frequency $\\nu_c$;\n(b) the phase velocity $v_{\\text{ph}}$ and group velocity $v_g$ in terms of the vacuum wavelength $\\lambda$ and show that $v_{\\text{ph}} v_g = c^2$.",
        "hints": [
            "For $\\text{TE}_{m0}$ modes, the transverse electric field must vanish at $x = 0$ and $x = a$, giving $k_x = \\frac{m\\pi}{a}$. For $\\text{TE}_{10}$, $k_x = \\frac{\\pi}{a}$.",
            "The dispersion relation in the waveguide is $\\frac{\\omega^2}{c^2} = k_z^2 + k_x^2 = k_z^2 + \\left(\\frac{\\pi}{a}\\right)^2$. Cut-off occurs when $k_z = 0$.",
            "Calculate $v_{\\text{ph}} = \\frac{\\omega}{k_z}$ and $v_g = \\frac{d\\omega}{dk_z}$."
        ],
        "answer": "(a) $\\lambda_c = 2a$, $\\nu_c = \\frac{c}{2a}$;\n(b) $v_{\\text{ph}} = \\frac{c}{\\sqrt{1 - (\\lambda/2a)^2}} > c$, $v_g = c \\sqrt{1 - (\\lambda/2a)^2} < c$, with $v_{\\text{ph}} v_g = c^2$",
        "solution": "**(a) Boundary Conditions and Cut-Off Frequency:**\nIn a rectangular waveguide bounded by perfectly conducting walls at $x = 0, a$ and $y = 0, b$, the electric field of the $\\text{TE}_{10}$ mode has only a $y$-component:\n$$E_y(x, z, t) = E_0 \\sin(k_x x) e^{i(k_z z - \\omega t)}$$\nThe boundary condition $E_y(0) = E_y(a) = 0$ requires:\n$$k_x a = \\pi \\implies k_x = \\frac{\\pi}{a}$$\nFrom the Helmholtz wave equation in vacuum, the wavevector components satisfy:\n$$\\frac{\\omega^2}{c^2} = k_x^2 + k_z^2 = \\left(\\frac{\\pi}{a}\\right)^2 + k_z^2$$\nWave propagation along the $z$-axis ($k_z > 0$) requires $\\frac{\\omega}{c} > k_x = \\frac{\\pi}{a}$. The cut-off occurs when $k_z = 0$:\n$$\\omega_c = c k_x = \\frac{\\pi c}{a} \\implies \\nu_c = \\frac{c}{2a}$$\nThe cut-off wavelength in vacuum is:\n$$\\lambda_c = \\frac{c}{\\nu_c} = 2a$$\n\n**(b) Phase Velocity and Group Velocity:**\nThe propagation constant along the waveguide is:\n$$k_z = \\sqrt{\\frac{\\omega^2}{c^2} - \\left(\\frac{\\pi}{a}\\right)^2} = \\frac{\\omega}{c} \\sqrt{1 - \\left(\\frac{\\omega_c}{\\omega}\\right)^2} = \\frac{2\\pi}{\\lambda} \\sqrt{1 - \\left(\\frac{\\lambda}{2a}\\right)^2}$$\n1. The phase velocity is the speed at which wave fronts advance:\n$$v_{\\text{ph}} = \\frac{\\omega}{k_z} = \\frac{c}{\\sqrt{1 - (\\lambda/2a)^2}} > c$$\n2. The group velocity is the speed of energy transmission:\n$$v_g = \\frac{d\\omega}{dk_z}$$\nDifferentiating the dispersion relation $\\omega^2 = c^2 k_z^2 + \\omega_c^2$ with respect to $k_z$:\n$$2\\omega \\frac{d\\omega}{dk_z} = 2 c^2 k_z \\implies v_g = \\frac{d\\omega}{dk_z} = c^2 \\frac{k_z}{\\omega} = \\frac{c^2}{v_{\\text{ph}}} = c \\sqrt{1 - \\left(\\frac{\\lambda}{2a}\\right)^2} < c$$\n3. Product of velocities:\n$$v_{\\text{ph}} v_g = c^2$$",
        "tags": ["waveguides", "TE10 mode", "cut-off frequency", "phase velocity", "group velocity"]
    },
    {
        "id": "4.233",
        "title": "Radiation Pressure and Optical Levitation of a Transparent Micro-Sphere",
        "difficulty": 3,
        "question": "A vertical, upward-directed laser beam with wavelength $\\lambda$ and total power $P_0$ is focused into a Gaussian waist of radius $w_0$. A transparent non-absorbing dielectric micro-sphere of radius $R \\ll w_0$ and relative refractive index $n$ is placed on the beam axis. The scattering cross-section is $\\sigma_{\\text{scat}}$, and the mean forward scattering parameter is $\\langle \\cos\\theta \\rangle$. Find the upward radiation pressure force $F_{\\text{rad}}$ acting on the sphere in terms of the beam axial intensity $I_0 = \\frac{2P_0}{\\pi w_0^2}$.",
        "hints": [
            "Radiation force arises from the transfer of photon momentum: $F_{\\text{rad}} = \\frac{P_{\\text{scat}}}{c} (1 - \\langle \\cos\\theta \\rangle)$.",
            "The scattered power from an incident beam of intensity $I_0$ is $P_{\\text{scat}} = \\sigma_{\\text{scat}} I_0$.",
            "Combine to write the radiation pressure cross-section: $\\sigma_{\\text{pr}} = \\sigma_{\\text{scat}} (1 - \\langle \\cos\\theta \\rangle)$ and $F_{\\text{rad}} = \\frac{I_0}{c} \\sigma_{\\text{pr}}$."
        ],
        "answer": "$F_{\\text{rad}} = \\frac{I_0}{c} \\sigma_{\\text{scat}} (1 - \\langle \\cos\\theta \\rangle) = \\frac{2 P_0}{\\pi w_0^2 c} \\sigma_{\\text{scat}} (1 - \\langle \\cos\\theta \\rangle)$",
        "solution": "**1. Momentum Balance for Scattered Radiation:**\nConsider an incident beam of light with intensity $I_0$ propagating in the $+z$ direction. The incident momentum flux per unit time intercepted by the particle is:\n$$\\dot{p}_{\\text{in}} = \\frac{P_{\\text{scat}}}{c} = \\frac{\\sigma_{\\text{scat}} I_0}{c}$$\nwhere $\\sigma_{\\text{scat}}$ is the scattering cross-section.\n\n**2. Forward Momentum Carried by Scattered Light:**\nThe light scattered into polar angle $\\theta$ carries forward momentum at the rate $\\frac{dP_{\\text{scat}}}{c} \\cos\\theta$.\nAveraging over all scattering angles:\n$$\\dot{p}_{\\text{out}, z} = \\frac{P_{\\text{scat}}}{c} \\langle \\cos\\theta \\rangle = \\frac{\\sigma_{\\text{scat}} I_0}{c} \\langle \\cos\\theta \\rangle$$\nwhere $\\langle \\cos\\theta \\rangle$ is the asymmetry parameter (the mean cosine of the scattering angle).\n\n**3. Net Radiation Pressure Force:**\nBy conservation of linear momentum, the net longitudinal force transferred to the dielectric sphere is:\n$$F_{\\text{rad}} = \\dot{p}_{\\text{in}} - \\dot{p}_{\\text{out}, z} = \\frac{I_0}{c} \\sigma_{\\text{scat}} (1 - \\langle \\cos\\theta \\rangle)$$\nThe effective radiation pressure cross-section is defined as:\n$$\\sigma_{\\text{pr}} = \\sigma_{\\text{scat}} (1 - \\langle \\cos\\theta \\rangle)$$\nSubstituting the peak Gaussian beam intensity $I_0 = \\frac{2 P_0}{\\pi w_0^2}$:\n$$F_{\\text{rad}} = \\frac{2 P_0}{\\pi w_0^2 c} \\sigma_{\\text{scat}} (1 - \\langle \\cos\\theta \\rangle)$$\nWhen $F_{\\text{rad}}$ balances the sphere's gravitational weight $m g$, optical levitation (Ashkin's optical tweezers) is achieved.",
        "tags": ["optical levitation", "optical tweezers", "radiation pressure", "Mie scattering"]
    },
    {
        "id": "4.234",
        "title": "Coherent Far-Field Interference of Two Parallel Dipole Antennas",
        "difficulty": 2,
        "question": "Two identical elementary dipoles oriented along the $z$ axis are located on the $x$ axis at points $x = \\pm d/2$. Both dipoles oscillate with identical frequency $\\omega$ and amplitude $p_0$, but with a constant phase shift $\\delta$. Find:\n(a) the radiation intensity $I(\\theta, \\phi)$ in the far zone as a function of the polar angle $\\theta$ and azimuthal angle $\\phi$;\n(b) the condition for constructive interference in the broadside direction (along the $y$ axis, $\\phi = \\pi/2$).",
        "hints": [
            "The field of a single dipole in the far zone is proportional to $\\sin\\theta \\, e^{ikr} / r$.",
            "The path difference to an observer at angle $(\\theta, \\phi)$ is $\\Delta r = d \\sin\\theta \\cos\\phi$, causing phase difference $\\Delta\\Phi = k d \\sin\\theta \\cos\\phi + \\delta$.",
            "The interference intensity is modulated by the array factor $4 \\cos^2(\\Delta\\Phi / 2)$."
        ],
        "answer": "(a) $I(\\theta, \\phi) = 4 I_1(\\theta) \\cos^2\\left(\\frac{\\pi d}{\\lambda} \\sin\\theta \\cos\\phi + \\frac{\\delta}{2}\\right)$, where $I_1(\\theta) \\propto \\sin^2\\theta$;\n(b) Maximum in the broadside direction $(\\phi = \\pi/2)$ occurs when $\\delta = 0$ (in-phase feed)",
        "solution": "**(a) Far-Field Radiation Pattern:**\nEach dipole is directed along the $z$-axis, so the single-dipole far-field amplitude has angular dependence $\\sin\\theta$:\n$$E_1 \\propto \\frac{\\sin\\theta}{r} e^{i(kr - \\omega t)}$$\nFor an observation point in direction $(\\theta, \\phi)$, the path difference between the waves emitted by the two dipoles at $(\\pm d/2, 0, 0)$ is:\n$$\\Delta r = x_1 \\sin\\theta \\cos\\phi - x_2 \\sin\\theta \\cos\\phi = d \\sin\\theta \\cos\\phi$$\nThe total phase difference between the two waves at the receiver is:\n$$\\Delta\\Phi = k \\Delta r + \\delta = \\frac{2\\pi}{\\lambda} d \\sin\\theta \\cos\\phi + \\delta$$\nBy the superposition principle, the total electric field is:\n$$E_{\\text{tot}} = E_1 \\left(e^{-i\\Delta\\Phi/2} + e^{i\\Delta\\Phi/2}\\right) = 2 E_1 \\cos\\left(\\frac{\\Delta\\Phi}{2}\\right)$$\nThe time-averaged intensity is therefore:\n$$I(\\theta, \\phi) = |E_{\\text{tot}}|^2 = 4 I_1(\\theta) \\cos^2\\left(\\frac{\\pi d}{\\lambda} \\sin\\theta \\cos\\phi + \\frac{\\delta}{2}\\right)$$\nwhere $I_1(\\theta) = I_0 \\sin^2\\theta$ is the radiation pattern of a single isolated dipole.\n\n**(b) Broadside Direction:**\nFor the broadside direction along the $y$-axis, $\\phi = \\pi/2$, so $\\cos\\phi = 0$ and the path difference vanishes. The phase difference is purely the intrinsic feed phase difference:\n$$\\Delta\\Phi = \\delta$$\nConstructive interference requires $\\cos^2(\\delta / 2) = 1$, which gives:\n$$\\delta = 2m\\pi \\quad (m \\in \\mathbb{Z})$$\nFor the fundamental mode, the dipoles must be driven in phase ($\\delta = 0$).",
        "tags": ["antenna array", "dipole interference", "radiation pattern", "broadside array"]
    },
    {
        "id": "4.235",
        "title": "Magnetic Dipole Radiation of a Small Alternating Current Loop",
        "difficulty": 2,
        "question": "A small circular loop of radius $a$ lies in the $(x, y)$ plane and carries an alternating current $I(t) = I_0 \\cos\\omega t$. Assuming the wavelength $\\lambda = 2\\pi c / \\omega \\gg a$, find:\n(a) the total power $P_m$ radiated by the loop (magnetic dipole radiation);\n(b) the ratio of this magnetic dipole power to the electric dipole power $P_e$ radiated by an electric dipole of length $l = 2a$ carrying current amplitude $I_0$.",
        "hints": [
            "The magnetic dipole moment of the loop has magnitude $m(t) = I(t) \\pi a^2 = I_0 \\pi a^2 \\cos\\omega t$.",
            "The power radiated by a magnetic dipole is $P_m = \\frac{\\mu_0 \\ddot{m}^2}{6\\pi c^3}$ or in SI units $P_m = \\frac{\\mu_0 m_0^2 \\omega^4}{12\\pi c^3}$.",
            "An electric dipole of length $l = 2a$ has moment $p(t) = \\frac{I_0 l}{\\omega} \\sin\\omega t$. Compare $P_m$ and $P_e$."
        ],
        "answer": "(a) $P_m = \\frac{\\mu_0 \\pi a^4 I_0^2 \\omega^4}{12 c^3} = \\frac{\\pi}{12} \\sqrt{\\frac{\\mu_0}{\\varepsilon_0}} I_0^2 (k a)^4$;\n(b) $\\frac{P_m}{P_e} = \\frac{1}{4} (k a)^2 = \\frac{\\pi^2 a^2}{\\lambda^2} \\ll 1$",
        "solution": "**(a) Total Radiated Power of Magnetic Dipole:**\nThe magnetic dipole moment vector of the circular loop is directed along the $z$-axis:\n$$m(t) = I(t) (\\pi a^2) = (\\pi a^2 I_0) \\cos\\omega t$$\nThe second time derivative is:\n$$\\ddot{m}(t) = -\\omega^2 (\\pi a^2 I_0) \\cos\\omega t$$\nThe formula for the time-averaged power radiated by a magnetic dipole in vacuum is:\n$$P_m = \\frac{\\mu_0 \\langle \\ddot{m}^2 \\rangle}{6\\pi c^3} = \\frac{\\mu_0 (\\pi a^2 I_0)^2 \\omega^4}{12\\pi c^3} = \\frac{\\mu_0 \\pi a^4 I_0^2 \\omega^4}{12 c^3}$$\nExpressing this in terms of the wave number $k = \\omega / c$ and wave impedance $Z_0 = \\sqrt{\\mu_0 / \\varepsilon_0} = \\mu_0 c$:\n$$P_m = \\frac{Z_0}{12} \\pi I_0^2 (k a)^4$$\n\n**(b) Comparison with Electric Dipole Radiation:**\nFor an electric dipole of length $l = 2a$ carrying the same current $I(t) = I_0 \\cos\\omega t$, the charge at the ends is $q(t) = \\int I(t)\\,dt = \\frac{I_0}{\\omega} \\sin\\omega t$, giving an electric dipole moment:\n$$p(t) = q(t) l = \\frac{I_0 (2a)}{\\omega} \\sin\\omega t$$\nThe second derivative is $\\ddot{p}(t) = -2a \\omega I_0 \\sin\\omega t$, and the time-averaged electric dipole power is:\n$$P_e = \\frac{1}{4\\pi\\varepsilon_0} \\frac{2 \\langle \\ddot{p}^2 \\rangle}{3 c^3} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{2 (4 a^2 \\omega^2 I_0^2 / 2)}{3 c^3} = \\frac{a^2 I_0^2 \\omega^2}{3\\pi \\varepsilon_0 c^3} = \\frac{Z_0}{3\\pi} I_0^2 (k a)^2$$\nTaking the ratio:\n$$\\frac{P_m}{P_e} = \\frac{\\frac{\\pi Z_0}{12} I_0^2 (k a)^4}{\\frac{Z_0}{3\\pi} I_0^2 (k a)^2} = \\frac{\\pi^2}{4} (k a)^2 = \\pi^2 \\left(\\frac{2\\pi a}{\\lambda}\\right)^2 = \\frac{1}{4} (k a)^2$$\nSince $k a = 2\\pi a / \\lambda \\ll 1$, magnetic dipole radiation is weaker than electric dipole radiation by a factor of order $(a/\\lambda)^2$.",
        "tags": ["magnetic dipole", "current loop", "radiation power", "multipolar expansion"]
    },
    {
        "id": "4.236",
        "title": "Quadrupole Radiation Power of an Oscillating Linear Charge Quadrupole",
        "difficulty": 3,
        "question": "A linear electric quadrupole consists of a central charge $-2q(t)$ flanked symmetrically by two charges $+q(t)$ at coordinates $z = \\pm l$. The charge oscillates as $q(t) = q_0 \\cos\\omega t$. Assuming $l \\ll \\lambda = 2\\pi c / \\omega$, find the total time-averaged power $P_{\\text{quad}}$ radiated by this quadrupole in vacuum.",
        "hints": [
            "The electric dipole moment of this symmetric configuration is identically zero: $p(t) = q l - 2q(0) + q(-l) = 0$.",
            "The quadrupole moment component is $D_{zz} = \\sum q_i (3 z_i^2 - r_i^2) = 2 q l^2 (3 - 1) = 4 q l^2 = 4 q_0 l^2 \\cos\\omega t$.",
            "The power radiated by a dynamic quadrupole is $P_{\\text{quad}} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{1}{180 c^5} \\langle \\dddot{D}_{zz}^2 \\rangle$."
        ],
        "answer": "$P_{\\text{quad}} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{2 q_0^2 l^4 \\omega^6}{45 c^5}$",
        "solution": "**1. Multipole Moments of the System:**\nThe system consists of:\n- Charge $+q(t)$ at $z = +l$\n- Charge $-2q(t)$ at $z = 0$\n- Charge $+q(t)$ at $z = -l$\n1. The total charge is $Q = q - 2q + q = 0$ (no monopole radiation).\n2. The electric dipole moment is $\\vec{p} = \\sum q_i z_i \\hat{k} = [q(l) + (-2q)(0) + q(-l)]\\hat{k} = 0$ (no dipole radiation).\n\n**2. Quadrupole Tensor Component:**\nThe non-zero component of the electric quadrupole tensor $D_{ij} = \\sum q_a (3 x_{a,i} x_{a,j} - r_a^2 \\delta_{ij})$ along the symmetry axis $z$ is:\n$$D_{zz}(t) = q(3 l^2 - l^2) + (-2q)(0) + q(3 l^2 - l^2) = 4 q(t) l^2 = 4 q_0 l^2 \\cos\\omega t$$\nBy symmetry, $D_{xx} = D_{yy} = -\\frac{1}{2} D_{zz} = -2 q_0 l^2 \\cos\\omega t$.\n\n**3. Third Time Derivative:**\nDifferentiating $D_{zz}(t)$ three times with respect to $t$:\n$$\\dddot{D}_{zz}(t) = 4 q_0 l^2 \\omega^3 \\sin\\omega t$$\n$$\\sum_{i,j} \\dddot{D}_{ij}^2 = \\dddot{D}_{zz}^2 + \\dddot{D}_{xx}^2 + \\dddot{D}_{yy}^2 = \\dddot{D}_{zz}^2 + \\frac{1}{4}\\dddot{D}_{zz}^2 + \\frac{1}{4}\\dddot{D}_{zz}^2 = \\frac{3}{2} \\dddot{D}_{zz}^2$$\nTaking the time average:\n$$\\langle \\sum_{i,j} \\dddot{D}_{ij}^2 \\rangle = \\frac{3}{2} (16 q_0^2 l^4 \\omega^6) \\langle \\sin^2\\omega t \\rangle = 12 q_0^2 l^4 \\omega^6$$\n\n**4. Total Radiated Power:**\nThe general formula for quadrupole radiation power is:\n$$P_{\\text{quad}} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{1}{180 c^5} \\sum_{i,j} \\langle \\dddot{D}_{ij}^2 \\rangle$$\nSubstituting the evaluated sum:\n$$P_{\\text{quad}} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{12 q_0^2 l^4 \\omega^6}{180 c^5} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{2 q_0^2 l^4 \\omega^6}{45 c^5}$$",
        "tags": ["quadrupole radiation", "multipole expansion", "Larmor formula", "electrodynamics"]
    },
    {
        "id": "4.237",
        "title": "Transition Radiation Emitted by a Charge Crossing a Conducting Boundary",
        "difficulty": 3,
        "question": "A particle with charge $q$ moves with constant non-relativistic velocity $v \\ll c$ in vacuum along the normal to the flat surface of an ideal conductor and enters it. Find the total energy $W$ radiated during the impact (transition radiation) in the forward half-space.",
        "hints": [
            "By the method of images, while the charge is at distance $z(t) = -vt$ in front of the conductor, an image charge $-q$ exists at $+z(t) = vt$.",
            "The system of real and image charge forms a variable electric dipole moment $p(t) = 2 q |z(t)| = 2 q (-vt)$ for $t < 0$, which vanishes abruptly at $t = 0$.",
            "The rapid deceleration of the dipole moment upon impact emits dipole radiation with total energy $W = \\frac{q^2 v}{12\\pi^2 \\varepsilon_0 c^3}$ or use the Fourier transform $\\Delta \\dot{p} = 2 q v$."
        ],
        "answer": "$W = \\frac{2 q^2 v}{3\\pi \\varepsilon_0 c^3} \\frac{1}{4\\pi} = \\frac{4}{3(4\\pi\\varepsilon_0)} \\frac{q^2 v}{c^3}$ (spectral density $dW/d\\omega = \\frac{q^2 v^2}{3\\pi^2 \\varepsilon_0 c^3}$)",
        "solution": "**1. The Image Charge Model:**\nWhen a charge $q$ approaches a conducting plane along the normal $z$ at velocity $v$, the boundary conditions on the metallic surface are equivalent to the field of the charge $q$ at $z(t) = v t$ (for $t < 0$) combined with an image charge $-q$ at $-z(t) = -v t$.\nThe dipole moment of this charge-image pair is directed along the normal:\n$$p(t) = 2 q z(t) = 2 q v t \\quad (t < 0)$$\nAt $t = 0$, the charge enters the conductor, and the dipole moment drops to zero:\n$$p(t) = 0 \\quad (t > 0)$$\n\n**2. Fourier Spectrum of the Dipole Acceleration:**\nThe effective current is $\\dot{p}(t) = 2qv$ for $t < 0$ and $0$ for $t > 0$. The derivative is a delta function upon impact:\n$$\\ddot{p}(t) = -2 q v \\delta(t)$$\nThe Fourier transform is:\n$$\\ddot{p}_\\omega = \\int_{-\\infty}^\\infty \\ddot{p}(t) e^{i\\omega t} \\, dt = -2 q v$$\n\n**3. Radiated Energy Spectrum:**\nThe spectral distribution of radiated energy into the vacuum half-space by dipole radiation is:\n$$\\frac{dW}{d\\omega} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{|\\ddot{p}_\\omega|^2}{3\\pi c^3} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{4 q^2 v^2}{3\\pi c^3} = \\frac{q^2 v^2}{3\\pi^2 \\varepsilon_0 c^3}$$\nTransition radiation has a flat (white) frequency spectrum up to a cut-off frequency determined by the plasma frequency of the metal.",
        "tags": ["transition radiation", "image charge", "dipole radiation", "boundary electrodynamics"]
    },
    {
        "id": "4.238",
        "title": "Relativistic Doppler Beaming and Headlight Effect of Radiation",
        "difficulty": 2,
        "question": "A relativistic source moves with velocity $v$ (Lorentz factor $\\gamma = 1 / \\sqrt{1 - v^2/c^2} \\gg 1$) relative to the laboratory frame. In its own proper rest frame $K'$, the source emits radiation isotropically. Find:\n(a) the angular distribution of the emitted photons in the laboratory frame, and the cone half-angle $\\theta_{1/2}$ into which half of all radiated power is concentrated;\n(b) the Doppler-shifted frequency $\\omega(\\theta)$ received by a stationary observer at angle $\\theta$ relative to the velocity vector.",
        "hints": [
            "Use the relativistic aberration formula $\\cos\\theta = \\frac{\\cos\\theta' + \\beta}{1 + \\beta \\cos\\theta'}$.",
            "In the proper frame, half of the photons are emitted into the forward hemisphere $\\theta' \\le \\pi/2$ (so $\\cos\\theta' \\ge 0$).",
            "Set $\\cos\\theta' = 0$ in the aberration formula to find $\\cos\\theta_{1/2} = \\beta$, which for $\\gamma \\gg 1$ yields $\\theta_{1/2} \\approx 1/\\gamma$."
        ],
        "answer": "(a) $\\cos\\theta_{1/2} = \\frac{v}{c} = \\beta$; for $\\gamma \\gg 1$, $\\theta_{1/2} \\approx \\frac{1}{\\gamma}$;\n(b) $\\omega(\\theta) = \\frac{\\omega_0}{\\gamma (1 - \\beta \\cos\\theta)}$",
        "solution": "**(a) Relativistic Aberration and Headlight Effect:**\nLet the source move along the $+x$ axis with velocity $v = \\beta c$. The direction of a ray of light in the rest frame $K'$ is $\\theta'$, and in the laboratory frame $K$ it is $\\theta$.\nFrom the Lorentz transformation of the wave four-vector $(\\omega/c, \\vec{k})$:\n$$\\cos\\theta = \\frac{\\cos\\theta' + \\beta}{1 + \\beta \\cos\\theta'}$$\nSince emission in the rest frame $K'$ is isotropic, exactly half of the total radiation is emitted into the forward hemisphere: $0 \\le \\theta' \\le \\pi/2$.\nThe boundary of this forward hemisphere is $\\theta' = \\pi/2$, for which $\\cos\\theta' = 0$. Substituting into the aberration formula:\n$$\\cos\\theta_{1/2} = \\frac{0 + \\beta}{1 + 0} = \\beta = \\frac{v}{c}$$\nFor ultra-relativistic motion where $\\gamma = 1/\\sqrt{1 - \\beta^2} \\gg 1$:\n$$\\sin^2\\theta_{1/2} = 1 - \\cos^2\\theta_{1/2} = 1 - \\beta^2 = \\frac{1}{\\gamma^2}$$\nSince $\\theta_{1/2} \\ll 1$, $\\sin\\theta_{1/2} \\approx \\theta_{1/2}$, giving:\n$$\\theta_{1/2} \\approx \\frac{1}{\\gamma}$$\nThus, half of the total radiated energy is beamed into an extremely narrow forward cone of half-angle $1/\\gamma$ (the relativistic 'headlight' effect).\n\n**(b) Relativistic Doppler Shift:**\nThe four-frequency transformation gives the frequency measured in the laboratory frame at angle $\\theta$ relative to the velocity:\n$$\\omega(\\theta) = \\frac{\\omega_0}{\\gamma (1 - \\beta \\cos\\theta)}$$\n- In the forward direction $(\\theta = 0)$:\n$$\\omega(0) = \\frac{\\omega_0}{\\gamma(1 - \\beta)} = \\omega_0 \\sqrt{\\frac{1 + \\beta}{1 - \\beta}} \\approx 2\\gamma \\omega_0$$\n- In the transverse direction $(\\theta = \\pi/2)$:\n$$\\omega(\\pi/2) = \\frac{\\omega_0}{\\gamma}$$ (pure transverse Doppler red-shift).",
        "tags": ["relativistic Doppler effect", "aberration of light", "headlight effect", "beaming", "Lorentz transformation"]
    }
]
