"""
part5_ch5_4b.py
Curated problems 5.179 to 5.199 (21 problems) of Irodov Chapter 5.4:
Polarization of Light (Part B: Wave Plates, Birefringence Interference, Optical Activity, Faraday and Kerr Effects).
"""

CH5_4B_CURATED = [
    {
        "id": "5.179",
        "title": "Thickness Limits for Half-Wave and Quarter-Wave Quartz Plates",
        "difficulty": 2,
        "question": "A quartz plate cut parallel to its optical axis is to be manufactured with thickness not exceeding $d_{\\text{max}} = 0.50\\text{ mm}$. Find the maximum possible thickness of the plate allowing plane-polarized light with wavelength $\\lambda = 589\\text{ nm}$ to:\n(a) experience only rotation of its polarization plane (half-wave plate);\n(b) acquire circular polarization after passing through the plate (quarter-wave plate).\nThe difference of refractive indices is $\\Delta n = n_e - n_o = 0.0090$.",
        "hints": [
            "(a) To act as a half-wave plate, the optical path difference must be an odd multiple of half-wavelengths: $\\Delta n \\cdot d = (2k + 1) \\frac{\\lambda}{2}$.",
            "(b) To act as a quarter-wave plate, the optical path difference must be an odd multiple of quarter-wavelengths: $\\Delta n \\cdot d = (2k + 1) \\frac{\\lambda}{4}$.",
            "Find the largest integer $k$ in each case such that $d \\le 0.50\\text{ mm}$."
        ],
        "answer": "(a) $d = 0.490\\text{ mm}$;\n(b) $d = 0.475\\text{ mm}$",
        "solution": "**1. Optical Path Difference in a Retardation Plate:**\nFor a birefringent plate of thickness $d$ cut parallel to the optical axis, the optical path difference between the extraordinary and ordinary rays is:\n$$\\Delta = (n_e - n_o) d = \\Delta n \\cdot d$$\n\n**2. Part (a): Half-Wave Plate (Rotation of Polarization Plane):**\nA plate rotates the polarization plane of linearly polarized light if the phase difference between the ordinary and extraordinary components is an odd multiple of $\\pi$, which corresponds to an optical path difference:\n$$\\Delta n \\cdot d = (2k + 1) \\frac{\\lambda}{2} \\implies d = \\frac{(2k + 1)\\lambda}{2 \\Delta n}$$\nGiven $d \\le d_{\\text{max}} = 0.50\\text{ mm}$:\n$$2k + 1 \\le \\frac{2 \\Delta n \\cdot d_{\\text{max}}}{\\lambda} = \\frac{2 (0.0090)(0.50 \\times 10^{-3}\\text{ m})}{5.89 \\times 10^{-7}\\text{ m}} = \\frac{9.0 \\times 10^{-6}}{5.89 \\times 10^{-7}} \\approx 15.28$$\nThe largest odd integer is $2k + 1 = 15$ ($k = 7$):\n$$d = \\frac{15 (5.89 \\times 10^{-7}\\text{ m})}{2 (0.0090)} = \\frac{8.835 \\times 10^{-6}\\text{ m}}{0.018} \\approx 4.908 \\times 10^{-4}\\text{ m} \\approx 0.490\\text{ mm}$$\n\n**3. Part (b): Quarter-Wave Plate (Circular Polarization):**\nLinearly polarized light oriented at $45^\\circ$ to the principal axes becomes circularly polarized if the phase difference is an odd multiple of $\\pi/2$:\n$$\\Delta n \\cdot d = (2k + 1) \\frac{\\lambda}{4} \\implies d = \\frac{(2k + 1)\\lambda}{4 \\Delta n}$$\nFor $d \\le 0.50\\text{ mm}$:\n$$2k + 1 \\le \\frac{4 \\Delta n \\cdot d_{\\text{max}}}{\\lambda} = 2 \\times 15.28 \\approx 30.56$$\nThe largest odd integer is $2k + 1 = 29$ ($k = 14$):\n$$d = \\frac{29 (5.89 \\times 10^{-7}\\text{ m})}{4 (0.0090)} = \\frac{1.7081 \\times 10^{-5}\\text{ m}}{0.036} \\approx 4.745 \\times 10^{-4}\\text{ m} \\approx 0.475\\text{ mm}$$",
        "tags": ["wave plate", "half-wave plate", "quarter-wave plate", "birefringence", "quartz"]
    },
    {
        "id": "5.180",
        "title": "Wavelengths Producing Circular Polarization in a Crossed Nicol Setup",
        "difficulty": 2,
        "question": "A quartz plate cut parallel to the optical axis is placed between two crossed Nicol prisms. The angle between the principal directions of the Nicol prisms and the plate's optical axis is $45^\\circ$. The thickness of the plate is $d = 0.50\\text{ mm}$. At what wavelengths in the interval from $0.50$ to $0.60\\,\\mu\\text{m}$ is the intensity of light behind the system independent of the rotation of the rear prism? Assume $\\Delta n = n_e - n_o = 0.0090$ throughout this interval.",
        "hints": [
            "The transmitted intensity behind the rear prism is independent of its rotation if and only if the light emerging from the quartz plate is circularly polarized.",
            "Since the incident light is linearly polarized at $45^\\circ$ to the plate's optical axis, the emerging light is circularly polarized when the phase retardance is an odd multiple of $\\pi/2$: $\\Delta = d \\Delta n = (2k + 1) \\frac{\\lambda}{4}$.",
            "Solve for $\\lambda = \\frac{4 d \\Delta n}{2k + 1}$ and find all integer orders $k$ that give $\\lambda \\in [0.50\\,\\mu\\text{m}, 0.60\\,\\mu\\text{m}]$."
        ],
        "answer": "$\\lambda = \\frac{4 d \\Delta n}{2k + 1} = 0.58\\,\\mu\\text{m}, 0.55\\,\\mu\\text{m}, 0.51\\,\\mu\\text{m}$ (for $k = 15, 16, 17$)",
        "solution": "**1. Condition for Polarization Invariance Under Analyzer Rotation:**\nWhen light emerging from the plate is circularly polarized, the projection of its electric field onto any analyzer axis has constant amplitude ($E_0 / \\sqrt{2}$).\nTherefore, the transmitted intensity does not vary as the analyzer is rotated.\n\n**2. Quarter-Wave Retardation Condition:**\nThe incident linearly polarized light makes an angle of $45^\\circ$ with the optical axis of the plate, exciting the ordinary and extraordinary components with equal amplitudes ($E_{0o} = E_{0e} = E_0 / \\sqrt{2}$).\nThe condition for circular polarization is that the phase difference $\\delta$ between the two components be an odd multiple of $\\pi/2$:\n$$\\delta = \\frac{2\\pi}{\\lambda} d \\Delta n = (2k + 1) \\frac{\\pi}{2}$$\n$$d \\Delta n = (2k + 1) \\frac{\\lambda}{4} \\implies \\lambda = \\frac{4 d \\Delta n}{2k + 1}$$\n\n**3. Evaluation of Wavelengths:**\nGiven $d = 0.50\\text{ mm} = 500\\,\\mu\\text{m}$ and $\\Delta n = 0.0090$:\n$$4 d \\Delta n = 4 (500\\,\\mu\\text{m})(0.0090) = 18.0\\,\\mu\\text{m}$$\n$$\\lambda = \\frac{18.0\\,\\mu\\text{m}}{2k + 1}$$\nWe require $0.50\\,\\mu\\text{m} \\le \\lambda \\le 0.60\\,\\mu\\text{m}$:\n$$0.50 \\le \\frac{18.0}{2k + 1} \\le 0.60 \\implies 30 \\le 2k + 1 \\le 36$$\nThe odd integers in this range are $2k + 1 = 31, 33, 35$:\n- For $2k + 1 = 31$ ($k = 15$): $\\lambda = \\frac{18.0}{31} \\approx 0.5806\\,\\mu\\text{m} \\approx 0.58\\,\\mu\\text{m}$\n- For $2k + 1 = 33$ ($k = 16$): $\\lambda = \\frac{18.0}{33} \\approx 0.5455\\,\\mu\\text{m} \\approx 0.55\\,\\mu\\text{m}$\n- For $2k + 1 = 35$ ($k = 17$): $\\lambda = \\frac{18.0}{35} \\approx 0.5143\\,\\mu\\text{m} \\approx 0.51\\,\\mu\\text{m}$",
        "tags": ["quartz plate", "crossed Nicols", "circular polarization", "birefringence", "retardation"]
    },
    {
        "id": "5.181",
        "title": "Number of Dark Fringes in the Spectrum of Polarized White Light",
        "difficulty": 2,
        "question": "White natural light falls on a system of two crossed Nicol prisms containing between them a quartz plate $d = 1.50\\text{ mm}$ thick, cut parallel to the optical axis. The axis of the plate forms an angle of $45^\\circ$ with the principal directions of the Nicol prisms. The light transmitted through the system is dispersed into a spectrum. How many dark fringes will be observed in the wavelength interval from $0.55$ to $0.66\\,\\mu\\text{m}$? Assume $\\Delta n = n_e - n_o = 0.0090$ throughout this interval.",
        "hints": [
            "For crossed Nicols with a birefringent plate at $45^\\circ$, the transmitted intensity is $I = I_0 \\sin^2(\\delta/2)$, where $\\delta = \\frac{2\\pi}{\\lambda} d \\Delta n$.",
            "A dark fringe in the spectrum corresponds to zero transmission, which occurs when $\\delta = 2m \\pi \\implies d \\Delta n = m \\lambda$, where $m$ is an integer.",
            "Calculate $m$ for the endpoints $\\lambda_1 = 0.66\\,\\mu\\text{m}$ and $\\lambda_2 = 0.55\\,\\mu\\text{m}$ and count the number of integer values of $m$."
        ],
        "answer": "Four dark fringes ($m = 21, 22, 23, 24$)",
        "solution": "**1. Transmitted Intensity Condition:**\nWhen a plate with principal axes at $45^\\circ$ to the polarizer is placed between crossed polarizers, the transmitted intensity for wavelength $\\lambda$ is:\n$$I(\\lambda) = I_0 \\sin^2\\left(\\frac{\\delta}{2}\\right)$$\nwhere the phase retardance is:\n$$\\delta = \\frac{2\\pi}{\\lambda} d \\Delta n$$\n\n**2. Dark Fringe Condition:**\nDark fringes (extinction lines) in the channeled spectrum occur when $I(\\lambda) = 0$, meaning:\n$$\\frac{\\delta}{2} = m \\pi \\implies d \\Delta n = m \\lambda \\implies m = \\frac{d \\Delta n}{\\lambda}$$\nwhere $m$ is an integer.\n\n**3. Optical Path Difference:**\nGiven $d = 1.50\\text{ mm} = 1500\\,\\mu\\text{m}$ and $\\Delta n = 0.0090$:\n$$d \\Delta n = 1500\\,\\mu\\text{m} \\times 0.0090 = 13.5\\,\\mu\\text{m}$$\n\n**4. Range of Interference Orders:**\n- At the upper bound $\\lambda_1 = 0.66\\,\\mu\\text{m}$:\n  $$m_1 = \\frac{13.5}{0.66} \\approx 20.45$$\n- At the lower bound $\\lambda_2 = 0.55\\,\\mu\\text{m}$:\n  $$m_2 = \\frac{13.5}{0.55} \\approx 24.55$$\nThe integer values of $m$ falling strictly within this range are:\n$$m = 21, 22, 23, 24$$\nThere are exactly **4 dark fringes** in the spectrum.",
        "tags": ["channeled spectrum", "crossed Nicols", "quartz plate", "dark fringes", "birefringence"]
    },
    {
        "id": "5.182",
        "title": "Visible Wavelengths for Multi-Order Quarter-Wave Plate",
        "difficulty": 2,
        "question": "A crystalline plate cut parallel to its optical axis is $d = 0.25\\text{ mm}$ thick and serves as a quarter-wave plate for wavelength $\\lambda_0 = 530\\text{ nm}$. At what other wavelengths in the visible spectrum will it also serve as a quarter-wave plate? Assume $\\Delta n = n_e - n_o = 0.0090$ is constant across the visible spectrum ($400\\text{ nm}$ to $750\\text{ nm}$).",
        "hints": [
            "Calculate the optical path difference $\\Delta = d \\Delta n$.",
            "A plate acts as a quarter-wave plate when $\\Delta = \\left(k + \\frac{1}{4}\\right)\\lambda$ or $(2m + 1)\\frac{\\lambda}{4}$. For effective quarter-wave retardance with the same fast/slow orientation, $\\Delta = (m + 1/4)\\lambda$ or $(2m+1)\\lambda/4$.",
            "Identify the order at $\\lambda = 530\\text{ nm}$ and find the wavelengths corresponding to the adjacent allowed orders in the visible range."
        ],
        "answer": "$\\lambda = 0.69\\,\\mu\\text{m}$ and $0.43\\,\\mu\\text{m}$",
        "solution": "**1. Optical Path Difference:**\n$$\\Delta = d \\Delta n = (0.25\\text{ mm})(0.0090) = 2.25\\,\\mu\\text{m} = 2250\\text{ nm}$$\n\n**2. Quarter-Wave Plate Condition:**\nA plate acts as a quarter-wave plate if the path difference is an odd multiple of quarter wavelengths:\n$$\\Delta = (2m + 1) \\frac{\\lambda}{4} \\implies \\lambda = \\frac{4 \\Delta}{2m + 1} = \\frac{9000\\text{ nm}}{2m + 1}$$\nAt $\\lambda_0 = 530\\text{ nm}$:\n$$2m_0 + 1 = \\frac{9000}{530} \\approx 16.98 \\implies 2m_0 + 1 = 17$$\n\n**3. Other Visible Wavelengths:**\nQuarter-wave behavior that converts linear polarization at $45^\\circ$ into the same handedness of circular polarization corresponds to $\\Delta = (k + 1/4)\\lambda$, which changes $2m + 1$ by steps of 4 (i.e. $2m + 1 = 17 \\pm 4 = 13$ and $21$):\n- For $2m + 1 = 13$:\n  $$\\lambda_1 = \\frac{9000\\text{ nm}}{13} \\approx 692.3\\text{ nm} \\approx 0.69\\,\\mu\\text{m}$$\n- For $2m + 1 = 21$:\n  $$\\lambda_2 = \\frac{9000\\text{ nm}}{21} \\approx 428.6\\text{ nm} \\approx 0.43\\,\\mu\\text{m}$$\nBoth $0.69\\,\\mu\\text{m}$ and $0.43\\,\\mu\\text{m}$ lie well within the visible range.",
        "tags": ["quarter-wave plate", "retardation", "chromatic response", "birefringence", "visible spectrum"]
    },
    {
        "id": "5.183",
        "title": "Plate Thickness for Simultaneous Transmission and Extinction of Doublet Wavelengths",
        "difficulty": 2,
        "question": "A quartz plate cut parallel to its optical axis is placed between two crossed Nicol prisms with its optical axis at $45^\\circ$ to their principal directions. Find the minimum thickness $d$ of the plate that transmits light of wavelength $\\lambda_1 = 643\\text{ nm}$ with maximum intensity while substantially extinguishing light of wavelength $\\lambda_2 = 564\\text{ nm}$. Assume $\\Delta n = n_e - n_o = 0.0090$ for both wavelengths.",
        "hints": [
            "For crossed Nicols with axes at $45^\\circ$, maximum transmission occurs when $\\Delta = (2k_1 - 1) \\frac{\\lambda_1}{2}$.",
            "Complete extinction occurs when $\\Delta = k_2 \\lambda_2$, where $k_2$ is an integer.",
            "Equating the path difference gives $\\frac{2k_1 - 1}{2 k_2} = \\frac{\\lambda_2}{\\lambda_1} = \\frac{564}{643} \\approx 0.8771$. Find small integer values of $k_1$ and $k_2$ satisfying this ratio."
        ],
        "answer": "$d = \\frac{(k - 1/2)\\lambda_1}{\\Delta n} = 0.25\\text{ mm}$ (for $k = 4$)",
        "solution": "**1. Transmission and Extinction Conditions:**\nFor crossed Nicol prisms, the transmitted intensity is $I = I_0 \\sin^2(\\delta/2)$:\n- Maximum transmission for $\\lambda_1$ requires a half-wave condition:\n  $$\\Delta = \\left(k_1 - \\frac{1}{2}\\right) \\lambda_1 = \\frac{2k_1 - 1}{2} \\lambda_1$$\n- Complete extinction for $\\lambda_2$ requires a full-wave condition:\n  $$\\Delta = k_2 \\lambda_2$$\n\n**2. Determining the Order:**\nEquating both path differences:\n$$\\frac{2k_1 - 1}{2 k_2} = \\frac{\\lambda_2}{\\lambda_1} = \\frac{564\\text{ nm}}{643\\text{ nm}} \\approx 0.87713$$\nTesting integer values for $k_1$:\n- For $k_1 = 4$: $2k_1 - 1 = 7$.\n  $$2 k_2 = \\frac{7}{0.87713} \\approx 7.9806 \\approx 8 \\implies k_2 = 4$$\nThis matches extremely well ($7/8 = 0.875$ vs $564/643 = 0.877$).\n\n**3. Minimum Thickness Calculation:**\nUsing $k_1 = 4$:\n$$\\Delta = \\left(4 - \\frac{1}{2}\\right) \\lambda_1 = 3.5 \\times 643\\text{ nm} = 2250.5\\text{ nm} \\approx 2.25\\,\\mu\\text{m}$$\nSince $\\Delta = d \\Delta n$:\n$$d = \\frac{\\Delta}{\\Delta n} = \\frac{2.25\\,\\mu\\text{m}}{0.0090} = 250\\,\\mu\\text{m} = 0.25\\text{ mm}$$",
        "tags": ["quartz plate", "crossed Nicols", "optical filter", "birefringence", "wavelength selection"]
    },
    {
        "id": "5.184",
        "title": "Birefringence of Quartz from Interference Fringes in a Polarized Wedge",
        "difficulty": 2,
        "question": "A quartz wedge with refracting angle $\\theta = 3.5^\\circ$ is inserted between two crossed Polaroids. The optical axis of the wedge is parallel to its edge and forms an angle of $45^\\circ$ with the principal directions of the Polaroids. On transmission of light with wavelength $\\lambda = 550\\text{ nm}$ through this system, an interference fringe pattern of width $\\Delta x = 1.0\\text{ mm}$ is formed. Find the difference of refractive indices $\\Delta n = n_e - n_o$ of quartz at this wavelength.",
        "hints": [
            "At distance $x$ from the apex of the wedge, the thickness is $d(x) = x \\theta$ (with $\\theta$ in radians).",
            "The optical path difference between the extraordinary and ordinary rays is $\\Delta(x) = d(x) \\Delta n = x \\theta \\Delta n$.",
            "The fringe width $\\Delta x$ corresponds to an increase in optical path difference of one wavelength: $\\Delta x \\cdot \\theta \\Delta n = \\lambda$. Solve for $\\Delta n = \\frac{\\lambda}{\\Delta x \\cdot \\theta}$."
        ],
        "answer": "$\\Delta n = \\frac{\\lambda}{\\Delta x \\cdot \\theta} = 0.0090$",
        "solution": "**1. Path Difference in the Quartz Wedge:**\nFor a wedge of refracting angle $\\theta \\ll 1\\text{ rad}$, the thickness at distance $x$ from the edge is:\n$$d(x) = x \\tan\\theta \\approx x \\theta$$\nThe optical path difference between the extraordinary and ordinary rays transmitted normally through the wedge is:\n$$\\Delta(x) = (n_e - n_o) d(x) = \\Delta n \\cdot x \\theta$$\n\n**2. Fringe Spacing:**\nBetween crossed Polaroids, dark fringes appear where the path difference is an integer multiple of $\\lambda$:\n$$\\Delta(x) = m \\lambda$$\nThe separation between consecutive dark fringes is $\\Delta x$, so:\n$$\\Delta(x + \\Delta x) - \\Delta(x) = \\lambda \\implies \\Delta n \\cdot \\Delta x \\cdot \\theta = \\lambda$$\n$$\\Delta n = \\frac{\\lambda}{\\Delta x \\cdot \\theta}$$\n\n**3. Numerical Evaluation:**\nGiven $\\lambda = 550\\text{ nm} = 5.50 \\times 10^{-7}\\text{ m}$, $\\Delta x = 1.0\\text{ mm} = 1.0 \\times 10^{-3}\\text{ m}$, and $\\theta = 3.5^\\circ$:\n$$\\theta = 3.5 \\times \\frac{\\pi}{180} \\approx 0.06109\\text{ rad}$$\n$$\\Delta n = \\frac{5.50 \\times 10^{-7}\\text{ m}}{(1.0 \\times 10^{-3}\\text{ m})(0.06109\\text{ rad})} = \\frac{5.50 \\times 10^{-4}}{0.06109} \\approx 0.00900$$",
        "tags": ["quartz wedge", "crossed Polaroids", "interference fringes", "birefringence", "refractive index"]
    },
    {
        "id": "5.185",
        "title": "General Intensity Distribution of Polarized Light Passing Through a Birefringent Plate",
        "difficulty": 3,
        "question": "Natural monochromatic light of intensity $I_0$ falls on a system of two Polaroids between which a crystalline plate is inserted, cut parallel to its optical axis. The plate introduces a phase difference $\\delta$ between the ordinary and extraordinary rays. Demonstrate that the intensity of light transmitted through the system is:\n$$I = \\frac{1}{2} I_0 \\left[ \\cos^2(\\varphi - \\varphi') - \\sin 2\\varphi \\sin 2\\varphi' \\sin^2\\left(\\frac{\\delta}{2}\\right) \\right]$$\nwhere $\\varphi$ and $\\varphi'$ are the angles between the optical axis of the crystal and the principal directions of the polarizer and analyzer respectively. Analyze the special cases of crossed and parallel Polaroids.",
        "hints": [
            "Natural light entering the first Polaroid becomes linearly polarized with intensity $I_1 = \\frac{1}{2} I_0$ and amplitude $E_1 = \\sqrt{I_0/2}$.",
            "Resolve $E_1$ along the optical axis (extraordinary) and perpendicular to it (ordinary): $E_e = E_1 \\cos\\varphi$ and $E_o = E_1 \\sin\\varphi$.",
            "After traversing the plate, a phase difference $\\delta$ is introduced: $E_e' = E_1 \\cos\\varphi$, $E_o' = E_1 \\sin\\varphi \\, e^{i\\delta}$. Project both onto the analyzer axis at angle $\\varphi'$ and compute the resultant intensity."
        ],
        "answer": "$I = \\frac{1}{2} I_0 [\\cos^2(\\varphi - \\varphi') - \\sin 2\\varphi \\sin 2\\varphi' \\sin^2(\\delta/2)]$; for crossed Polaroids: $I_\\perp = \\frac{1}{2} I_0 \\sin^2 2\\varphi \\sin^2(\\delta/2)$; for parallel Polaroids: $I_\\parallel = \\frac{1}{2} I_0 [1 - \\sin^2 2\\varphi \\sin^2(\\delta/2)]$",
        "solution": "**1. Electric Field Projections:**\nNatural light of intensity $I_0$ passing through the first Polaroid emerges with linear polarization of intensity $I_1 = \\frac{1}{2} I_0$ and amplitude $E_1$.\nLet the optical axis of the crystal plate define the $x$-axis, and the perpendicular direction define the $y$-axis.\nThe polarizer transmission axis makes angle $\\varphi$ with the $x$-axis:\n$$E_x = E_1 \\cos\\varphi, \\quad E_y = E_1 \\sin\\varphi$$\n\n**2. Phase Retardation Across the Crystal:**\nThe plate introduces a relative phase shift $\\delta$:\n$$E_x' = E_1 \\cos\\varphi, \\quad E_y' = E_1 \\sin\\varphi \\, e^{i\\delta}$$\n\n**3. Projection onto the Analyzer Axis:**\nThe transmission axis of the analyzer makes angle $\\varphi'$ with the $x$-axis.\nThe transmitted amplitude is:\n$$E = E_x' \\cos\\varphi' + E_y' \\sin\\varphi' = E_1 (\\cos\\varphi \\cos\\varphi' + \\sin\\varphi \\sin\\varphi' e^{i\\delta})$$\n\n**4. Calculating Transmitted Intensity:**\n$$|E|^2 = E_1^2 |\\cos\\varphi \\cos\\varphi' + \\sin\\varphi \\sin\\varphi' (\\cos\\delta + i \\sin\\delta)|^2$$\n$$|E|^2 = E_1^2 \\left[ (\\cos\\varphi \\cos\\varphi' + \\sin\\varphi \\sin\\varphi' \\cos\\delta)^2 + (\\sin\\varphi \\sin\\varphi' \\sin\\delta)^2 \\right]$$\n$$|E|^2 = E_1^2 \\left[ \\cos^2\\varphi \\cos^2\\varphi' + \\sin^2\\varphi \\sin^2\\varphi' + 2 \\cos\\varphi \\cos\\varphi' \\sin\\varphi \\sin\\varphi' \\cos\\delta \\right]$$\nUsing $\\cos^2(\\varphi - \\varphi') = (\\cos\\varphi \\cos\\varphi' + \\sin\\varphi \\sin\\varphi')^2 = \\cos^2\\varphi \\cos^2\\varphi' + \\sin^2\\varphi \\sin^2\\varphi' + 2 \\cos\\varphi \\cos\\varphi' \\sin\\varphi \\sin\\varphi'$:\n$$|E|^2 = E_1^2 \\left[ \\cos^2(\\varphi - \\varphi') - 2 \\cos\\varphi \\sin\\varphi \\cos\\varphi' \\sin\\varphi' (1 - \\cos\\delta) \\right]$$\nNoting that $2 \\cos\\varphi \\sin\\varphi = \\sin 2\\varphi$ and $1 - \\cos\\delta = 2 \\sin^2(\\delta/2)$:\n$$I = \\frac{1}{2} I_0 \\left[ \\cos^2(\\varphi - \\varphi') - \\sin 2\\varphi \\sin 2\\varphi' \\sin^2\\left(\\frac{\\delta}{2}\\right) \\right]$$\n\n**5. Special Cases:**\n- **Crossed Polaroids ($\\varphi' = \\varphi + \\pi/2$):**\n  $\\cos(\\varphi - \\varphi') = \\cos(-\\pi/2) = 0$, and $\\sin 2\\varphi' = \\sin(2\\varphi + \\pi) = -\\sin 2\\varphi$:\n  $$I_\\perp = \\frac{1}{2} I_0 \\sin^2 2\\varphi \\sin^2\\left(\\frac{\\delta}{2}\\right)$$\n- **Parallel Polaroids ($\\varphi' = \\varphi$):**\n  $\\cos(\\varphi - \\varphi') = 1$, and $\\sin 2\\varphi' = \\sin 2\\varphi$:\n  $$I_\\parallel = \\frac{1}{2} I_0 \\left[ 1 - \\sin^2 2\\varphi \\sin^2\\left(\\frac{\\delta}{2}\\right) \\right]$$",
        "tags": ["birefringent plate", "polarizers", "intensity formula", "general polarization", "derivation"]
    },
    {
        "id": "5.186",
        "title": "Transmission of Circularly Polarized Light Through a Retardation Plate and Analyzer",
        "difficulty": 2,
        "question": "Monochromatic light with circular polarization falls normally on a crystalline plate cut parallel to the optical axis. Behind the plate there is a Nicol prism whose principal direction forms an angle $\\varphi$ with the optical axis of the plate. Demonstrate that the intensity of light transmitted through this system is:\n$$I = \\frac{1}{2} I_0 (1 \\pm \\sin 2\\varphi \\sin\\delta)$$\nwhere $\\delta$ is the phase difference between the ordinary and extraordinary rays introduced by the plate.",
        "hints": [
            "Represent circularly polarized light of intensity $I_0$ as two orthogonal components along the crystal's axes: $E_x = \\frac{E_0}{\\sqrt{2}} \\cos\\omega t$ and $E_y = \\pm \\frac{E_0}{\\sqrt{2}} \\sin\\omega t$.",
            "After passing through the plate, the phase difference changes by $\\delta$: $E_x' = \\frac{E_0}{\\sqrt{2}} e^{i\\omega t}$, $E_y' = \\pm \\frac{E_0}{\\sqrt{2}} e^{i(\\omega t \\pm \\pi/2 + \\delta)}$.",
            "Project onto the analyzer axis at angle $\\varphi$: $E = E_x' \\cos\\varphi + E_y' \\sin\\varphi$, and compute $I = |E|^2$."
        ],
        "answer": "$I = \\frac{1}{2} I_0 (1 \\pm \\sin 2\\varphi \\sin\\delta)$",
        "solution": "**1. Incident Circularly Polarized Wave:**\nLet the optical axis of the crystalline plate be along the $x$-axis.\nCircularly polarized light of intensity $I_0$ and total amplitude $E_0$ has components:\n$$E_x(t) = \\frac{E_0}{\\sqrt{2}} e^{i\\omega t}, \\quad E_y(t) = \\frac{E_0}{\\sqrt{2}} e^{i(\\omega t \\pm \\pi/2)} = \\pm i \\frac{E_0}{\\sqrt{2}} e^{i\\omega t}$$\nwhere the sign $\\pm$ corresponds to left- or right-hand circular polarization.\n\n**2. Action of the Crystalline Plate:**\nThe plate introduces a relative phase retardance $\\delta$ between the $y$ and $x$ components:\n$$E_x' = \\frac{E_0}{\\sqrt{2}} e^{i\\omega t}, \\quad E_y' = \\pm i \\frac{E_0}{\\sqrt{2}} e^{i(\\omega t + \\delta)}$$\n\n**3. Action of the Analyzer:**\nThe Nicol prism's transmission axis is oriented at angle $\\varphi$ to the $x$-axis.\nThe transmitted field amplitude is:\n$$E = E_x' \\cos\\varphi + E_y' \\sin\\varphi = \\frac{E_0}{\\sqrt{2}} e^{i\\omega t} \\left( \\cos\\varphi \\pm i \\sin\\varphi e^{i\\delta} \\right)$$\n$$E = \\frac{E_0}{\\sqrt{2}} e^{i\\omega t} \\left[ \\cos\\varphi \\pm i \\sin\\varphi (\\cos\\delta + i \\sin\\delta) \\right] = \\frac{E_0}{\\sqrt{2}} e^{i\\omega t} \\left[ (\\cos\\varphi \\mp \\sin\\varphi \\sin\\delta) \\pm i \\sin\\varphi \\cos\\delta \\right]$$\n\n**4. Calculating Transmitted Intensity:**\n$$I = |E|^2 = \\frac{E_0^2}{2} \\left[ (\\cos\\varphi \\mp \\sin\\varphi \\sin\\delta)^2 + (\\sin\\varphi \\cos\\delta)^2 \\right]$$\n$$I = \\frac{I_0}{2} \\left[ \\cos^2\\varphi \\mp 2 \\cos\\varphi \\sin\\varphi \\sin\\delta + \\sin^2\\varphi \\sin^2\\delta + \\sin^2\\varphi \\cos^2\\delta \\right]$$\nSince $\\sin^2\\varphi \\sin^2\\delta + \\sin^2\\varphi \\cos^2\\delta = \\sin^2\\varphi$:\n$$I = \\frac{I_0}{2} \\left[ \\cos^2\\varphi + \\sin^2\\varphi \\mp 2 \\sin\\varphi \\cos\\varphi \\sin\\delta \\right]$$\n$$I = \\frac{1}{2} I_0 (1 \\pm \\sin 2\\varphi \\sin\\delta)$$\nThis proves the formula.",
        "tags": ["circular polarization", "retardation plate", "Nicol prism", "phase difference", "derivation"]
    },
    {
        "id": "5.187",
        "title": "Experimental Discrimination of Polarization States Using a Quarter-Wave Plate",
        "difficulty": 2,
        "question": "Explain how, using a Polaroid and a quarter-wave plate made of a positive uniaxial crystal ($n_e > n_o$), to distinguish:\n(a) light with left-hand circular polarization from that with right-hand circular polarization;\n(b) natural light from circularly polarized light, and from a mixture of natural and circularly polarized light.",
        "hints": [
            "(a) When circularly polarized light traverses a quarter-wave plate, it is converted into linearly polarized light. For a positive crystal ($n_e > n_o$), the slow axis is along the optical axis; the orientation of the resulting linear polarization ($+45^\\circ$ vs $-45^\\circ$ to the optical axis) reveals the handedness.",
            "(b) For natural light, the quarter-wave plate leaves it completely unpolarized, so rotating a subsequent Polaroid produces constant intensity.",
            "For circularly polarized light, the plate converts it into $100\\%$ linearly polarized light, so rotating the Polaroid produces complete extinction at a certain angle. For mixed light, intensity varies between non-zero minimum and maximum."
        ],
        "answer": "(a) Right-hand circular light becomes linearly polarized at $+45^\\circ$ to the optic axis, left-hand at $-45^\\circ$;\n(b) Rotating Polaroid gives: constant intensity for natural light, complete extinction for circular light, partial modulation without extinction for mixed light.",
        "solution": "**1. Part (a): Distinguishing Left-Hand from Right-Hand Circular Polarization:**\nPass the beam normally through the quarter-wave plate.\nIn a positive uniaxial crystal ($n_e > n_o$), the optical axis is the slow axis.\n- Circularly polarized light has equal amplitudes along the fast and slow axes with a phase shift of $\\pm \\pi/2$.\n- The quarter-wave plate introduces an additional phase difference of $\\pi/2$.\n- For **right-hand circular polarization** (looking toward the incoming wave), the total phase difference becomes $0$ or $\\pi$, transforming the wave into linearly polarized light oscillating at an angle of $+45^\\circ$ relative to the optical axis.\n- For **left-hand circular polarization**, the phase difference becomes $\\pi$ or $2\\pi$, transforming the wave into linearly polarized light oscillating at an angle of $-45^\\circ$ relative to the optical axis.\nBy rotating the Polaroid placed behind the plate and finding the orientation of maximum transmission (or extinction), the handedness is uniquely determined.\n\n**2. Part (b): Distinguishing Natural, Circular, and Mixed Light:**\nSend the light through the quarter-wave plate and then through the rotating Polaroid:\n1. **Natural (unpolarized) light:** The quarter-wave plate adds a phase shift to incoherent orthogonal components, leaving the light completely unpolarized. Rotating the Polaroid produces **no change in intensity** for any orientation of the plate.\n2. **Circularly polarized light:** The quarter-wave plate transforms the light into $100\\%$ linearly polarized light. As the Polaroid is rotated, the intensity varies and **drops to zero** (complete extinction) at the crossed position.\n3. **Mixture of natural and circularly polarized light:** The circular component is converted into linear polarization while the natural component remains unpolarized. Rotating the Polaroid causes the intensity to **modulate between a maximum and a non-zero minimum**.",
        "tags": ["polarization analysis", "quarter-wave plate", "Polaroid", "circular polarization", "optical diagnostics"]
    },
    {
        "id": "5.188",
        "title": "Babinet Compensator Fringe Width and Optical Path Difference",
        "difficulty": 3,
        "question": "Light with wavelength $\\lambda$ falls on a system of crossed polarizer $P$ and analyzer $A$ containing a Babinet compensator $C$. The compensator consists of two quartz wedges with small refracting angle $\\theta \\ll 1$, where the optical axis of one wedge is parallel to its edge and of the other is perpendicular to it. The principal directions of $P$ and $A$ form an angle of $45^\\circ$ with the optical axes of the compensator. The difference of refractive indices of quartz is $\\Delta n = n_e - n_o$. When a birefringent sample $S$ is inserted, the fringes shift by $\\delta x$. Find:\n(a) the fringe width $\\Delta x$;\n(b) the magnitude and sign of the optical path difference introduced by the sample.",
        "hints": [
            "(a) At distance $x$ from the position where the two wedges have equal thickness, the thickness difference is $\\Delta d(x) = 2 x \\theta$. The optical path difference is $\\Delta(x) = 2 x \\theta (n_e - n_o)$.",
            "The fringe width corresponds to $\\Delta(x + \\Delta x) - \\Delta(x) = \\lambda$, so $\\Delta x = \\frac{\\lambda}{2 \\theta (n_e - n_o)}$.",
            "(b) When a sample of optical path difference $\\Delta_S$ is inserted, the fringe pattern shifts by $\\delta x$ such that $\\Delta_S + 2 \\theta \\Delta n \\,\\delta x = 0$."
        ],
        "answer": "(a) $\\Delta x = \\frac{\\lambda}{2 \\theta (n_e - n_o)}$;\n(b) $\\Delta_S = d(n_o' - n_e') = -2 \\theta (n_e - n_o) \\delta x$",
        "solution": "**1. Part (a): Optical Path Difference and Fringe Width in Babinet Compensator:**\nThe compensator consists of two identical quartz wedges with refracting angle $\\theta$ whose optical axes are mutually perpendicular.\nLet $x$ be the coordinate measured from the center line where both wedges have equal thickness $d_1 = d_2$.\nAt distance $x$, the thickness of wedge 1 is $d_1 = d_0 + x \\theta$ and of wedge 2 is $d_2 = d_0 - x \\theta$.\nBecause the optical axes are perpendicular, the ordinary ray in wedge 1 becomes extraordinary in wedge 2, and vice versa.\nThe total optical path difference introduced by the compensator is:\n$$\\Delta_C(x) = (n_e - n_o) d_1 - (n_e - n_o) d_2 = (n_e - n_o)(d_1 - d_2) = 2 x \\theta (n_e - n_o)$$\nBetween crossed polarizers at $45^\\circ$, dark fringes appear where $\\Delta_C(x) = m \\lambda$.\nThe width of each interference fringe is:\n$$\\Delta x = \\frac{\\lambda}{2 \\theta (n_e - n_o)}$$\n\n**2. Part (b): Path Difference of the Birefringent Sample:**\nWhen an unknown birefringent sample $S$ of thickness $d$ and refractive indices $n_o', n_e'$ is inserted into the beam, it adds a constant path difference $\\Delta_S = d(n_e' - n_o')$.\nThe total path difference becomes:\n$$\\Delta_{\\text{total}} = \\Delta_S + 2 x \\theta (n_e - n_o)$$\nThe central fringe ($m = 0$, where $\\Delta_{\\text{total}} = 0$) shifts from $x = 0$ to a new position $x = \\delta x$:\n$$\\Delta_S + 2 \\delta x \\,\\theta (n_e - n_o) = 0$$\n$$\\Delta_S = -2 \\theta (n_e - n_o) \\delta x$$\nIn terms of the fringe spacing $\\Delta x = \\frac{\\lambda}{2 \\theta (n_e - n_o)}$:\n$$\\Delta_S = -\\lambda \\frac{\\delta x}{\\Delta x}$$",
        "tags": ["Babinet compensator", "birefringence", "fringe shift", "optical path difference", "polarization"]
    },
    {
        "id": "5.189",
        "title": "Circular Birefringence of Quartz from Specific Rotation",
        "difficulty": 2,
        "question": "Using the specific rotation constant of quartz for sodium light ($\\\\lambda = 589.5\\text{ nm}$), $\\alpha = 21.7^\\circ/\\text{mm}$, calculate the difference of refractive indices $\\Delta n = |n_L - n_R|$ of quartz for right-hand and left-hand circularly polarized light.",
        "hints": [
            "According to Fresnel's theory of optical activity, optical rotation is caused by circular birefringence: $\\alpha = \\frac{\\pi}{\\lambda} (n_L - n_R)$.",
            "Express the specific rotation $\\alpha$ in radians per meter (or radians per millimeter).",
            "Solve for $\\Delta n = \\frac{\\alpha \\lambda}{\\pi}$."
        ],
        "answer": "$\\Delta n = \\frac{\\alpha \\lambda}{\\pi} = 0.71 \\times 10^{-4}$",
        "solution": "**1. Fresnel's Relation for Optical Activity:**\nLinearly polarized light can be decomposed into two circular components of opposite handedness.\nBecause the phase velocities of the left- and right-circularly polarized waves are slightly different ($v_L \\ne v_R$), a phase difference accumulates over distance $l$:\n$$\\Delta\\phi = \\frac{2\\pi l}{\\lambda} (n_L - n_R)$$\nThis relative phase shift rotates the plane of polarization by an angle:\n$$\\varphi = \\frac{\\Delta\\phi}{2} = \\frac{\\pi l}{\\lambda} (n_L - n_R)$$\nThe specific rotation per unit length is:\n$$\\alpha = \\frac{\\varphi}{l} = \\frac{\\pi}{\\lambda} \\Delta n$$\nwhere $\\Delta n = |n_L - n_R|$.\n\n**2. Calculation of Difference in Refractive Indices:**\n$$\\Delta n = \\frac{\\alpha \\lambda}{\\pi}$$\nGiven $\\alpha = 21.7^\\circ/\\text{mm}$ and $\\lambda = 589.5\\text{ nm} = 5.895 \\times 10^{-4}\\text{ mm}$:\nConverting $\\alpha$ to radians per millimeter:\n$$\\alpha = 21.7 \\times \\frac{\\pi}{180}\\text{ rad/mm} \\approx 0.3787\\text{ rad/mm}$$\n$$\\Delta n = \\frac{(0.3787\\text{ rad/mm})(5.895 \\times 10^{-4}\\text{ mm})}{\\pi} = \\frac{21.7}{180} \\times 5.895 \\times 10^{-4}$$\n$$\\Delta n = (0.12056)(5.895 \\times 10^{-4}) \\approx 0.7107 \\times 10^{-4} \\approx 0.71 \\times 10^{-4}$$",
        "tags": ["optical activity", "circular birefringence", "Fresnel theory", "quartz", "specific rotation"]
    },
    {
        "id": "5.190",
        "title": "Specific Rotation Constant of Quartz from Prism Fringe Pattern",
        "difficulty": 2,
        "question": "Plane-polarized light of wavelength $\\lambda = 0.59\\,\\mu\\text{m}$ falls normally on a trihedral quartz prism with refracting angle $\\theta = 30^\\circ$. Inside the prism light propagates along the optical axis. Behind an analyzer Polaroid, an interference pattern of bright and dark fringes of width $\\Delta x = 15.0\\text{ mm}$ is observed. Find the specific rotation constant $\\alpha$ of quartz and express the intensity distribution $I(x)$ behind the Polaroid.",
        "hints": [
            "Inside the prism, light propagates along the optical axis, so it experiences optical activity (rotation of the plane of polarization by angle $\\varphi(x) = \\alpha l(x)$).",
            "The thickness of the prism at distance $x$ from the refracting edge is $l(x) = x \\tan\\theta$.",
            "The polarization plane rotates by $\\varphi(x) = \\alpha x \\tan\\theta$. The fringe spacing $\\Delta x$ corresponds to a rotation of $\\pi$: $\\alpha \\Delta x \\tan\\theta = \\pi$. Solve for $\\alpha$."
        ],
        "answer": "$\\alpha = \\frac{\\pi}{\\Delta x \\tan\\theta} = 21^\\circ/\\text{mm}$; $I(x) \\propto \\cos^2\\left(\\frac{\\pi x}{\\Delta x}\\right)$",
        "solution": "**1. Path Length and Rotation of Polarization Plane:**\nAt a distance $x$ from the apex of the quartz prism of refracting angle $\\theta$, the optical path length along the ray is:\n$$l(x) = x \\tan\\theta$$\nSince the light travels along the optical axis, birefringence is absent and the medium exhibits pure natural optical rotation.\nThe plane of polarization rotates by:\n$$\\varphi(x) = \\alpha l(x) = \\alpha x \\tan\\theta$$\nwhere $\\alpha$ is the specific rotation constant.\n\n**2. Intensity Behind the Polaroid:**\nPassing through the analyzer Polaroid, the transmitted intensity follows Malus's law:\n$$I(x) = I_{\\text{max}} \\cos^2[\\varphi(x) - \\varphi_0] = I_{\\text{max}} \\cos^2\\left(\\alpha x \\tan\\theta - \\varphi_0\\right)$$\nChoosing the origin at a transmission maximum ($\\varphi_0 = 0$):\n$$I(x) \\propto \\cos^2(\\alpha x \\tan\\theta)$$\n\n**3. Fringe Spacing and Determination of $\\alpha$:**\nThe period of the $\\cos^2$ intensity pattern is $\\pi$:\n$$\\alpha \\Delta x \\tan\\theta = \\pi \\implies \\alpha = \\frac{\\pi}{\\Delta x \\tan\\theta}$$\nIn terms of $\\Delta x$, the intensity distribution is:\n$$I(x) \\propto \\cos^2\\left(\\frac{\\pi x}{\\Delta x}\\right)$$\n\n**4. Numerical Evaluation:**\nGiven $\\Delta x = 15.0\\text{ mm}$ and $\\theta = 30^\\circ$ ($\\tan 30^\\circ = \\frac{1}{\\sqrt{3}} \\approx 0.57735$):\n$$\\alpha = \\frac{180^\\circ}{(15.0\\text{ mm})(0.57735)} = \\frac{180^\\circ}{8.660\\text{ mm}} \\approx 20.78^\\circ/\\text{mm} \\approx 21^\\circ/\\text{mm}$$",
        "tags": ["optical activity", "quartz prism", "specific rotation", "interference fringes", "Malus's law"]
    },
    {
        "id": "5.191",
        "title": "Minimum Thickness of an Optically Active Quartz Plate for Given Transmission",
        "difficulty": 2,
        "question": "Natural monochromatic light falls on a system of two crossed Nicol prisms containing a quartz plate cut perpendicular to its optical axis. Find the minimum thickness $d_{\\text{min}}$ of the plate at which the system transmits a fraction $\\eta = 0.30$ of the luminous flux, given that the specific rotation constant of quartz is $\\alpha = 17^\\circ/\\text{mm}$.",
        "hints": [
            "The first Nicol converts natural light of intensity $I_0$ into linearly polarized light of intensity $I_1 = \\frac{1}{2} I_0$.",
            "The quartz plate cut perpendicular to the optic axis rotates the polarization plane by angle $\\varphi = \\alpha d$.",
            "The second Nicol is crossed at $90^\\circ$, so the transmitted intensity is $I = I_1 \\cos^2(90^\\circ - \\varphi) = \\frac{1}{2} I_0 \\sin^2(\\alpha d)$. Solve $\\frac{1}{2} \\sin^2(\\alpha d) = \\eta$ for $d$."
        ],
        "answer": "$d_{\\text{min}} = \\frac{1}{\\alpha} \\arcsin(\\sqrt{2\\eta}) = 3.0\\text{ mm}$",
        "solution": "**1. Intensity Transmission Through the System:**\n- Natural light of intensity $I_0$ passing through the first Nicol prism becomes linearly polarized with intensity:\n  $$I_1 = \\frac{1}{2} I_0$$\n- The quartz plate, cut perpendicular to the optical axis, rotates the polarization plane by angle $\\varphi = \\alpha d$.\n- The analyzer is crossed relative to the polarizer (transmission axis at $90^\\circ$). The angle between the rotated polarization plane and the analyzer axis is $90^\\circ - \\varphi$.\nBy Malus's law, the transmitted intensity is:\n$$I = I_1 \\cos^2(90^\\circ - \\varphi) = \\frac{1}{2} I_0 \\sin^2(\\alpha d)$$\n\n**2. Solving for Plate Thickness:**\nThe fraction of luminous flux transmitted is $\\eta = I / I_0$:\n$$\\eta = \\frac{1}{2} \\sin^2(\\alpha d) \\implies \\sin^2(\\alpha d) = 2\\eta$$\n$$\\sin(\\alpha d) = \\sqrt{2\\eta}$$\n$$d_{\\text{min}} = \\frac{1}{\\alpha} \\arcsin(\\sqrt{2\\eta})$$\n\n**3. Numerical Evaluation:**\nFor $\\eta = 0.30$ and $\\alpha = 17^\\circ/\\text{mm}$:\n$$2\\eta = 0.60 \\implies \\sqrt{2\\eta} = \\sqrt{0.60} \\approx 0.7746$$\n$$\\arcsin(0.7746) \\approx 50.77^\\circ$$\n$$d_{\\text{min}} = \\frac{50.77^\\circ}{17^\\circ/\\text{mm}} \\approx 2.986\\text{ mm} \\approx 3.0\\text{ mm}$$",
        "tags": ["optical activity", "crossed Nicols", "quartz plate", "specific rotation", "Malus's law"]
    },
    {
        "id": "5.192",
        "title": "Dual-Wavelength Extinction and Transmission by an Optically Active Plate",
        "difficulty": 2,
        "question": "Light passes through a system of two crossed Nicol prisms containing a quartz plate cut perpendicular to its optical axis. Determine the minimum thickness $d$ of the plate that allows light of wavelength $\\lambda_1 = 436\\text{ nm}$ to be completely extinguished by the system, while transmitting maximum possible intensity (half the incident natural light) of wavelength $\\lambda_2 = 497\\text{ nm}$. The specific rotation constants are $\\alpha_1 = 41.5^\\circ/\\text{mm}$ and $\\alpha_2 = 31.1^\\circ/\\text{mm}$.",
        "hints": [
            "For crossed Nicols, complete extinction occurs when the rotation is an integer multiple of $180^\\circ$: $\\alpha_1 d = k \\cdot 180^\\circ$.",
            "Maximum transmission of natural light through crossed Nicols ($I = I_0/2$) occurs when the rotation is an odd multiple of $90^\\circ$: $\\alpha_2 d = (2m + 1) \\cdot 90^\\circ$.",
            "Find the smallest integer $k$ for which $\\alpha_2 d \\approx (2m + 1) \\cdot 90^\\circ$."
        ],
        "answer": "$d = 8.7\\text{ mm}$",
        "solution": "**1. Conditions for Extinction and Maximum Transmission:**\nFor crossed Nicol prisms, the transmitted intensity for natural light is $I = \\frac{1}{2} I_0 \\sin^2(\\alpha d)$:\n- **Complete extinction for $\\lambda_1$:**\n  $$\\sin^2(\\alpha_1 d) = 0 \\implies \\alpha_1 d = k \\cdot 180^\\circ \\quad (k = 1, 2, 3, \\dots)$$\n- **Maximum transmission for $\\lambda_2$:**\n  $$\\sin^2(\\alpha_2 d) = 1 \\implies \\alpha_2 d = (2m + 1) \\cdot 90^\\circ \\quad (m = 0, 1, 2, \\dots)$$\n\n**2. Ratio of Specific Rotations:**\n$$\\frac{\\alpha_1 d}{\\alpha_2 d} = \\frac{\\alpha_1}{\\alpha_2} = \\frac{41.5^\\circ/\\text{mm}}{31.1^\\circ/\\text{mm}} \\approx 1.3344$$\nNotice that $1.3344 \\approx \\frac{4}{3} = \\frac{360^\\circ}{270^\\circ}$.\n\n**3. Evaluation for $k = 2$ and $m = 1$:**\n- For $k = 2$:\n  $$\\alpha_1 d = 2 \\times 180^\\circ = 360^\\circ$$\n  $$d = \\frac{360^\\circ}{41.5^\\circ/\\text{mm}} \\approx 8.675\\text{ mm}$$\n- Checking the angle for $\\lambda_2$:\n  $$\\alpha_2 d = (31.1^\\circ/\\text{mm})(8.675\\text{ mm}) \\approx 269.8^\\circ \\approx 270^\\circ$$\nThis corresponds precisely to $m = 1$ ($(2 \\times 1 + 1) \\times 90^\\circ = 270^\\circ$)!\nThus, $d \\approx 8.7\\text{ mm}$ satisfies both conditions simultaneously.",
        "tags": ["optical activity", "crossed Nicols", "quartz plate", "specific rotation", "wavelength filtering"]
    },
    {
        "id": "5.193",
        "title": "Specific Rotation Constant of a Turbid Sugar Solution from Helical Fringes",
        "difficulty": 2,
        "question": "Plane-polarized light of wavelength $\\lambda = 589\\text{ nm}$ propagates along the axis of a cylindrical glass vessel filled with a slightly turbid sugar solution of concentration $C = 500\\text{ g/L}$. Viewed from the side, a system of helical fringes is observed with pitch $l = 50\\text{ cm}$ between neighbouring dark fringes along the axis. Explain the emergence of the fringes and determine the specific rotation constant $[\\alpha]$ of the solution.",
        "hints": [
            "Molecular Rayleigh scattering in a turbid medium acts as a partial analyzer: light scattered at $90^\\circ$ to the beam has zero intensity when the electric field vector oscillates along the line of sight (dipole radiation pattern).",
            "As the plane-polarized beam propagates along the cylinder, its polarization plane continuously rotates due to optical activity: $\\varphi(z) = [\\alpha] C z$.",
            "The scattered intensity viewed from the side is modulated as $I(z) \\propto \\sin^2\\varphi(z)$. The period between dark fringes is $l = 50\\text{ cm}$, corresponding to $\\Delta\\varphi = 180^\\circ$. Solve for $[\\alpha] = \\frac{180^\\circ}{C l}$."
        ],
        "answer": "$[\\alpha] = \\frac{180^\\circ}{C l} = 72^\\circ / (\\text{dm} \\cdot \\text{g/cm}^3)$",
        "solution": "**1. Physical Mechanism of Helical Fringes:**\nIn a turbid sugar solution, small suspended particles scatter light via Rayleigh scattering.\nAn oscillating electric dipole does not radiate along its axis of oscillation. When viewed from the side (perpendicular to the tube axis):\n- If the electric vector of the beam oscillates along the direction of observation, the scattered intensity is zero (dark fringe).\n- If the electric vector oscillates perpendicular to the direction of observation, the scattered intensity is maximum (bright fringe).\nBecause the sugar solution is optically active, the polarization vector rotates continuously as the beam advances along the axis $z$, forming a spatial helix.\n\n**2. Period of the Fringes:**\nThe dipole radiation pattern has two-fold symmetry ($180^\\circ$), so the observed scattered intensity repeats every time the polarization plane rotates by $\\pi$ ($180^\\circ$):\n$$\\Delta\\varphi = [\\alpha] C l = 180^\\circ$$\nwhere $l = 50\\text{ cm}$ is the distance along the tube between consecutive dark fringes.\n\n**3. Determining Specific Rotation:**\n$$[\\alpha] = \\frac{180^\\circ}{C l}$$\nGiven $C = 500\\text{ g/L} = 0.50\\text{ g/cm}^3$ and $l = 50\\text{ cm} = 5.0\\text{ dm}$:\n$$C l = (0.50\\text{ g/cm}^3)(5.0\\text{ dm}) = 2.50\\text{ dm} \\cdot \\text{g/cm}^3$$\n$$[\\alpha] = \\frac{180^\\circ}{2.50\\text{ dm} \\cdot \\text{g/cm}^3} = 72^\\circ / (\\text{dm} \\cdot \\text{g/cm}^3)$$",
        "tags": ["sugar solution", "Rayleigh scattering", "optical activity", "specific rotation", "helical fringes"]
    },
    {
        "id": "5.194",
        "title": "Kerr Cell Electric Field and Modulation Frequency",
        "difficulty": 3,
        "question": "A Kerr cell is positioned between two crossed Nicol prisms so that the direction of the electric field $\\mathbf{E}$ in the capacitor forms an angle of $45^\\circ$ with the principal directions of the prisms. The capacitor has length $l = 10\\text{ cm}$ and is filled with nitrobenzene. Light of wavelength $\\lambda = 0.50\\,\\mu\\text{m}$ passes through the system. Given that the Kerr constant is $B = 2.2 \\times 10^{-10}\\text{ cm/V}^2$ ($n_e - n_o = B \\lambda E^2$):\n(a) find the minimum electric field strength $E_{\\text{min}}$ at which the intensity of light behind the system is independent of the rotation of the rear prism;\n(b) determine how many times per second light will be completely interrupted when a sinusoidal voltage of frequency $\\nu = 10\\text{ MHz}$ and field amplitude $E_m = 50\\text{ kV/cm}$ is applied to the capacitor.",
        "hints": [
            "(a) Independence of rear prism rotation means the emerging light is circularly polarized, requiring a quarter-wave phase difference $\\delta = \\pi/2$. The Kerr effect gives $\\delta = 2\\pi B l E^2 = \\pi/2 \\implies E_{\\text{min}} = \\frac{1}{\\sqrt{4 B l}}$.",
            "(b) Light is extinguished by the crossed Nicols whenever the total phase retardance is an integer multiple of $2\\pi$: $\\delta(t) = 2 k \\pi$, which occurs at $E^2(t) = \\frac{k}{B l}$.",
            "Calculate how many times $E(t) = E_m \\sin(2\\pi\\nu t)$ crosses each extinction field level during one complete cycle."
        ],
        "answer": "(a) $E_{\\text{min}} = \\frac{1}{2\\sqrt{B l}} = 10.6\\text{ kV/cm}$;\n(b) $2.2 \\times 10^8\\text{ interruptions per second}$",
        "solution": "**1. Kerr Effect and Phase Retardation:**\nIn an electric field $E$, an isotropic substance exhibits induced birefringence:\n$$n_e - n_o = B \\lambda E^2$$\nThe phase difference introduced over length $l$ is:\n$$\\delta = \\frac{2\\pi}{\\lambda} (n_e - n_o) l = 2\\pi B l E^2$$\n\n**2. Part (a): Field for Polarization Invariance:**\nThe light emerging from the Kerr cell will have an intensity independent of the rotation of the analyzer if it is circularly polarized.\nBecause the electric field makes an angle of $45^\\circ$ with the polarizer axis, circular polarization is achieved when the phase retardance is an odd multiple of $\\pi/2$:\n$$\\delta = 2\\pi B l E^2 = \\frac{\\pi}{2} \\implies E_{\\text{min}} = \\frac{1}{\\sqrt{4 B l}} = \\frac{1}{2\\sqrt{B l}}$$\nGiven $B = 2.2 \\times 10^{-10}\\text{ cm/V}^2$ and $l = 10\\text{ cm}$:\n$$B l = 2.2 \\times 10^{-9}\\text{ V}^{-2}$$\n$$E_{\\text{min}} = \\frac{1}{2 \\sqrt{2.2 \\times 10^{-9}}} = \\frac{1}{2 (4.690 \\times 10^{-5})} \\approx 10660\\text{ V/cm} = 10.6\\text{ kV/cm}$$\n\n**3. Part (b): Number of Light Interruptions Per Second:**\nThe applied field is $E(t) = E_m \\sin(\\omega t)$ with $E_m = 50\\text{ kV/cm} = 5.0 \\times 10^4\\text{ V/cm}$ and $\\nu = 10\\text{ MHz}$.\nThe maximum phase difference is:\n$$\\delta_{\\text{max}} = 2\\pi B l E_m^2 = 2\\pi (2.2 \\times 10^{-9}\\text{ V}^{-2})(5.0 \\times 10^4\\text{ V/cm})^2 = 2\\pi (2.2 \\times 10^{-9})(2.5 \\times 10^9) = 2\\pi (5.5) = 11\\pi$$\nBetween crossed Nicols, complete extinction occurs when $\\delta = 2k\\pi$ ($k = 0, 1, 2, \\dots, k_{\\text{max}}$).\nHere $2 k_{\\text{max}} \\le 5.5 \\implies k_{\\text{max}} = 2$ non-zero extinction values ($k = 1, 2$), plus $k = 0$ at zero field.\nDuring each quarter-cycle, as $E(t)$ increases from $0$ to $E_m$, the field crosses extinction values at $k = 0, 1, 2$ (and the peak $\\delta = 5.5\\pi$ does not extinguish).\nOver one full cycle (4 quarter-cycles), the number of interruptions is $4 \\times 5.5 = 22$.\nTherefore, the number of interruptions per second is:\n$$N = 22 \\times \\nu = 22 \\times (10 \\times 10^6\\text{ s}^{-1}) = 2.2 \\times 10^8\\text{ s}^{-1}$$",
        "tags": ["Kerr cell", "Kerr effect", "electro-optics", "nitrobenzene", "optical modulation"]
    },
    {
        "id": "5.195",
        "title": "Circular Birefringence from the Faraday Effect",
        "difficulty": 2,
        "question": "Monochromatic plane-polarized light with angular frequency $\\omega$ passes through a substance along a uniform longitudinal magnetic field $H$. Find the difference of refractive indices $\\Delta n = |n_L - n_R|$ for the right-hand and left-hand circular components of the light beam if the Verdet constant of the substance is $V$.",
        "hints": [
            "According to the Faraday effect, the plane of polarization rotates by angle $\\varphi = V H l$.",
            "In terms of circular birefringence, the rotation of the polarization plane over distance $l$ is $\\varphi = \\frac{\\omega l}{2c} (n_L - n_R) = \\frac{\\omega l \\Delta n}{2c}$.",
            "Equate the two expressions for $\\varphi$ and solve for $\\Delta n = \\frac{2 c V H}{\\omega}$."
        ],
        "answer": "$\\Delta n = \\frac{2 c V H}{\\omega}$",
        "solution": "**1. Faraday Rotation Law:**\nWhen plane-polarized light passes through a magneto-active medium of length $l$ in a magnetic field $H$, the plane of polarization rotates by:\n$$\\varphi = V H l$$\nwhere $V$ is the Verdet constant of the material.\n\n**2. Relation to Circular Birefringence:**\nThe incident linearly polarized wave is composed of left- and right-circularly polarized modes with refractive indices $n_L$ and $n_R$.\nThe phase difference accumulated between these two modes over path length $l$ is:\n$$\\Delta\\phi = \\frac{\\omega l}{c} (n_L - n_R)$$\nThis relative phase delay results in a rotation of the resultant plane of polarization by:\n$$\\varphi = \\frac{\\Delta\\phi}{2} = \\frac{\\omega l}{2c} \\Delta n$$\nwhere $\\Delta n = |n_L - n_R|$.\n\n**3. Equating Both Expressions:**\n$$\\frac{\\omega l}{2c} \\Delta n = V H l$$\n$$\\Delta n = \\frac{2 c V H}{\\omega}$$\nThis direct relation links the macroscopic Faraday Verdet constant to the microscopic difference in circular refractive indices.",
        "tags": ["Faraday effect", "Verdet constant", "magnetic circular birefringence", "magneto-optics"]
    },
    {
        "id": "5.196",
        "title": "Determination of Verdet Constant in the Presence of Natural Optical Activity",
        "difficulty": 2,
        "question": "A substance is placed in a longitudinal magnetic field of a solenoid located between two Polaroids. The length of the tube with the substance is $l = 30\\text{ cm}$. Find the Verdet constant $V$ if, at a field strength $H = 56.5\\text{ kA/m}$, the angle of rotation of the polarization plane is $\\varphi_1 = +5^\\circ 10'$ for one direction of the field and $\\varphi_2 = -3^\\circ 20'$ for the opposite direction.",
        "hints": [
            "The substance possesses both natural optical rotation $\\varphi_{\\text{nat}}$ and magnetic Faraday rotation $\\varphi_{\\text{magn}} = V H l$.",
            "When the magnetic field is reversed, the magnetic rotation changes sign while natural optical activity does not: $\\varphi_1 = \\varphi_{\\text{nat}} + V H l$ and $\\varphi_2 = \\varphi_{\\text{nat}} - V H l$.",
            "Subtract the two angles: $\\varphi_1 - \\varphi_2 = 2 V H l$, and solve for $V = \\frac{\\varphi_1 - \\varphi_2}{2 H l}$."
        ],
        "answer": "$V = \\frac{\\varphi_1 - \\varphi_2}{2 H l} = 0.015\\text{ arcmin/A}$",
        "solution": "**1. Superposition of Natural and Magnetic Rotations:**\nLet $\\varphi_{\\text{nat}}$ be the natural optical rotation of the substance, and $\\varphi_{\\text{magn}} = V H l$ be the magnetic rotation produced by the Faraday effect.\n- For the first direction of the magnetic field:\n  $$\\varphi_1 = \\varphi_{\\text{nat}} + V H l$$\n- For the reversed magnetic field:\n  $$\\varphi_2 = \\varphi_{\\text{nat}} - V H l$$\n\n**2. Isolating the Faraday Component:**\nSubtracting the two equations eliminates the natural rotation:\n$$\\varphi_1 - \\varphi_2 = 2 V H l \\implies V = \\frac{\\varphi_1 - \\varphi_2}{2 H l}$$\n\n**3. Numerical Evaluation:**\nGiven $l = 30\\text{ cm} = 0.30\\text{ m}$, $H = 56.5\\text{ kA/m} = 5.65 \\times 10^4\\text{ A/m}$, $\\varphi_1 = +5^\\circ 10' = 310'$, and $\\varphi_2 = -3^\\circ 20' = -200'$:\n$$\\varphi_1 - \\varphi_2 = 310' - (-200') = 510'$$\n$$2 H l = 2 (5.65 \\times 10^4\\text{ A/m})(0.30\\text{ m}) = 3.39 \\times 10^4\\text{ A}$$\n$$V = \\frac{510'}{3.39 \\times 10^4\\text{ A}} \\approx 0.01504'\\text{/A} \\approx 0.015\\text{ arcmin/A}$$",
        "tags": ["Faraday effect", "Verdet constant", "natural optical activity", "magnetic field", "solenoid"]
    },
    {
        "id": "5.197",
        "title": "Combined Natural and Magnetic Optical Rotation for Multiple Passes",
        "difficulty": 2,
        "question": "A narrow beam of plane-polarized light passes through a dextrorotatory compound placed in a longitudinal magnetic field $H$. The beam is reflected back and forth through the tube of length $l$ so that it traverses the substance $N$ times. Find the total angle $\\varphi$ through which the polarization plane turns if the specific rotation constant is $\\alpha$ and the Verdet constant is $V$.",
        "hints": [
            "Consider the reciprocal nature of natural rotation vs the non-reciprocal nature of Faraday rotation.",
            "Upon reflection, the beam reverses direction. Natural rotation is reciprocal: the rotation reverses sign relative to the forward direction with each reflection, leaving a net rotation $\\alpha l$ for an odd number of passes ($N = 1, 3, 5, \\dots$).",
            "Magnetic Faraday rotation is non-reciprocal: it depends only on the orientation relative to the magnetic field vector $\\mathbf{H}$, accumulating continuously across all $N$ passes as $V N H l$."
        ],
        "answer": "$\\varphi = (\\alpha - V N H) l$ (for $N$ passes)",
        "solution": "**1. Reciprocal vs Non-Reciprocal Rotation:**\n- **Natural optical activity:**\n  Natural rotation is governed by the structural chirality of molecules. When a beam reflects and propagates backward along its path, the rotation unwinds relative to the fixed laboratory axis. For $N$ passes ($N$ being odd, e.g. $N = 5$ with four reflections):\n  $$\\varphi_{\\text{nat}} = [1 - 1 + 1 - 1 + \\dots] \\alpha l = \\alpha l$$\n- **Magnetic Faraday rotation:**\n  Faraday rotation is non-reciprocal. The direction of rotation is determined strictly by the magnetic field vector $\\mathbf{H}$, regardless of the beam's propagation direction. Upon reflection, both the wave vector and the relative rotation accumulate in the same absolute sense:\n  $$\\varphi_{\\text{magn}} = -N V H l$$\n\n**2. Total Rotation Angle:**\nTaking clockwise rotation looking toward the transmitted beam as positive:\n$$\\varphi = (\\alpha - V N H) l$$\nFor $N = 5$ passes through the tube:\n$$\\varphi = (\\alpha - 5 V H) l$$",
        "tags": ["Faraday effect", "optical activity", "non-reciprocity", "multiple reflections", "polarization rotation"]
    },
    {
        "id": "5.198",
        "title": "Magnetic Optical Isolator (Optical Valve) Threshold Field",
        "difficulty": 2,
        "question": "A tube of length $l = 26\\text{ cm}$ is filled with benzene and placed in the longitudinal magnetic field of a solenoid positioned between two Polaroids whose principal transmission planes form an angle of $45^\\circ$. Find the minimum magnetic field strength $H_{\\text{min}}$ at which light of wavelength $\\lambda = 589\\text{ nm}$ propagates through the system in one direction only (optical valve/isolator). What happens if the direction of the magnetic field is reversed?",
        "hints": [
            "An optical isolator transmits light in the forward direction and extinguishes reflected light propagating in reverse.",
            "For forward transmission, the Faraday rotation must rotate the polarization plane by $45^\\circ$ to align with the second Polaroid: $\\varphi = V H l = \\pi/4$.",
            "Light traveling in reverse rotates by another $45^\\circ$ in the same sense, making a total rotation of $90^\\circ$ relative to the first Polaroid, causing total extinction. Reverse the field to switch the allowed transmission direction."
        ],
        "answer": "$H_{\\text{min}} = \\frac{\\pi}{4 V l} = 4.0\\text{ kA/m}$; reversing the field reverses the allowed transmission direction",
        "solution": "**1. Principle of the Optical Isolator (Optical Valve):**\n- **Forward pass:** Light polarized by Polaroid 1 enters the Faraday rotator and its polarization plane is rotated by angle $\\varphi = V H l$.\n  If $\\varphi = 45^\\circ$, its polarization matches the transmission axis of Polaroid 2 (oriented at $45^\\circ$), transmitting light with zero loss.\n- **Backward pass:** Any reflected light entering from the right is polarized at $45^\\circ$ by Polaroid 2.\n  Because Faraday rotation is non-reciprocal, traversing the magnetic field in the reverse direction rotates the polarization by another $+45^\\circ$ in the laboratory frame, making the total angle $45^\\circ + 45^\\circ = 90^\\circ$.\n  This makes the light perpendicular to Polaroid 1, resulting in complete extinction.\n\n**2. Minimum Magnetic Field Strength:**\n$$\\varphi = V H_{\\text{min}} l = \\frac{\\pi}{4} \\implies H_{\\text{min}} = \\frac{\\pi}{4 V l}$$\nFor benzene at $\\lambda = 589\\text{ nm}$, the Verdet constant is $V \\approx 0.0297'\\text{/(A)} \\approx 7.55 \\times 10^{-4}\\text{ rad/A}$ (or $V = 1.09 \\times 10^{-2}\\text{ rad/(T m)}$):\n$$H_{\\text{min}} = \\frac{\\pi / 4}{(7.55 \\times 10^{-4}\\text{ rad/A})(0.26\\text{ m})} \\approx \\frac{0.7854}{1.963 \\times 10^{-4}} \\approx 4000\\text{ A/m} = 4.0\\text{ kA/m}$$\n\n**3. Reversal of Magnetic Field:**\nIf the magnetic field $\\mathbf{H}$ is reversed, the sign of the Faraday rotation flips to $-45^\\circ$.\nAs a result, forward-traveling light is rotated to $-45^\\circ$ (perpendicular to Polaroid 2) and blocked, while backward-traveling light is transmitted.\nThe allowed transmission direction reverses.",
        "tags": ["optical isolator", "optical valve", "Faraday effect", "Verdet constant", "non-reciprocal optics"]
    },
    {
        "id": "5.199",
        "title": "Angular Acceleration of a Disc Absorbing Circularly Polarized Light",
        "difficulty": 2,
        "question": "A beam of circularly polarized light with wavelength $\\lambda = 0.70\\,\\mu\\text{m}$ and intensity $I = 10\\text{ W/cm}^2$ falls normally on a uniform black disc of mass $m = 10\\text{ mg}$ that can freely rotate about its symmetry axis. The flow density of angular momentum in circularly polarized light in vacuum is $M = I / \\omega$, where $\\omega$ is the angular frequency. How long will it take for the disc's angular velocity to reach $\\omega_0 = 1.0\\text{ rad/s}$?",
        "hints": [
            "The torque exerted on a fully absorbing surface of area $S = \\pi R^2$ is $\\tau = M S = \\frac{I S}{\\omega}$.",
            "The moment of inertia of a uniform disc of mass $m$ and radius $R$ is $J = \\frac{1}{2} m R^2$.",
            "Calculate the angular acceleration $\\beta = \\frac{\\tau}{J} = \\frac{I \\pi R^2 / \\omega}{\\frac{1}{2} m R^2} = \\frac{2 \\pi I}{m \\omega} = \\frac{\\lambda I}{m c}$. Then $t = \\frac{\\omega_0}{\\beta} = \\frac{m c \\omega_0}{\\lambda I}$."
        ],
        "answer": "$t = \\frac{m c \\omega_0}{\\lambda I} \\approx 12\\text{ hours}$",
        "solution": "**1. Angular Momentum Flux and Torque on the Disc:**\nCircularly polarized photons of energy $\\hbar\\omega$ carry spin angular momentum $\\pm \\hbar$.\nThe angular momentum flux density of the beam is:\n$$M = \\frac{I}{\\omega}$$\nWhen the light falls normally on a completely absorbing (black) disc of radius $R$ and area $S = \\pi R^2$, all absorbed photons transfer their angular momentum to the disc.\nThe total torque acting on the disc is:\n$$\\tau = M S = \\frac{I S}{\\omega} = \\frac{I \\pi R^2}{\\omega}$$\n\n**2. Equation of Rotational Motion:**\nThe moment of inertia of a uniform disc of mass $m$ and radius $R$ is:\n$$J = \\frac{1}{2} m R^2$$\nThe angular acceleration of the disc is:\n$$\\beta = \\frac{\\tau}{J} = \\frac{I \\pi R^2 / \\omega}{\\frac{1}{2} m R^2} = \\frac{2 \\pi I}{m \\omega}$$\nSince $\\omega = \\frac{2\\pi c}{\\lambda}$, we have $\\frac{2\\pi}{\\omega} = \\frac{\\lambda}{c}$, so:\n$$\\beta = \\frac{\\lambda I}{m c}$$\nNotice that the radius $R$ cancels out completely!\n\n**3. Time to Reach Angular Velocity $\\omega_0$:**\n$$t = \\frac{\\omega_0}{\\beta} = \\frac{m c \\omega_0}{\\lambda I}$$\n\n**4. Numerical Evaluation:**\nGiven $m = 10\\text{ mg} = 1.0 \\times 10^{-5}\\text{ kg}$, $c = 3.0 \\times 10^8\\text{ m/s}$, $\\omega_0 = 1.0\\text{ rad/s}$, $\\lambda = 0.70\\,\\mu\\text{m} = 7.0 \\times 10^{-7}\\text{ m}$, and $I = 10\\text{ W/cm}^2 = 1.0 \\times 10^5\\text{ W/m}^2$:\n$$t = \\frac{(1.0 \\times 10^{-5}\\text{ kg})(3.0 \\times 10^8\\text{ m/s})(1.0\\text{ rad/s})}{(7.0 \\times 10^{-7}\\text{ m})(1.0 \\times 10^5\\text{ W/m}^2)}$$\n$$t = \\frac{3.0 \\times 10^3}{7.0 \\times 10^{-2}} = \\frac{3000}{0.070} \\approx 42857\\text{ s}$$\nConverting to hours:\n$$t = \\frac{42857}{3600}\\text{ hours} \\approx 11.9\\text{ hours} \\approx 12\\text{ hours}$$",
        "tags": ["angular momentum of light", "photon spin", "circular polarization", "radiation torque", "Beth experiment"]
    }
]
