"""
part5_ch5_4a.py
Curated problems 5.157 to 5.178 (22 problems) of Irodov Chapter 5.4:
Polarization of Light (Part A: Polarization, Malus's Law, Brewster's Law, Fresnel Equations, Birefringence).
"""

CH5_4A_CURATED = [
    {
        "id": "5.157",
        "title": "Diffraction Pattern Behind Two Touching Polaroid Half-Planes",
        "difficulty": 2,
        "question": "A plane monochromatic wave of natural light with intensity $I_0$ falls normally on a screen composed of two touching Polaroid half-planes. The principal direction of one Polaroid is parallel, and of the other perpendicular, to the boundary between them. What kind of diffraction pattern is formed behind the screen? What is the intensity of light behind the screen at the points of the plane perpendicular to the screen and passing through the boundary between the Polaroids?",
        "hints": [
            "Natural (unpolarized) light can be represented as two independent, mutually incoherent orthogonal linearly polarized components of equal intensity $I_0 / 2$.",
            "Choose the coordinate axes along the principal directions of the two Polaroids. Each Polaroid transmits only the polarization component parallel to its transmission axis.",
            "At any point on the plane of symmetry passing through the dividing line, each half-plane acts as a straight-edge knife screen for its respective transmitted component, yielding an intensity $I = \\frac{1}{4} (I_0/2) + \\frac{1}{4} (I_0/2) = I_0 / 4$."
        ],
        "answer": "$I = \\frac{I_0}{4}$ at the symmetry plane; diffraction fringes with no interference between the two orthogonal polarizations",
        "solution": "**1. Decomposition of Natural Incident Light:**\nNatural light of intensity $I_0$ consists of two mutually incoherent orthogonal linearly polarized components of equal intensity:\n$$I_x = I_y = \\frac{I_0}{2}$$\nLet the boundary between the two Polaroids lie along the $y$-axis.\n- The left half-plane ($x < 0$) is a Polaroid with transmission axis parallel to the boundary ($y$-axis).\n- The right half-plane ($x > 0$) is a Polaroid with transmission axis perpendicular to the boundary ($x$-axis).\n\n**2. Nature of the Diffraction Pattern:**\nThe left Polaroid transmits only the $y$-polarized component, while the right Polaroid transmits only the $x$-polarized component.\nBecause the $x$- and $y$-polarized waves are mutually orthogonal, they cannot interfere with each other. Therefore, the total intensity at any point behind the screen is the simple sum of the two independent diffraction intensities:\n$$I(x, y, z) = I_x(x, z) + I_y(x, z)$$\nEach component undergoes straight-edge (knife-edge) Fresnel diffraction from its respective half-plane aperture.\n\n**3. Intensity on the Plane of Symmetry:**\nOn the plane passing through the boundary ($x = 0$):\nFor straight-edge Fresnel diffraction, the complex amplitude at the geometric shadow boundary is half of the unobstructed amplitude:\n$$E = \\frac{E_{\\text{inc}}}{2} \\implies I = \\frac{I_{\\text{inc}}}{4}$$\nApplying this to each transmitted component:\n- Contribution from the left Polaroid: $I_y(0) = \\frac{1}{4} \\left(\\frac{I_0}{2}\\right) = \\frac{I_0}{8}$\n- Contribution from the right Polaroid: $I_x(0) = \\frac{1}{4} \\left(\\frac{I_0}{2}\\right) = \\frac{I_0}{8}$\nAdding the two orthogonal, incoherent intensities:\n$$I = \\frac{I_0}{8} + \\frac{I_0}{8} = \\frac{I_0}{4}$$",
        "tags": ["polarization", "Polaroid", "straight edge", "Fresnel diffraction", "unpolarized light"]
    },
    {
        "id": "5.158",
        "title": "First Fresnel Zone Covered by Orthogonal Polaroids",
        "difficulty": 2,
        "question": "A plane monochromatic wave of natural light with intensity $I_0$ falls normally on an opaque screen with a round hole corresponding to the first Fresnel zone for an on-axis observation point $P$. Find the intensity of light at point $P$ after the hole is covered with two identical Polaroids whose principal directions are mutually perpendicular and the boundary between them passes:\n(a) along a diameter of the hole;\n(b) along the circumference of the circle limiting the first half (by area) of the Fresnel zone.",
        "hints": [
            "Decompose the natural incident light into two mutually incoherent orthogonal linear polarization components, each of intensity $I_0 / 2$.",
            "(a) When split along the diameter, each half-disk transmits one polarization component. The amplitude from half of the first Fresnel zone for one polarization is $E_1 / 2 = E_0$. Sum the intensities of the two orthogonal components.",
            "(b) When split into inner and outer concentric subzones, the inner half-zone (phases $0$ to $\\pi/2$) transmits one component and the outer half-zone (phases $\\pi/2$ to $\\pi$) transmits the other component. Since they have orthogonal polarizations, they do not destructively interfere."
        ],
        "answer": "(a) $I = I_0$;\n(b) $I = 2 I_0$",
        "solution": "**1. Part (a): Boundary Along the Diameter:**\nAn unobstructed first Fresnel zone creates an on-axis amplitude $A_1 = 2 E_0$, where $E_0$ is the amplitude of the unobstructed incident wave ($I_0 = E_0^2$).\nNatural light consists of two incoherent orthogonal polarizations ($x$ and $y$), each carrying intensity $I_0 / 2$ with incident amplitude $E_0 / \\sqrt{2}$.\nDividing the aperture along a diameter into two equal semicircles:\n- The first semicircle transmits the $x$-component. Its amplitude is half that of a full zone: $A_x = \\frac{1}{2} (2 E_{0,x}) = E_{0,x} = \\frac{E_0}{\\sqrt{2}}$.\n- The second semicircle transmits the $y$-component: $A_y = \\frac{1}{2} (2 E_{0,y}) = E_{0,y} = \\frac{E_0}{\\sqrt{2}}$.\nSince the two polarizations are mutually perpendicular, their intensities add:\n$$I = A_x^2 + A_y^2 = \\left(\\frac{E_0}{\\sqrt{2}}\\right)^2 + \\left(\\frac{E_0}{\\sqrt{2}}\\right)^2 = E_0^2 = I_0$$\n\n**2. Part (b): Boundary Along Concentric Subzones:**\nThe first Fresnel zone covers phase angles from $\\phi = 0$ to $\\pi$.\n- Inner circle (half-area): covers phases $0 \\le \\phi \\le \\pi/2$. Its complex amplitude vector for the transmitted $x$-component is:\n  $$E_x = \\int_0^{\\pi/2} e^{i\\phi} d\\phi = [-i e^{i\\phi}]_0^{\\pi/2} = 1 + i$$\n  $$|E_x|^2 = 1^2 + 1^2 = 2$$\n- Outer ring (half-area): covers phases $\\pi/2 \\le \\phi \\le \\pi$. Its complex amplitude vector for the transmitted $y$-component is:\n  $$E_y = \\int_{\\pi/2}^\\pi e^{i\\phi} d\\phi = -1 + i$$\n  $$|E_y|^2 = (-1)^2 + 1^2 = 2$$\nIn units where an unobstructed wave gives intensity $I_0/2$ per polarization:\n$$I_x = 2 \\left(\\frac{I_0}{2}\\right) = I_0, \\quad I_y = 2 \\left(\\frac{I_0}{2}\\right) = I_0$$\nSince the two components are mutually orthogonal, they cannot interfere destructively:\n$$I = I_x + I_y = I_0 + I_0 = 2 I_0$$",
        "tags": ["Fresnel zones", "circular aperture", "orthogonal polaroids", "birefringence", "intensity"]
    },
    {
        "id": "5.159",
        "title": "Energy Transmitted Through a Rotating Polarizer",
        "difficulty": 1,
        "question": "A beam of plane-polarized light falls on a polarizer which rotates about the axis of the ray with angular velocity $\\omega = 21\\text{ rad/s}$. Find the energy of light passing through the polarizer per one revolution if the flux of energy of the incident ray is $\\Phi_0 = 4.0\\text{ mW}$.",
        "hints": [
            "Use Malus's law for the instantaneous transmitted power: $\\Phi(t) = \\Phi_0 \\cos^2(\\omega t)$.",
            "The period of one full revolution of the polarizer is $T = \\frac{2\\pi}{\\omega}$.",
            "Integrate the transmitted flux over one period: $E = \\int_0^T \\Phi(t) dt = \\Phi_0 \\int_0^{2\\pi/\\omega} \\cos^2(\\omega t) dt$."
        ],
        "answer": "$E = \\frac{\\pi \\Phi_0}{\\omega} = 0.60\\text{ mJ}$",
        "solution": "**1. Instantaneous Transmitted Luminous Flux:**\nAccording to Malus's law, when plane-polarized light of power $\\Phi_0$ passes through a polarizer whose transmission axis makes an angle $\\theta(t) = \\omega t$ with the polarization plane:\n$$\\Phi(t) = \\Phi_0 \\cos^2(\\omega t)$$\n\n**2. Energy per Revolution:**\nThe time taken for one full revolution ($2\\pi$ radians) is $T = \\frac{2\\pi}{\\omega}$.\nThe total energy transmitted during one revolution is:\n$$E = \\int_0^T \\Phi(t) \\, dt = \\Phi_0 \\int_0^{2\\pi/\\omega} \\cos^2(\\omega t) \\, dt$$\nUsing the identity $\\cos^2(\\omega t) = \\frac{1 + \\cos(2\\omega t)}{2}$:\n$$E = \\Phi_0 \\left[ \\frac{t}{2} + \\frac{\\sin(2\\omega t)}{4\\omega} \\right]_0^{2\\pi/\\omega} = \\Phi_0 \\left( \\frac{\\pi}{\\omega} + 0 \\right) = \\frac{\\pi \\Phi_0}{\\omega}$$\n\n**3. Numerical Evaluation:**\nGiven $\\Phi_0 = 4.0\\text{ mW} = 4.0 \\times 10^{-3}\\text{ W}$ and $\\omega = 21\\text{ rad/s}$:\n$$E = \\frac{\\pi \\times (4.0 \\times 10^{-3}\\text{ W})}{21\\text{ s}^{-1}} = \\frac{4.0 \\pi}{21} \\times 10^{-3}\\text{ J} \\approx \\frac{12.566}{21} \\times 10^{-3}\\text{ J} \\approx 0.598 \\times 10^{-3}\\text{ J} \\approx 0.60\\text{ mJ}$$",
        "tags": ["Malus's law", "rotating polarizer", "energy flux", "polarization"]
    },
    {
        "id": "5.160",
        "title": "Transmission Through a System of N Turned Nicol Prisms",
        "difficulty": 1,
        "question": "A beam of natural light falls on a system of $N = 6$ Nicol prisms whose transmission planes are each turned through an angle $\\varphi = 30^\\circ$ with respect to that of the preceding prism. What fraction $\\eta$ of luminous flux passes through this system?",
        "hints": [
            "The first Nicol prism converts natural light of intensity $I_0$ into linearly polarized light of intensity $I_1 = \\frac{1}{2} I_0$.",
            "Each of the subsequent $N - 1$ Nicol prisms is rotated by angle $\\varphi$ relative to the preceding one, multiplying the intensity by $\\cos^2\\varphi$ according to Malus's law.",
            "The overall transmission fraction is $\\eta = \\frac{1}{2} (\\cos^2\\varphi)^{N - 1} = \\frac{1}{2} \\cos^{2(N-1)}\\varphi$."
        ],
        "answer": "$\\eta = \\frac{1}{2} \\cos^{2(N-1)}\\varphi = 0.12$",
        "solution": "**1. Transmission Formula:**\n- The first Nicol prism receives unpolarized (natural) light and transmits linearly polarized light with intensity:\n  $$I_1 = \\frac{1}{2} I_0$$\n- There are $N - 1$ subsequent interfaces between successive prisms. At each stage, the polarization direction is rotated by angle $\\varphi = 30^\\circ$, attenuating the intensity by a factor of $\\cos^2\\varphi$ (by Malus's law):\n  $$I_N = I_1 (\\cos^2\\varphi)^{N-1} = \\frac{1}{2} I_0 \\cos^{2(N-1)}\\varphi$$\n\n**2. Fraction of Luminous Flux Transmitted:**\n$$\\eta = \\frac{I_N}{I_0} = \\frac{1}{2} \\cos^{2(N-1)}\\varphi$$\n\n**3. Numerical Evaluation:**\nFor $N = 6$ and $\\varphi = 30^\\circ$ ($N - 1 = 5$):\n$$\\cos 30^\\circ = \\frac{\\sqrt{3}}{2} \\implies \\cos^2 30^\\circ = \\frac{3}{4} = 0.75$$\n$$\\eta = \\frac{1}{2} \\left(\\frac{3}{4}\\right)^5 = \\frac{1}{2} \\times \\frac{243}{1024} = \\frac{243}{2048} \\approx 0.1187 \\approx 0.12$$",
        "tags": ["Nicol prism", "Malus's law", "polarization cascade", "natural light"]
    },
    {
        "id": "5.161",
        "title": "Intensity Attenuation in a System of Three Imperfect Polaroids",
        "difficulty": 2,
        "question": "Natural light falls on a system of three identical in-line Polaroids, the principal direction of the middle Polaroid forming an angle $\\varphi = 60^\\circ$ with those of the two other parallel Polaroids. The maximum transmission coefficient of each Polaroid is $\\tau = 0.81$ when plane-polarized light falls on it. How many times will the intensity of light decrease after passing through the system?",
        "hints": [
            "Natural light passing through the first Polaroid has intensity $I_1 = \\frac{1}{2} \\tau I_0$.",
            "Passing through the middle Polaroid rotated by $\\varphi = 60^\\circ$ gives $I_2 = I_1 \\tau \\cos^2\\varphi$.",
            "Passing through the third Polaroid (rotated by $\\varphi = 60^\\circ$ relative to the middle Polaroid) gives $I_3 = I_2 \\tau \\cos^2\\varphi = \\frac{1}{2} I_0 \\tau^3 \\cos^4\\varphi$. Find the ratio $I_0 / I_3$."
        ],
        "answer": "$\\frac{I_0}{I_3} = \\frac{2}{\\tau^3 \\cos^4\\varphi} \\approx 60$",
        "solution": "**1. Step-by-Step Intensity Transmission:**\n- **First Polaroid:**\n  Natural light of intensity $I_0$ can be regarded as two independent equal components. The first Polaroid transmits only the parallel component with transmission factor $\\tau$:\n  $$I_1 = \\frac{1}{2} \\tau I_0$$\n- **Second Polaroid (rotated by $\\varphi = 60^\\circ$):**\n  The incident light is linearly polarized along the axis of the first Polaroid. By Malus's law with transmission factor $\\tau$:\n  $$I_2 = \\tau I_1 \\cos^2\\varphi = \\frac{1}{2} \\tau^2 I_0 \\cos^2\\varphi$$\n- **Third Polaroid (parallel to the first):**\n  The angle between the second and third Polaroids is also $\\varphi = 60^\\circ$:\n  $$I_3 = \\tau I_2 \\cos^2\\varphi = \\frac{1}{2} \\tau^3 I_0 \\cos^4\\varphi$$\n\n**2. Attenuation Factor:**\n$$\\frac{I_0}{I_3} = \\frac{2}{\\tau^3 \\cos^4\\varphi}$$\n\n**3. Numerical Evaluation:**\nGiven $\\tau = 0.81$ and $\\varphi = 60^\\circ$ (so $\\cos 60^\\circ = 0.5$, $\\cos^4 60^\\circ = 0.0625 = 1/16$):\n$$\\tau^3 = (0.81)^3 = 0.531441$$\n$$\\frac{I_0}{I_3} = \\frac{2}{0.531441 \\times (1/16)} = \\frac{32}{0.531441} \\approx 60.2 \\approx 60$$",
        "tags": ["Polaroids", "Malus's law", "transmission coefficient", "polarization"]
    },
    {
        "id": "5.162",
        "title": "Ratio of Polarized and Natural Components in Partially Polarized Light",
        "difficulty": 1,
        "question": "The degree of polarization of partially polarized light is $P = 0.25$. Find the ratio of intensities of the polarized component $I_p$ and the natural (unpolarized) component $I_n$ of this light.",
        "hints": [
            "Partially polarized light can be viewed as an incoherent mixture of completely unpolarized light of intensity $I_n$ and completely linearly polarized light of intensity $I_p$.",
            "The maximum and minimum intensities transmitted by a rotating analyzer are $I_{\\text{max}} = I_p + \\frac{1}{2} I_n$ and $I_{\\text{min}} = \\frac{1}{2} I_n$.",
            "The degree of polarization is $P = \\frac{I_{\\text{max}} - I_{\\text{min}}}{I_{\\text{max}} + I_{\\text{min}}} = \\frac{I_p}{I_p + I_n}$. Solve for $I_p / I_n$."
        ],
        "answer": "$\\frac{I_p}{I_n} = \\frac{P}{1 - P} = \\frac{1}{3} \\approx 0.33$",
        "solution": "**1. Definition of Degree of Polarization:**\nPartially polarized light consists of a completely linearly polarized component of intensity $I_p$ and an unpolarized (natural) component of intensity $I_n$.\nWhen transmitted through an analyzer:\n- The natural light always transmits half its intensity: $I_{n,\\text{trans}} = \\frac{1}{2} I_n$.\n- The linearly polarized component transmits according to Malus's law: $I_{p,\\text{trans}} = I_p \\cos^2\\theta$.\nThus, the extreme intensities observed upon rotating the analyzer are:\n$$I_{\\text{max}} = I_p + \\frac{1}{2} I_n$$\n$$I_{\\text{min}} = \\frac{1}{2} I_n$$\n\n**2. Expressing $P$ in terms of $I_p$ and $I_n$:**\n$$P = \\frac{I_{\\text{max}} - I_{\\text{min}}}{I_{\\text{max}} + I_{\\text{min}}} = \\frac{I_p}{I_p + I_n}$$\n\n**3. Ratio of Intensities:**\nRearranging for $I_p / I_n$:\n$$P (I_p + I_n) = I_p \\implies P I_n = I_p (1 - P)$$\n$$\\frac{I_p}{I_n} = \\frac{P}{1 - P}$$\nFor $P = 0.25$:\n$$\\frac{I_p}{I_n} = \\frac{0.25}{1 - 0.25} = \\frac{0.25}{0.75} = \\frac{1}{3} \\approx 0.33$$",
        "tags": ["degree of polarization", "partially polarized light", "natural light", "analyzer"]
    },
    {
        "id": "5.163",
        "title": "Degree of Polarization from Analyzer Rotation",
        "difficulty": 2,
        "question": "A Nicol prism is placed in the path of a partially polarized beam of light. When the prism is turned from the position of maximum transmission through an angle $\\varphi = 60^\\circ$, the intensity of transmitted light decreases by a factor of $\\eta = 3.0$. Find the degree of polarization $P$ of the incident light.",
        "hints": [
            "The transmitted intensity as a function of angle $\\varphi$ from the transmission maximum is $I(\\varphi) = I_{\\text{min}} + (I_{\\text{max}} - I_{\\text{min}}) \\cos^2\\varphi$.",
            "At $\\varphi = 0$, $I(0) = I_{\\text{max}}$. The given condition is $I(0) / I(\\varphi) = \\eta$.",
            "Express the ratio $I_{\\text{min}} / I_{\\text{max}}$ in terms of $\\eta$ and $\\varphi$, and then find $P = \\frac{I_{\\text{max}} - I_{\\text{min}}}{I_{\\text{max}} + I_{\\text{min}}} = \\frac{\\eta - 1}{\\eta - 1 + 2\\sin^2\\varphi} = \\frac{\\eta - 1}{\\eta - \\cos 2\\varphi}$."
        ],
        "answer": "$P = \\frac{\\eta - 1}{\\eta - 1 + 2\\sin^2\\varphi} = 0.80$",
        "solution": "**1. Transmitted Intensity Distribution:**\nFor partially polarized light with principal intensities $I_{\\text{max}}$ and $I_{\\text{min}}$, the intensity transmitted by a polarizer oriented at angle $\\varphi$ relative to the position of maximum transmission is:\n$$I(\\varphi) = I_{\\text{min}} + (I_{\\text{max}} - I_{\\text{min}}) \\cos^2\\varphi$$\nAt $\\varphi = 0$:\n$$I(0) = I_{\\text{max}}$$\n\n**2. Ratio of Intensities:**\nGiven that $I(0) / I(\\varphi) = \\eta$:\n$$I_{\\text{max}} = \\eta [I_{\\text{min}} + (I_{\\text{max}} - I_{\\text{min}}) \\cos^2\\varphi]$$\nDividing by $I_{\\text{max}}$ and using $r = I_{\\text{min}} / I_{\\text{max}}$:\n$$1 = \\eta [r + (1 - r) \\cos^2\\varphi] = \\eta [\\cos^2\\varphi + r (1 - \\cos^2\\varphi)] = \\eta [\\cos^2\\varphi + r \\sin^2\\varphi]$$\n$$\\frac{1}{\\eta} - \\cos^2\\varphi = r \\sin^2\\varphi \\implies r = \\frac{1 - \\eta \\cos^2\\varphi}{\\eta \\sin^2\\varphi}$$\n\n**3. Degree of Polarization:**\n$$P = \\frac{I_{\\text{max}} - I_{\\text{min}}}{I_{\\text{max}} + I_{\\text{min}}} = \\frac{1 - r}{1 + r}$$\nSubstituting $r$:\n$$1 - r = \\frac{\\eta \\sin^2\\varphi - (1 - \\eta \\cos^2\\varphi)}{\\eta \\sin^2\\varphi} = \\frac{\\eta(\\sin^2\\varphi + \\cos^2\\varphi) - 1}{\\eta \\sin^2\\varphi} = \\frac{\\eta - 1}{\\eta \\sin^2\\varphi}$$\n$$1 + r = \\frac{\\eta \\sin^2\\varphi + 1 - \\eta \\cos^2\\varphi}{\\eta \\sin^2\\varphi} = \\frac{1 - \\eta(\\cos^2\\varphi - \\sin^2\\varphi)}{\\eta \\sin^2\\varphi} = \\frac{1 - \\eta \\cos 2\\varphi}{\\eta \\sin^2\\varphi}$$\nTherefore:\n$$P = \\frac{\\eta - 1}{1 - \\eta \\cos 2\\varphi} = \\frac{\\eta - 1}{\\eta - 1 + 2\\sin^2\\varphi}$$\n\n**4. Numerical Evaluation:**\nFor $\\eta = 3.0$ and $\\varphi = 60^\\circ$ ($\\sin^2 60^\\circ = 3/4 = 0.75$):\n$$P = \\frac{3.0 - 1}{3.0 - 1 + 2(0.75)} = \\frac{2}{2 + 1.5} = \\frac{2}{3.5} = \\frac{4}{7} \\dots$$\nWait, using $\\cos 2(60^\\circ) = \\cos 120^\\circ = -0.5$:\n$$1 - \\eta \\cos 2\\varphi = 1 - 3.0(-0.5) = 1 + 1.5 = 2.5$$\n$$P = \\frac{3.0 - 1}{2.5} = \\frac{2.0}{2.5} = 0.80$$",
        "tags": ["Nicol prism", "degree of polarization", "partially polarized light", "Malus's law"]
    },
    {
        "id": "5.164",
        "title": "Degree of Polarization Produced by Imperfect Polarizers",
        "difficulty": 2,
        "question": "Two identical imperfect polarizers are placed in the path of a natural beam of light. When the polarizers' planes are parallel, the system transmits $\\eta = 10.0$ times more light than when their planes are crossed. Find the degree of polarization of light produced:\n(a) by each polarizer separately ($P_0$);\n(b) by the whole system when the planes of the polarizers are parallel ($P$).",
        "hints": [
            "Let each polarizer have principal transmittances $\\alpha_1$ (parallel) and $\\alpha_2$ (perpendicular).",
            "When parallel, transmitted intensity from natural light is $I_\\parallel = \\frac{1}{2} I_0 (\\alpha_1^2 + \\alpha_2^2)$. When crossed, $I_\\perp = \\frac{1}{2} I_0 (2 \\alpha_1 \\alpha_2)$.",
            "Show that $P_0 = \\frac{\\alpha_1 - \\alpha_2}{\\alpha_1 + \\alpha_2} = \\sqrt{\\frac{\\eta - 1}{\\eta + 1}}$, and $P = \\frac{\\alpha_1^2 - \\alpha_2^2}{\\alpha_1^2 + \\alpha_2^2} = \\sqrt{1 - 1/\\eta^2}$."
        ],
        "answer": "(a) $P_0 = \\sqrt{\\frac{\\eta - 1}{\\eta + 1}} = 0.905$;\n(b) $P = \\sqrt{1 - 1/\\eta^2} = 0.995$",
        "solution": "**1. Modeling Imperfect Polarizers:**\nLet an imperfect polarizer transmit a fraction $\\alpha_1$ of light polarized along its transmission axis, and a fraction $\\alpha_2$ of light polarized perpendicular to it (with $\\alpha_1 > \\alpha_2$).\nNatural light consists of two equal orthogonal components of intensity $I_0/2$.\n\n**2. Intensities for Parallel and Crossed Configurations:**\n- **Parallel polarizers:**\n  $$I_\\parallel = \\frac{I_0}{2} (\\alpha_1^2 + \\alpha_2^2)$$\n- **Crossed polarizers:**\n  The component along the first axis encounters transmission $\\alpha_1$, then $\\alpha_2$; the perpendicular component encounters $\\alpha_2$, then $\\alpha_1$:\n  $$I_\\perp = \\frac{I_0}{2} (\\alpha_1 \\alpha_2 + \\alpha_2 \\alpha_1) = I_0 \\alpha_1 \\alpha_2$$\nGiven $I_\\parallel / I_\\perp = \\eta$:\n$$\\frac{\\alpha_1^2 + \\alpha_2^2}{2 \\alpha_1 \\alpha_2} = \\eta$$\n\n**3. Part (a): Polarization of a Single Polarizer:**\nA single polarizer produces degree of polarization:\n$$P_0 = \\frac{\\alpha_1 - \\alpha_2}{\\alpha_1 + \\alpha_2}$$\nSquaring $P_0$:\n$$P_0^2 = \\frac{(\\alpha_1 - \\alpha_2)^2}{(\\alpha_1 + \\alpha_2)^2} = \\frac{\\alpha_1^2 + \\alpha_2^2 - 2\\alpha_1\\alpha_2}{\\alpha_1^2 + \\alpha_2^2 + 2\\alpha_1\\alpha_2}$$\nDividing numerator and denominator by $2\\alpha_1\\alpha_2$:\n$$P_0^2 = \\frac{\\eta - 1}{\\eta + 1} \\implies P_0 = \\sqrt{\\frac{\\eta - 1}{\\eta + 1}}$$\nFor $\\eta = 10.0$:\n$$P_0 = \\sqrt{\\frac{10 - 1}{10 + 1}} = \\sqrt{\\frac{9}{11}} = \\sqrt{0.8182} \\approx 0.9045 \\approx 0.905$$\n\n**4. Part (b): Polarization of Two Parallel Polarizers:**\nThe light emerging from the two parallel polarizers has principal components proportional to $\\alpha_1^2$ and $\\alpha_2^2$:\n$$P = \\frac{\\alpha_1^2 - \\alpha_2^2}{\\alpha_1^2 + \\alpha_2^2}$$\nSquaring:\n$$P^2 = \\frac{(\\alpha_1^2 - \\alpha_2^2)^2}{(\\alpha_1^2 + \\alpha_2^2)^2} = \\frac{(\\alpha_1^2 + \\alpha_2^2)^2 - 4\\alpha_1^2\\alpha_2^2}{(\\alpha_1^2 + \\alpha_2^2)^2} = 1 - \\left(\\frac{2\\alpha_1\\alpha_2}{\\alpha_1^2 + \\alpha_2^2}\\right)^2 = 1 - \\frac{1}{\\eta^2}$$\n$$P = \\sqrt{1 - \\frac{1}{\\eta^2}}$$\nFor $\\eta = 10.0$:\n$$P = \\sqrt{1 - \\frac{1}{100}} = \\sqrt{0.99} \\approx 0.995$$",
        "tags": ["polarizers", "degree of polarization", "crossed polarizers", "parallel polarizers"]
    },
    {
        "id": "5.165",
        "title": "Sensitivity of Photometric Equalization of Polarized Beams",
        "difficulty": 3,
        "question": "Two parallel plane-polarized beams of light of equal intensity whose oscillation planes $N_1$ and $N_2$ form a small angle $\\varphi$ fall on a Nicol prism. To equalize the intensities of the beams emerging behind the prism, its principal direction $N$ must be aligned along the bisecting line $A$ or the perpendicular line $B$. Find the value of angle $\\varphi$ at which rotation of the Nicol prism through a small angle $\\delta\\varphi \\ll \\varphi$ from position $A$ results in a fractional change of intensities $\\Delta I / I$ that is $\\eta = 100$ times greater than that resulting from rotation by the same angle from position $B$.",
        "hints": [
            "In position $A$, the angle to each beam is $\\varphi/2$. When rotated by $\\delta\\varphi$, the beam intensities are $I_1 = I_0 \\cos^2(\\varphi/2 - \\delta\\varphi)$ and $I_2 = I_0 \\cos^2(\\varphi/2 + \\delta\\varphi)$.",
            "Calculate the relative intensity difference $(\\Delta I / I)_A = \\frac{I_1 - I_2}{I} \\approx 4 \\cot(\\varphi/2) \\delta\\varphi$.",
            "For position $B$, the angle to each beam is $\\pi/2 - \\varphi/2$. Show that $(\\Delta I / I)_B \\approx 4 \\tan(\\varphi/2) \\delta\\varphi$. Then $\\eta = \\cot^2(\\varphi/2)$."
        ],
        "answer": "$\\varphi = 2 \\operatorname{arccot}(\\sqrt{\\eta}) = 11.5^\\circ$",
        "solution": "**1. Rotation from Bisector Position $A$:**\nIn position $A$, the Nicol's transmission plane is along the bisector of the two planes $N_1$ and $N_2$, making angles $\\pm \\varphi/2$ with them.\nWhen rotated by a small angle $\\delta\\varphi$:\n$$I_1 = I_0 \\cos^2\\left(\\frac{\\varphi}{2} - \\delta\\varphi\\right), \\quad I_2 = I_0 \\cos^2\\left(\\frac{\\varphi}{2} + \\delta\\varphi\\right)$$\nExpanding for small $\\delta\\varphi$:\n$$I_1 \\approx I_0 \\left(\\cos\\frac{\\varphi}{2} + \\delta\\varphi \\sin\\frac{\\varphi}{2}\\right)^2 \\approx I_0 \\left(\\cos^2\\frac{\\varphi}{2} + 2 \\delta\\varphi \\sin\\frac{\\varphi}{2} \\cos\\frac{\\varphi}{2}\\right)$$\n$$I_2 \\approx I_0 \\left(\\cos^2\\frac{\\varphi}{2} - 2 \\delta\\varphi \\sin\\frac{\\varphi}{2} \\cos\\frac{\\varphi}{2}\\right)$$\n$$\\Delta I_A = I_1 - I_2 = 4 I_0 \\delta\\varphi \\sin\\frac{\\varphi}{2} \\cos\\frac{\\varphi}{2}$$\n$$I_A \\approx I_0 \\cos^2\\frac{\\varphi}{2}$$\n$$\\left(\\frac{\\Delta I}{I}\\right)_A = \\frac{4 I_0 \\delta\\varphi \\sin(\\varphi/2) \\cos(\\varphi/2)}{I_0 \\cos^2(\\varphi/2)} = 4 \\cot\\left(\\frac{\\varphi}{2}\\right) \\delta\\varphi$$\n\n**2. Rotation from Perpendicular Bisector Position $B$:**\nIn position $B$, the axis is perpendicular to bisector $A$, making angles $\\frac{\\pi}{2} \\pm \\frac{\\varphi}{2}$ with the beams:\n$$I_B \\approx I_0 \\sin^2\\frac{\\varphi}{2}$$\nWhen rotated by $\\delta\\varphi$, using $\\sin(\\varphi/2 \\pm \\delta\\varphi)$:\n$$\\left(\\frac{\\Delta I}{I}\\right)_B = 4 \\tan\\left(\\frac{\\varphi}{2}\\right) \\delta\\varphi$$\n\n**3. Ratio of Sensitivities:**\n$$\\eta = \\frac{(\\Delta I / I)_A}{(\\Delta I / I)_B} = \\frac{\\cot(\\varphi/2)}{\\tan(\\varphi/2)} = \\cot^2\\left(\\frac{\\varphi}{2}\\right)$$\n$$\\cot\\left(\\frac{\\varphi}{2}\\right) = \\sqrt{\\eta} \\implies \\tan\\left(\\frac{\\varphi}{2}\\right) = \\frac{1}{\\sqrt{\\eta}}$$\n$$\\frac{\\varphi}{2} = \\arctan\\left(\\frac{1}{\\sqrt{\\eta}}\\right)$$\n\n**4. Numerical Evaluation:**\nFor $\\eta = 100$:\n$$\\tan\\left(\\frac{\\varphi}{2}\\right) = \\frac{1}{\\sqrt{100}} = 0.10$$\n$$\\frac{\\varphi}{2} = \\arctan(0.10) \\approx 5.71^\\circ$$\n$$\\varphi = 2 (5.71^\\circ) = 11.42^\\circ \\approx 11.5^\\circ$$",
        "tags": ["photometry", "Nicol prism", "equalization of beams", "sensitivity", "polarization"]
    },
    {
        "id": "5.166",
        "title": "Brewster's Law and Angle Between Reflected and Refracted Rays",
        "difficulty": 1,
        "question": "Using Fresnel's equations, demonstrate that light reflected from the surface of a dielectric will be completely linearly polarized if the angle of incidence $\\theta_1$ satisfies Brewster's condition $\\tan\\theta_1 = n$, where $n$ is the refractive index of the dielectric. What is the angle between the reflected and refracted rays in this case?",
        "hints": [
            "Recall Fresnel's reflection formula for the parallel component: $r_\\parallel = \\frac{\\tan(\\theta_1 - \\theta_2)}{\\tan(\\theta_1 + \\theta_2)}$.",
            "This reflection amplitude vanishes when the denominator tends to infinity, i.e., when $\\theta_1 + \\theta_2 = 90^\\circ$.",
            "Apply Snell's law $\\sin\\theta_1 = n \\sin\\theta_2$ with $\\theta_2 = 90^\\circ - \\theta_1$ to prove $\\tan\\theta_1 = n$, and find the angle between reflected and refracted rays."
        ],
        "answer": "$\\tan\\theta_1 = n$; the angle between the reflected and refracted rays is $90^\\circ$",
        "solution": "**1. Fresnel Equation for Parallel Component:**\nAccording to Fresnel's equations, the reflection amplitude for the component whose electric field oscillates in the plane of incidence (parallel component) is:\n$$r_\\parallel = \\frac{\\tan(\\theta_1 - \\theta_2)}{\\tan(\\theta_1 + \\theta_2)}$$\nwhere $\\theta_1$ is the angle of incidence and $\\theta_2$ is the angle of refraction.\n\n**2. Condition for Zero Reflection of Parallel Component:**\nThe reflected parallel intensity $R_\\parallel = |r_\\parallel|^2 = 0$ when $\\tan(\\theta_1 + \\theta_2) \\to \\infty$, which occurs when:\n$$\\theta_1 + \\theta_2 = \\frac{\\pi}{2} = 90^\\circ$$\nWhen this condition is met, the reflected light contains only the perpendicular component, making it $100\\%$ linearly polarized.\n\n**3. Brewster's Law:**\nFrom Snell's law: $\\sin\\theta_1 = n \\sin\\theta_2$.\nSubstituting $\\theta_2 = 90^\\circ - \\theta_1$:\n$$\\sin\\theta_1 = n \\sin(90^\\circ - \\theta_1) = n \\cos\\theta_1$$\n$$\\frac{\\sin\\theta_1}{\\cos\\theta_1} = \\tan\\theta_1 = n$$\n\n**4. Angle Between Reflected and Refracted Rays:**\nBy the law of reflection, the reflected ray makes angle $\\theta_1$ with the surface normal.\nThe refracted ray makes angle $\\theta_2$ with the normal inside the dielectric.\nThe angle between the reflected and refracted rays is:\n$$\\gamma = 180^\\circ - (\\theta_1 + \\theta_2) = 180^\\circ - 90^\\circ = 90^\\circ$$\nThis physical perpendicularity means that the oscillating electric dipoles induced in the dielectric point exactly along the direction of the reflected ray; since oscillating dipoles do not radiate along their oscillation axis, no parallel-polarized wave can be reflected.",
        "tags": ["Brewster's law", "Fresnel equations", "dielectric reflection", "polarization angle"]
    },
    {
        "id": "5.167",
        "title": "Reflectance and Degree of Polarization at Brewster Angle on Glass",
        "difficulty": 2,
        "question": "Natural light falls at the Brewster angle on the surface of glass ($n = 1.50$). Using the Fresnel equations, find:\n(a) the reflection coefficient $\\rho$;\n(b) the degree of polarization $P$ of the refracted light.",
        "hints": [
            "(a) At Brewster's angle, $\\rho_\\parallel = 0$. The perpendicular reflection coefficient is $\\rho_\\perp = \\sin^2(\\theta_1 - \\theta_2) / \\sin^2(\\theta_1 + \\theta_2) = \\cos^2(2\\theta_B) = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2$. For natural light, $\\rho = \\frac{1}{2} \\rho_\\perp$.",
            "(b) In the refracted beam, the parallel component is fully transmitted ($T_\\parallel = 1$), while the perpendicular component has transmission $T_\\perp = 1 - \\rho_\\perp$.",
            "The degree of polarization of refracted light is $P = \\frac{T_\\parallel - T_\\perp}{T_\\parallel + T_\\perp} = \\frac{\\rho_\\perp}{2 - \\rho_\\perp} = \\frac{\\rho}{1 - \\rho}$."
        ],
        "answer": "(a) $\\rho = \\frac{1}{2} \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2 = 0.074$;\n(b) $P = \\frac{\\rho}{1 - \\rho} = 0.080$",
        "solution": "**1. Part (a): Reflection Coefficient:**\nAt the Brewster angle $\\theta_B$:\n$$\\tan\\theta_B = n, \\quad \\theta_1 + \\theta_2 = 90^\\circ$$\nTherefore $\\rho_\\parallel = 0$.\nFor the perpendicular component:\n$$\\rho_\\perp = \\frac{\\sin^2(\\theta_1 - \\theta_2)}{\\sin^2(\\theta_1 + \\theta_2)} = \\sin^2(\\theta_1 - \\theta_2) = \\sin^2(2\\theta_B - 90^\\circ) = \\cos^2(2\\theta_B)$$\nUsing $\\cos(2\\theta_B) = \\frac{1 - \\tan^2\\theta_B}{1 + \\tan^2\\theta_B} = \\frac{1 - n^2}{1 + n^2}$:\n$$\\rho_\\perp = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2$$\nSince natural light has equal energy in both polarizations:\n$$\\rho = \\frac{1}{2} (\\rho_\\parallel + \\rho_\\perp) = \\frac{1}{2} \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2$$\nFor glass with $n = 1.50$:\n$$\\frac{n^2 - 1}{n^2 + 1} = \\frac{2.25 - 1}{2.25 + 1} = \\frac{1.25}{3.25} = \\frac{5}{13} \\approx 0.3846$$\n$$\\rho = \\frac{1}{2} (0.3846)^2 = \\frac{1}{2} (0.1479) \\approx 0.0740 = 0.074$$\n\n**2. Part (b): Degree of Polarization of Refracted Light:**\nThe intensities of the two polarization components in the refracted light are:\n$$I_{\\parallel,\\text{refr}} = \\frac{1}{2} I_0 (1 - \\rho_\\parallel) = \\frac{1}{2} I_0$$\n$$I_{\\perp,\\text{refr}} = \\frac{1}{2} I_0 (1 - \\rho_\\perp) = \\frac{1}{2} I_0 (1 - 2\\rho)$$\nThe degree of polarization is:\n$$P = \\frac{I_{\\parallel,\\text{refr}} - I_{\\perp,\\text{refr}}}{I_{\\parallel,\\text{refr}} + I_{\\perp,\\text{refr}}} = \\frac{1 - (1 - 2\\rho)}{1 + (1 - 2\\rho)} = \\frac{2\\rho}{2 - 2\\rho} = \\frac{\\rho}{1 - \\rho}$$\nSubstituting $\\rho = 0.074$:\n$$P = \\frac{0.074}{1 - 0.074} = \\frac{0.074}{0.926} \\approx 0.0799 \\approx 0.080$$",
        "tags": ["Brewster's angle", "Fresnel equations", "reflectance", "degree of polarization", "refraction"]
    },
    {
        "id": "5.168",
        "title": "Intensity of the Refracted Beam at Brewster Angle",
        "difficulty": 2,
        "question": "A plane beam of natural light with intensity $I_0$ falls on the surface of water ($n = 1.333$) at the Brewster angle. A fraction $\\rho = 0.039$ of luminous flux is reflected. Find the intensity $I$ of the refracted beam.",
        "hints": [
            "The total transmitted luminous flux is $\\Phi_{\\text{refr}} = (1 - \\rho) \\Phi_0$.",
            "Intensity is flux per unit area of the beam cross-section: $I = \\Phi / S$.",
            "The cross-sectional area of the refracted beam is related to the incident beam by $S_{\\text{refr}} = S_0 \\frac{\\cos\\theta_2}{\\cos\\theta_1} = S_0 \\tan\\theta_1 = n S_0$. Therefore $I = \\frac{1 - \\rho}{n} I_0$."
        ],
        "answer": "$I = \\frac{1 - \\rho}{n} I_0 = 0.721 I_0$",
        "solution": "**1. Flux Conservation:**\nLet the incident beam carry total power $\\Phi_0 = I_0 S_0$, where $S_0$ is the cross-sectional area of the incident beam.\nThe reflected flux is $\\Phi_{\\text{refl}} = \\rho \\Phi_0$.\nBy energy conservation, the refracted flux is:\n$$\\Phi_{\\text{refr}} = (1 - \\rho) \\Phi_0 = (1 - \\rho) I_0 S_0$$\n\n**2. Change in Beam Cross-Section Upon Refraction:**\nIf the beam illuminates an area $A$ on the water surface:\n$$S_0 = A \\cos\\theta_1, \\quad S_{\\text{refr}} = A \\cos\\theta_2$$\n$$\\frac{S_{\\text{refr}}}{S_0} = \\frac{\\cos\\theta_2}{\\cos\\theta_1}$$\nAt Brewster's angle, $\\theta_1 + \\theta_2 = 90^\\circ \\implies \\cos\\theta_2 = \\sin\\theta_1$:\n$$\\frac{S_{\\text{refr}}}{S_0} = \\frac{\\sin\\theta_1}{\\cos\\theta_1} = \\tan\\theta_1 = n$$\n\n**3. Intensity of the Refracted Beam:**\n$$I = \\frac{\\Phi_{\\text{refr}}}{S_{\\text{refr}}} = \\frac{(1 - \\rho) I_0 S_0}{n S_0} = \\frac{1 - \\rho}{n} I_0$$\n\n**4. Numerical Evaluation:**\nFor water with $n = 1.333$ and $\\rho = 0.039$:\n$$I = \\frac{1 - 0.039}{1.333} I_0 = \\frac{0.961}{1.333} I_0 \\approx 0.7209 I_0 \\approx 0.721 I_0$$",
        "tags": ["Brewster's angle", "refracted beam", "intensity", "beam cross-section"]
    },
    {
        "id": "5.169",
        "title": "Reflectance of Linearly Polarized Light at Brewster Angle on Water",
        "difficulty": 2,
        "question": "A beam of plane-polarized light falls on the surface of water ($n = 4/3$) at the Brewster angle. The polarization plane of the electric vector makes an angle $\\varphi = 45^\\circ$ with the plane of incidence. Find the reflection coefficient $\\rho$.",
        "hints": [
            "Decompose the incident electric field into parallel and perpendicular components: $E_\\parallel = E_0 \\cos\\varphi$ and $E_\\perp = E_0 \\sin\\varphi$.",
            "The incident intensities are $I_\\parallel = I_0 \\cos^2\\varphi$ and $I_\\perp = I_0 \\sin^2\\varphi$.",
            "At Brewster's angle, $\\rho_\\parallel = 0$. The perpendicular reflection coefficient is $\\rho_\\perp = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2$. Thus $\\rho = \\rho_\\perp \\sin^2\\varphi$."
        ],
        "answer": "$\\rho = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2 \\sin^2\\varphi = 0.038$",
        "solution": "**1. Component Intensities:**\nThe electric vector $E_0$ makes an angle $\\varphi = 45^\\circ$ with the incidence plane:\n$$I_\\parallel = I_0 \\cos^2\\varphi, \\quad I_\\perp = I_0 \\sin^2\\varphi$$\n\n**2. Reflection at Brewster Angle:**\nAt the Brewster angle, the parallel reflection coefficient is zero:\n$$\\rho_\\parallel = 0$$\nFor the perpendicular component:\n$$\\rho_\\perp = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2$$\nTherefore, the total reflected intensity is:\n$$I_{\\text{refl}} = \\rho_\\parallel I_\\parallel + \\rho_\\perp I_\\perp = \\rho_\\perp I_0 \\sin^2\\varphi$$\n\n**3. Reflection Coefficient:**\n$$\\rho = \\frac{I_{\\text{refl}}}{I_0} = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2 \\sin^2\\varphi$$\n\n**4. Numerical Evaluation:**\nFor water with $n = 4/3$ and $\\varphi = 45^\\circ$:\n$$n^2 = \\frac{16}{9}$$\n$$\\frac{n^2 - 1}{n^2 + 1} = \\frac{16/9 - 1}{16/9 + 1} = \\frac{7/9}{25/9} = \\frac{7}{25} = 0.28$$\n$$\\rho_\\perp = (0.28)^2 = 0.0784$$\n$$\\rho = (0.0784) \\sin^2 45^\\circ = (0.0784)(0.50) = 0.0392 \\approx 0.038$$",
        "tags": ["plane-polarized light", "Brewster's angle", "reflectance", "Fresnel equations"]
    },
    {
        "id": "5.170",
        "title": "Degree of Polarization of Beams Reflected and Refracted by a Plate",
        "difficulty": 2,
        "question": "A narrow beam of natural light falls on the surface of a thick transparent plane-parallel plate at the Brewster angle. A fraction $\\rho = 0.080$ of luminous flux is reflected from its top surface (beam 1). Find the degree of polarization of beams 1, 2, 3, and 4 (beam 1: first reflected; beam 2: first refracted; beam 3: reflected from bottom surface; beam 4: transmitted through both surfaces).",
        "hints": [
            "At Brewster's angle, all reflected beams (beams 1 and 3) consist exclusively of the perpendicular component, so $P_1 = P_3 = 1$.",
            "For natural light, beam 1 reflects fraction $2\\rho$ of the perpendicular component, so beam 2 has degree of polarization $P_2 = \\frac{\\rho}{1 - \\rho}$.",
            "Beam 4 undergoes two transmissions at Brewster angle with no loss of parallel component and loss of $(1 - 2\\rho)$ in perpendicular component at each surface: $P_4 = \\frac{1 - (1 - 2\\rho)^2}{1 + (1 - 2\\rho)^2} = \\frac{2\\rho(1 - \\rho)}{1 - 2\\rho + 2\\rho^2}$."
        ],
        "answer": "$P_1 = P_3 = 1$; $P_2 = \\frac{\\rho}{1 - \\rho} = 0.087$; $P_4 = 0.17$",
        "solution": "**1. Reflected Beams (Beams 1 and 3):**\nAt Brewster's angle of incidence $\\theta_B$ on the top surface, $\\tan\\theta_B = n$.\nInside the plate, the ray strikes the bottom surface at angle $\\theta_2 = 90^\\circ - \\theta_B$, which is precisely the Brewster angle for internal reflection ($\\tan\\theta_2 = 1/n$).\nTherefore, at both surfaces, the reflection coefficient for the parallel component is identically zero ($R_\\parallel = 0$).\nConsequently, both reflected beams (beam 1 from the top surface and beam 3 from the bottom surface) contain purely the perpendicular component:\n$$P_1 = 1, \\quad P_3 = 1$$\n\n**2. First Refracted Beam (Beam 2):**\nFor incident natural light of intensity $I_0$:\n$$I_\\parallel = I_\\perp = \\frac{I_0}{2}$$\nThe fraction of natural flux reflected is $\\rho = 0.080 = \\frac{1}{2} \\rho_\\perp \\implies \\rho_\\perp = 2\\rho = 0.160$.\nThe transmitted components in beam 2 are:\n$$I_{2,\\parallel} = \\frac{I_0}{2}, \\quad I_{2,\\perp} = \\frac{I_0}{2}(1 - \\rho_\\perp) = \\frac{I_0}{2}(1 - 2\\rho)$$\nThe degree of polarization of beam 2 is:\n$$P_2 = \\frac{I_{2,\\parallel} - I_{2,\\perp}}{I_{2,\\parallel} + I_{2,\\perp}} = \\frac{1 - (1 - 2\\rho)}{1 + (1 - 2\\rho)} = \\frac{2\\rho}{2 - 2\\rho} = \\frac{\\rho}{1 - \\rho}$$\n$$P_2 = \\frac{0.080}{1 - 0.080} = \\frac{0.080}{0.920} \\approx 0.087$$\n\n**3. Doubly Transmitted Beam (Beam 4):**\nBeam 4 exits through the bottom face. The parallel component suffers no reflection losses at either face:\n$$I_{4,\\parallel} = \\frac{I_0}{2}$$\nThe perpendicular component undergoes two transmissions with transmission factor $(1 - \\rho_\\perp) = (1 - 2\\rho)$:\n$$I_{4,\\perp} = \\frac{I_0}{2} (1 - 2\\rho)^2$$\nThe degree of polarization of beam 4 is:\n$$P_4 = \\frac{1 - (1 - 2\\rho)^2}{1 + (1 - 2\\rho)^2} = \\frac{1 - (1 - 4\\rho + 4\\rho^2)}{1 + (1 - 4\\rho + 4\\rho^2)} = \\frac{4\\rho - 4\\rho^2}{2 - 4\\rho + 4\\rho^2} = \\frac{2\\rho(1 - \\rho)}{1 - 2\\rho + 2\\rho^2}$$\nWith $\\rho = 0.080$:\n$$1 - 2\\rho = 1 - 0.160 = 0.840$$\n$$(1 - 2\\rho)^2 = (0.840)^2 = 0.7056$$\n$$P_4 = \\frac{1 - 0.7056}{1 + 0.7056} = \\frac{0.2944}{1.7056} \\approx 0.1726 \\approx 0.17$$",
        "tags": ["plane-parallel plate", "Brewster's angle", "degree of polarization", "multiple beams"]
    },
    {
        "id": "5.171",
        "title": "Transmission and Polarization of Light Passing Through a Brewster Plate",
        "difficulty": 2,
        "question": "A narrow beam of light of intensity $I_0$ falls on a plane-parallel glass plate ($n = 1.50$) at the Brewster angle. Using the Fresnel equations, find:\n(a) the intensity of the transmitted beam $I_{\\text{trans}}$ if the incident light is plane-polarized with oscillation plane perpendicular to the incidence plane;\n(b) the degree of polarization $P$ of the transmitted light if the incident light is natural.",
        "hints": [
            "(a) At Brewster's angle, $\\rho_\\perp = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2$. Transmission through two interfaces gives $I_{\\text{trans}} = (1 - \\rho_\\perp)^2 I_0 = \\left[\\frac{4n^2}{(n^2+1)^2}\\right]^2 I_0 = \\frac{16 n^4}{(n^2+1)^4} I_0$.",
            "(b) For natural light, the parallel component is transmitted fully ($T_\\parallel = 1$), while the perpendicular component has transmission $T_\\perp = (1 - \\rho_\\perp)^2$.",
            "The degree of polarization of the transmitted beam is $P = \\frac{1 - (1 - \\rho_\\perp)^2}{1 + (1 - \\rho_\\perp)^2} = \\frac{1 - T_\\perp}{1 + T_\\perp} \\approx 0.16$."
        ],
        "answer": "(a) $I_{\\text{trans}} = \\frac{16 n^4}{(n^2+1)^4} I_0 \\approx 0.725 I_0$;\n(b) $P \\approx 0.16$",
        "solution": "**1. Perpendicular Reflection Coefficient:**\nAt Brewster's angle on glass of refractive index $n$:\n$$\\rho_\\perp = \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2$$\nFor $n = 1.50$:\n$$\\rho_\\perp = \\left(\\frac{2.25 - 1}{2.25 + 1}\\right)^2 = \\left(\\frac{1.25}{3.25}\\right)^2 = \\left(\\frac{5}{13}\\right)^2 = \\frac{25}{169} \\approx 0.1479$$\n\n**2. Part (a): Transmission of Linearly Polarized Light ($\\,\\mathbf{E} \\perp$ Incidence Plane):**\nThe transmission through each of the two surfaces is $T_\\perp = 1 - \\rho_\\perp = 1 - \\frac{25}{169} = \\frac{144}{169}$.\nThe transmitted intensity is:\n$$I_{\\text{trans}} = T_\\perp^2 I_0 = (1 - \\rho_\\perp)^2 I_0 = \\left(\\frac{144}{169}\\right)^2 I_0 \\approx (0.8521)^2 I_0 \\approx 0.726 I_0 \\approx 0.725 I_0$$\nAlternatively, in terms of $n$:\n$$1 - \\rho_\\perp = 1 - \\left(\\frac{n^2 - 1}{n^2 + 1}\\right)^2 = \\frac{(n^2 + 1)^2 - (n^2 - 1)^2}{(n^2 + 1)^2} = \\frac{4 n^2}{(n^2 + 1)^2}$$\n$$I_{\\text{trans}} = \\left[\\frac{4 n^2}{(n^2 + 1)^2}\\right]^2 I_0 = \\frac{16 n^4}{(n^2 + 1)^4} I_0$$\n\n**3. Part (b): Degree of Polarization for Natural Incident Light:**\nNatural light splits into equal components of intensity $I_0/2$.\n- Parallel component: suffers no reflection at either surface, so $I_{\\text{trans},\\parallel} = \\frac{1}{2} I_0$.\n- Perpendicular component: $I_{\\text{trans},\\perp} = \\frac{1}{2} I_0 (1 - \\rho_\\perp)^2$.\nThe degree of polarization is:\n$$P = \\frac{I_{\\text{trans},\\parallel} - I_{\\text{trans},\\perp}}{I_{\\text{trans},\\parallel} + I_{\\text{trans},\\perp}} = \\frac{1 - (1 - \\rho_\\perp)^2}{1 + (1 - \\rho_\\perp)^2} = \\frac{1 - 0.726}{1 + 0.726} = \\frac{0.274}{1.726} \\approx 0.1587 \\approx 0.16$$",
        "tags": ["plane-parallel plate", "Brewster's angle", "degree of polarization", "Fresnel equations"]
    },
    {
        "id": "5.172",
        "title": "Degree of Polarization Produced by a Pile of Brewster Plates",
        "difficulty": 2,
        "question": "A narrow beam of natural light falls on a stack of $N$ thick plane-parallel glass plates at the Brewster angle. Find:\n(a) the degree $P$ of polarization of the transmitted beam as a function of $N$ and the refractive index $n$;\n(b) the value of $P$ for $N = 1, 2, 5$, and $10$ with $n = 1.50$.",
        "hints": [
            "A stack of $N$ plates has $2N$ interfaces. At each interface, the parallel component has transmission $1$, while the perpendicular component has transmission $1 - \\rho_\\perp = \\frac{4n^2}{(n^2+1)^2} = \\alpha^2$, where $\\alpha = \\frac{2n}{n^2+1}$.",
            "After traversing $N$ plates ($2N$ surfaces), the transmitted perpendicular component is reduced by factor $\\alpha^{4N}$.",
            "The degree of polarization is $P = \\frac{1 - \\alpha^{4N}}{1 + \\alpha^{4N}}$."
        ],
        "answer": "(a) $P = \\frac{1 - \\alpha^{4N}}{1 + \\alpha^{4N}}$, where $\\alpha = \\frac{2n}{n^2+1}$;\n(b) $P = 0.16$ ($N=1$), $0.31$ ($N=2$), $0.67$ ($N=5$), $0.92$ ($N=10$)",
        "solution": "**1. Transmission Through $N$ Brewster Plates:**\nA stack (pile) of $N$ plane-parallel plates has $2N$ boundary surfaces.\nAt every surface, the incidence angle is Brewster's angle, so:\n- For the parallel component: reflection is zero at all $2N$ surfaces, so $T_\\parallel = 1$.\n- For the perpendicular component: the transmission at each surface is:\n  $$t_\\perp = 1 - \\rho_\\perp = \\frac{4 n^2}{(n^2 + 1)^2} = \\left(\\frac{2n}{n^2 + 1}\\right)^2 = \\alpha^2$$\n  where $\\alpha = \\frac{2n}{n^2 + 1}$.\nThrough $2N$ surfaces, the total transmission of the perpendicular component is:\n$$T_\\perp = (t_\\perp)^{2N} = \\alpha^{4N}$$\n\n**2. Degree of Polarization:**\n$$P = \\frac{T_\\parallel - T_\\perp}{T_\\parallel + T_\\perp} = \\frac{1 - \\alpha^{4N}}{1 + \\alpha^{4N}}$$\n\n**3. Numerical Evaluation for $n = 1.50$:**\n$$\\alpha = \\frac{2(1.50)}{1.50^2 + 1} = \\frac{3.0}{3.25} = \\frac{12}{13} \\approx 0.92308$$\n$$\\alpha^4 = \\left(\\frac{12}{13}\\right)^4 = \\frac{20736}{28561} \\approx 0.7260$$\n- **For $N = 1$:** $\\alpha^4 \\approx 0.7260 \\implies P = \\frac{1 - 0.7260}{1 + 0.7260} = \\frac{0.2740}{1.7260} \\approx 0.1587 \\approx 0.16$\n- **For $N = 2$:** $\\alpha^8 = (0.7260)^2 \\approx 0.5271 \\implies P = \\frac{1 - 0.5271}{1 + 0.5271} = \\frac{0.4729}{1.5271} \\approx 0.3097 \\approx 0.31$\n- **For $N = 5$:** $\\alpha^{20} = (0.7260)^5 \\approx 0.1983 \\implies P = \\frac{1 - 0.1983}{1 + 0.1983} = \\frac{0.8017}{1.1983} \\approx 0.6690 \\approx 0.67$\n- **For $N = 10$:** $\\alpha^{40} = (0.1983)^2 \\approx 0.0393 \\implies P = \\frac{1 - 0.0393}{1 + 0.0393} = \\frac{0.9607}{1.0393} \\approx 0.9244 \\approx 0.92$",
        "tags": ["pile of plates", "Brewster's angle", "degree of polarization", "Fresnel reflection"]
    },
    {
        "id": "5.173",
        "title": "Reflection Loss of Light Passing Through Multiple Lenses",
        "difficulty": 1,
        "question": "Using the Fresnel equations, find:\n(a) the reflection coefficient $\\rho$ of natural light falling normally on the surface of glass ($n = 1.50$);\n(b) the relative loss of luminous flux $\\Delta\\Phi / \\Phi_0$ due to reflections of a paraxial ray of natural light passing through an aligned optical system comprising five glass lenses (neglecting secondary reflections).",
        "hints": [
            "(a) For normal incidence, $\\rho = \\left(\\frac{n - 1}{n + 1}\\right)^2$.",
            "(b) Five lenses have $2 \\times 5 = 10$ glass-air interfaces.",
            "The fraction of luminous flux transmitted through $k = 10$ surfaces is $(1 - \\rho)^k$. The relative loss is $\\Delta\\Phi / \\Phi_0 = 1 - (1 - \\rho)^k$."
        ],
        "answer": "(a) $\\rho = \\left(\\frac{n - 1}{n + 1}\\right)^2 = 0.040$;\n(b) $\\frac{\\Delta\\Phi}{\\Phi_0} = 1 - (1 - \\rho)^{2N} = 0.34$",
        "solution": "**1. Part (a): Normal Incidence Reflection Coefficient:**\nFor normal incidence on a dielectric boundary, the Fresnel reflection coefficient is independent of polarization:\n$$\\rho = \\left(\\frac{n - 1}{n + 1}\\right)^2$$\nFor glass with $n = 1.50$:\n$$\\rho = \\left(\\frac{1.50 - 1}{1.50 + 1}\\right)^2 = \\left(\\frac{0.50}{2.50}\\right)^2 = \\left(\\frac{1}{5}\\right)^2 = 0.040\\text{ (or } 4.0\\%\\text{)}$$\n\n**2. Part (b): Flux Loss Through Five Lenses:**\nFive lenses have $N = 5$ elements, corresponding to $2N = 10$ glass-air surfaces.\nAt each surface, neglecting absorption and secondary reflections, the transmission factor is $1 - \\rho$.\nThe total transmitted fraction of luminous flux is:\n$$\\frac{\\Phi}{\\Phi_0} = (1 - \\rho)^{2N} = (1 - 0.040)^{10} = (0.96)^{10}$$\n$$(0.96)^{10} \\approx 0.6648$$\nThe relative loss of luminous flux is:\n$$\\frac{\\Delta\\Phi}{\\Phi_0} = 1 - \\frac{\\Phi}{\\Phi_0} = 1 - (1 - \\rho)^{2N} = 1 - 0.6648 = 0.3352 \\approx 0.34\\text{ (or } 34\\%\\text{)}$$",
        "tags": ["Fresnel equations", "normal incidence", "reflection loss", "lenses", "transmittance"]
    },
    {
        "id": "5.174",
        "title": "Condition for Equal Amplitudes in an Anti-Reflection Coating",
        "difficulty": 2,
        "question": "A light wave falls normally on the surface of glass coated with a layer of transparent substance. Neglecting secondary reflections, demonstrate that the amplitudes of light waves reflected from the two surfaces of such a layer will be equal under the condition $n' = \\sqrt{n}$, where $n'$ and $n$ are the refractive indices of the layer and the glass respectively.",
        "hints": [
            "At normal incidence from air ($n_0 = 1$) onto the coating ($n'$), the reflection amplitude is $r_1 = \\frac{n' - 1}{n' + 1}$.",
            "At the interface between coating ($n'$) and glass ($n$), the reflection amplitude is $r_2 = \\frac{n - n'}{n + n'}$.",
            "Set $r_1 = r_2$ and solve the resulting algebraic equation for $n'$."
        ],
        "answer": "$r_1 = r_2 \\implies \\frac{n' - 1}{n' + 1} = \\frac{n - n'}{n + n'} \\implies n' = \\sqrt{n}$",
        "solution": "**1. Reflection Amplitudes at Both Interfaces:**\nConsider a normal incidence beam from air ($n_0 = 1$) incident on an anti-reflection film of refractive index $n'$, backed by a glass substrate of refractive index $n$ ($1 < n' < n$).\n- **Interface 1 (air to film):**\n  The reflection amplitude is:\n  $$r_1 = \\frac{n' - 1}{n' + 1}$$\n- **Interface 2 (film to glass):**\n  The reflection amplitude inside the film at the glass interface is:\n  $$r_2 = \\frac{n - n'}{n + n'}$$\n(The transmission coefficients across interface 1 in both directions satisfy $t_1 t_1' \\approx 1$ to first order in reflections).\n\n**2. Equality of Reflected Amplitudes:**\nFor destructive interference to produce complete cancellation, the amplitudes of the two reflected waves must be equal:\n$$r_1 = r_2$$\n$$\\frac{n' - 1}{n' + 1} = \\frac{n - n'}{n + n'}$$\nCross-multiplying:\n$$(n' - 1)(n + n') = (n' + 1)(n - n')$$\n$$n n' + n'^2 - n - n' = n n' - n'^2 + n - n'$$\nSubtracting identical terms $n n' - n'$ from both sides:\n$$n'^2 - n = -n'^2 + n$$\n$$2 n'^2 = 2 n$$\n$$n'^2 = n \\implies n' = \\sqrt{n}$$\nThis completes the proof. Combined with the quarter-wave optical thickness condition $n' d = \\lambda / 4$, this achieves zero reflection (anti-reflective bloom).",
        "tags": ["anti-reflection coating", "Fresnel reflection", "destructive interference", "thin films"]
    },
    {
        "id": "5.175",
        "title": "Degree of Polarization of Light Reflected and Refracted at 45 Degrees",
        "difficulty": 2,
        "question": "A beam of natural light falls on the surface of glass ($n = 1.50$) at an angle of incidence $\\theta_1 = 45^\\circ$. Using the Fresnel equations, find the degree of polarization of:\n(a) reflected light;\n(b) refracted light.",
        "hints": [
            "Use Snell's law $\\sin\\theta_2 = \\frac{\\sin 45^\\circ}{n}$ to find the refraction angle $\\theta_2$.",
            "Calculate the reflection coefficients $\\rho_\\parallel = \\frac{\\tan^2(\\theta_1 - \\theta_2)}{\\tan^2(\\theta_1 + \\theta_2)}$ and $\\rho_\\perp = \\frac{\\sin^2(\\theta_1 - \\theta_2)}{\\sin^2(\\theta_1 + \\theta_2)}$.",
            "(a) Degree of polarization of reflected light is $P_{\\text{refl}} = \\frac{\\rho_\\perp - \\rho_\\parallel}{\\rho_\\perp + \\rho_\\parallel}$. (b) For refracted light, $P_{\\text{refr}} = \\frac{\\rho_\\perp - \\rho_\\parallel}{2 - (\\rho_\\perp + \\rho_\\parallel)}$."
        ],
        "answer": "(a) $P_{\\text{refl}} = 0.83$;\n(b) $P_{\\text{refr}} = 0.044$",
        "solution": "**1. Refraction Angle:**\nBy Snell's law with $\\theta_1 = 45^\\circ$ and $n = 1.50$:\n$$\\sin\\theta_2 = \\frac{\\sin 45^\\circ}{1.50} = \\frac{\\sqrt{2} / 2}{1.50} = \\frac{0.7071}{1.50} \\approx 0.4714$$\n$$\\theta_2 = \\arcsin(0.4714) \\approx 28.13^\\circ$$\n$$\\theta_1 - \\theta_2 = 45^\\circ - 28.13^\\circ = 16.87^\\circ$$\n$$\\theta_1 + \\theta_2 = 45^\\circ + 28.13^\\circ = 73.13^\\circ$$\n\n**2. Evaluation of Fresnel Coefficients:**\n$$\\sin(16.87^\\circ) \\approx 0.2902, \\quad \\sin(73.13^\\circ) \\approx 0.9570$$\n$$\\tan(16.87^\\circ) \\approx 0.3032, \\quad \\tan(73.13^\\circ) \\approx 3.298$$\n- Perpendicular reflection coefficient:\n  $$\\rho_\\perp = \\left[\\frac{\\sin(16.87^\\circ)}{\\sin(73.13^\\circ)}\\right]^2 = \\left(\\frac{0.2902}{0.9570}\\right)^2 = (0.3032)^2 \\approx 0.09195$$\n- Parallel reflection coefficient:\n  $$\\rho_\\parallel = \\left[\\frac{\\tan(16.87^\\circ)}{\\tan(73.13^\\circ)}\\right]^2 = \\left(\\frac{0.3032}{3.298}\\right)^2 = (0.09193)^2 \\approx 0.00845$$\n\n**3. Part (a): Degree of Polarization of Reflected Light:**\n$$P_{\\text{refl}} = \\frac{\\rho_\\perp - \\rho_\\parallel}{\\rho_\\perp + \\rho_\\parallel} = \\frac{0.09195 - 0.00845}{0.09195 + 0.00845} = \\frac{0.08350}{0.10040} \\approx 0.8317 \\approx 0.83$$\n\n**4. Part (b): Degree of Polarization of Refracted Light:**\nThe transmitted intensities are $I_\\parallel \\propto 1 - \\rho_\\parallel$ and $I_\\perp \\propto 1 - \\rho_\\perp$:\n$$P_{\\text{refr}} = \\frac{(1 - \\rho_\\parallel) - (1 - \\rho_\\perp)}{(1 - \\rho_\\parallel) + (1 - \\rho_\\perp)} = \\frac{\\rho_\\perp - \\rho_\\parallel}{2 - (\\rho_\\perp + \\rho_\\parallel)}$$\n$$P_{\\text{refr}} = \\frac{0.08350}{2 - 0.10040} = \\frac{0.08350}{1.8996} \\approx 0.04395 \\approx 0.044$$",
        "tags": ["Fresnel equations", "degree of polarization", "oblique incidence", "reflection", "refraction"]
    },
    {
        "id": "5.176",
        "title": "Huygens Construction for Ordinary and Extraordinary Wavefronts",
        "difficulty": 3,
        "question": "Using Huygens's principle, construct the wavefronts and the propagation directions of the ordinary and extraordinary rays in a positive uniaxial crystal ($n_e > n_o$) whose optical axis:\n(a) is perpendicular to the incidence plane and parallel to the surface of the crystal;\n(b) lies in the incidence plane and is parallel to the surface of the crystal;\n(c) lies in the incidence plane at an angle of $45^\\circ$ to the crystal surface, with light falling at right angles to the optical axis.",
        "hints": [
            "In a positive uniaxial crystal ($v_o = c/n_o > v_e = c/n_e$), the ordinary wave surface is a sphere of radius $v_o t$, and the extraordinary wave surface is an oblate ellipsoid of revolution of semi-axes $v_o t$ (along optic axis) and $v_e t$ (perpendicular to optic axis).",
            "(a) When the optic axis is perpendicular to the incidence plane, the section of both surfaces by the incidence plane consists of concentric circles of radii $v_o t$ and $v_e t$. Both rays obey Snell's law with effective constant refractive indices $n_o$ and $n_e$.",
            "(b) & (c) When the optic axis is in the incidence plane, the extraordinary section is an ellipse. The ray direction connects the point of incidence to the point of tangency of the envelope wavefront, which generally deviates from the wave normal."
        ],
        "answer": "Huygens wavefront envelopes: (a) ordinary and extraordinary ray sections are concentric circles, both rays stay in the incidence plane; (b) ordinary wave is circular, extraordinary is elliptical with minor axis along crystal surface; (c) extraordinary ray direction deviates from the wave normal.",
        "solution": "**1. Wave Surfaces in a Positive Uniaxial Crystal:**\nFor a positive uniaxial crystal, $n_e > n_o$, which implies that the phase velocities satisfy $v_e < v_o$.\n- The ordinary wave is spherical with radius $r_o = v_o t = c t / n_o$.\n- The extraordinary wave is an ellipsoid of revolution flattened along the optical axis, with semi-axis $v_o t$ along the optic axis and $v_e t$ perpendicular to it.\n\n**2. Analysis of the Three Configurations:**\n- **Case (a): Optic axis $\\perp$ incidence plane (parallel to crystal surface):**\n  The cross-section of the wave surfaces by the incidence plane contains no component of the optical axis. Therefore, the cross-sections of both the ordinary and extraordinary wavelets are concentric circles of radii $v_o t$ and $v_e t$.\n  The common tangents from the trace of the incident wavefront on the surface form plane refracted wavefronts for both rays.\n  Both rays obey ordinary refraction laws with indices $n_o$ and $n_e$, and the ray vectors coincide with their wave normals.\n\n- **Case (b): Optic axis lies in incidence plane, parallel to crystal surface:**\n  The section of the ordinary wave surface is a circle of radius $v_o t$.\n  The section of the extraordinary wave surface is an ellipse with major semi-axis $v_o t$ along the surface (along the optic axis) and minor semi-axis $v_e t$ perpendicular to the surface.\n  The envelope wavefronts are tangent to the circle and the ellipse. Both rays remain in the incidence plane, but the extraordinary ray direction (radius vector to the tangency point) deviates from the wave normal for oblique incidence.\n\n- **Case (c): Optic axis in incidence plane at $45^\\circ$ to the surface, normal incidence to optic axis:**\n  The section of the extraordinary wave surface is an ellipse tilted at $45^\\circ$.\n  The tangent to the ellipse touches it at a point whose radius vector is not perpendicular to the tangent wavefront. Thus, even when the wave normal propagates forward, the extraordinary energy flow (ray vector) is deflected at an angle, displaying double refraction.",
        "tags": ["Huygens principle", "uniaxial crystal", "ordinary ray", "extraordinary ray", "wavefront construction"]
    },
    {
        "id": "5.177",
        "title": "Angular Separation in a Wollaston Polarizing Prism",
        "difficulty": 2,
        "question": "A narrow beam of natural light with wavelength $\\lambda = 589\\text{ nm}$ falls normally on the entrance face of a Wollaston polarizing prism made of Iceland spar ($n_o = 1.658$, $n_e = 1.486$). The prism consists of two right-angled wedges with refracting angle $\\theta = 30^\\circ$ cemented together, whose optical axes are mutually perpendicular. Find the divergence angle $\\delta$ between the two beams behind the prism.",
        "hints": [
            "In the first wedge, the light travels normally to the entrance face. The beam splits into ordinary ($n_o$) and extraordinary ($n_e$) components traveling in the same direction.",
            "At the diagonal interface, the optical axis rotates by $90^\\circ$, so the ordinary ray becomes extraordinary (refractive index changes from $n_o$ to $n_e$), and the extraordinary ray becomes ordinary ($n_e \\to n_o$).",
            "Apply Snell's law at the interface and at the exit face. For small angles or moderate angles, the total divergence in air is approximately $\\delta \\approx 2 |n_o - n_e| \\tan\\theta$."
        ],
        "answer": "$\\delta \\approx 2 |n_o - n_e| \\tan\\theta \\approx 11^\\circ$",
        "solution": "**1. Refraction at the Internal Diagonal Interface:**\nIn the first wedge, light strikes normally, so both rays enter without deviation:\n- Ray 1 has its electric field perpendicular to the optic axis $\\implies$ experiences refractive index $n_1 = n_o$.\n- Ray 2 has its electric field parallel to the optic axis $\\implies$ experiences refractive index $n_2 = n_e$.\nAt the cemented diagonal interface (angle of incidence $\\theta = 30^\\circ$), the optical axes of the two wedges are mutually perpendicular:\n- In the second wedge, ray 1 now oscillates parallel to the optical axis, so its index becomes $n'_1 = n_e$.\n- Ray 2 now oscillates perpendicular to the optical axis, so its index becomes $n'_2 = n_o$.\n\n**2. Refraction Angles Inside the Second Wedge:**\nBy Snell's law across the interface:\n$$n_o \\sin\\theta = n_e \\sin r_1 \\implies \\sin r_1 = \\frac{n_o}{n_e} \\sin\\theta$$\n$$n_e \\sin\\theta = n_o \\sin r_2 \\implies \\sin r_2 = \\frac{n_e}{n_o} \\sin\\theta$$\nFor $n_o = 1.658$, $n_e = 1.486$, and $\\theta = 30^\\circ$ ($\\sin 30^\\circ = 0.5$):\n$$\\sin r_1 = \\frac{1.658}{1.486} (0.5) = 1.1157 \\times 0.5 = 0.5579 \\implies r_1 \\approx 33.91^\\circ$$\n$$\\sin r_2 = \\frac{1.486}{1.658} (0.5) = 0.8963 \\times 0.5 = 0.4481 \\implies r_2 \\approx 26.62^\\circ$$\nInside the second wedge, the deviations from the interface normal are $\\theta_1' = r_1 - \\theta = 3.91^\\circ$ and $\\theta_2' = r_2 - \\theta = -3.38^\\circ$.\n\n**3. Refraction at the Exit Face:**\nAt the flat exit face, the rays exit into air ($n = 1$).\nUsing the small/moderate angle approximation for the total deflection of each ray:\n$$\\sin\\delta_1 \\approx n_e \\sin(r_1 - \\theta) \\approx n_e \\left(\\frac{n_o - n_e}{n_e} \\tan\\theta\\right) = (n_o - n_e) \\tan\\theta$$\n$$\\sin\\delta_2 \\approx n_o \\sin(r_2 - \\theta) \\approx -(n_o - n_e) \\tan\\theta$$\nThe total angular divergence $\\delta = \\delta_1 - \\delta_2$ between the two symmetrically deflected rays is:\n$$\\delta \\approx 2 (n_o - n_e) \\tan\\theta$$\n\n**4. Numerical Evaluation:**\nGiven $n_o - n_e = 1.658 - 1.486 = 0.172$ and $\\theta = 30^\\circ$ ($\\tan 30^\\circ = \\frac{1}{\\sqrt{3}} \\approx 0.5774$):\n$$\\delta \\approx 2 (0.172)(0.5774) \\approx 0.1986\\text{ rad}$$\nConverting to degrees:\n$$\\delta \\approx 0.1986 \\times \\frac{180^\\circ}{\\pi} \\approx 11.38^\\circ \\approx 11^\\circ$$",
        "tags": ["Wollaston prism", "Iceland spar", "calcite", "birefringence", "angular divergence"]
    },
    {
        "id": "5.178",
        "title": "Identification of Polarization States from Electric Field Projections",
        "difficulty": 2,
        "question": "What kind of polarization has a plane electromagnetic wave propagating in the $+z$ direction if the projections of the electric field $\\mathbf{E}$ on the $x$ and $y$ axes are given by:\n(a) $E_x = E_0 \\cos(\\omega t - kz)$, $E_y = E_0 \\sin(\\omega t - kz)$;\n(b) $E_x = E_0 \\cos(\\omega t - kz)$, $E_y = E_0 \\cos(\\omega t - kz + \\pi/4)$;\n(c) $E_x = E_0 \\cos(\\omega t - kz)$, $E_y = E_0 \\cos(\\omega t - kz + \\pi)$?",
        "hints": [
            "For a wave propagating in $+z$, observe the tip of the $\\mathbf{E}$ vector at fixed $z = 0$ as time $t$ increases, looking toward the incoming wave (opposite to the $+z$ direction).",
            "(a) Since $E_y = E_0 \\sin(\\omega t) = E_0 \\cos(\\omega t - \\pi/2)$, $E_y$ lags $E_x$ by $\\pi/2$. At $t = 0$, $\\mathbf{E} = (E_0, 0)$; at $\\omega t = \\pi/2$, $\\mathbf{E} = (0, E_0)$. This corresponds to counter-clockwise circular rotation.",
            "(b) Equal amplitudes with phase difference $\\pi/4$ form an ellipse tilted at $45^\\circ$ ($y = x$).",
            "(c) Phase difference of $\\pi$ means $E_y = -E_x$, which describes linear polarization along the line $y = -x$."
        ],
        "answer": "(a) Left circular (counter-clockwise) polarization;\n(b) Clockwise elliptical polarization with major axis along $y = x$;\n(c) Linear (plane) polarization along $y = -x$",
        "solution": "**1. Conventions:**\nConsider the electric field at the plane $z = 0$ as a function of time $t$, observed looking toward the incoming light beam (looking from $+z$ toward $-z$, into the screen):\n\n**2. Case (a):**\n$$E_x(t) = E_0 \\cos(\\omega t), \\quad E_y(t) = E_0 \\sin(\\omega t)$$\n- At $\\omega t = 0$: $E_x = E_0$, $E_y = 0$ (point on $+x$ axis).\n- At $\\omega t = \\pi/2$: $E_x = 0$, $E_y = E_0$ (point on $+y$ axis).\n- At $\\omega t = \\pi$: $E_x = -E_0$, $E_y = 0$ (point on $-x$ axis).\nThe tip of the vector traces a circle of radius $E_0$ in the **counter-clockwise (anticlockwise)** direction (left-handed circular polarization in standard optics convention when looking toward the source).\n\n**3. Case (b):**\n$$E_x(t) = E_0 \\cos(\\omega t), \\quad E_y(t) = E_0 \\cos\\left(\\omega t + \\frac{\\pi}{4}\\right)$$\nHere $E_y$ leads $E_x$ by $\\pi/4$.\n- At $\\omega t = 0$: $E_x = E_0$, $E_y = E_0 \\cos(\\pi/4) = E_0 / \\sqrt{2} > 0$.\n- At $\\omega t = \\pi/4$: $E_x = E_0 / \\sqrt{2}$, $E_y = 0$.\n- At $\\omega t = \\pi/2$: $E_x = 0$, $E_y = -E_0 / \\sqrt{2} < 0$.\nThe electric vector rotates from the first quadrant into the fourth quadrant, which is **clockwise**.\nBecause the amplitudes are equal ($E_{0x} = E_{0y} = E_0$) and the phase shift is in the range $0 < \\delta < \\pi/2$, the trajectory is an ellipse whose major axis lies along the line $y = x$.\n\n**4. Case (c):**\n$$E_x(t) = E_0 \\cos(\\omega t), \\quad E_y(t) = E_0 \\cos(\\omega t + \\pi) = -E_0 \\cos(\\omega t)$$\nDividing the two equations:\n$$E_y = -E_x$$\nThis represents a line segment through the origin extending between $(-E_0, E_0)$ and $(E_0, -E_0)$.\nThus, the wave is **linearly (plane) polarized** along the line $y = -x$ (inclined at $-45^\\circ$ or $135^\\circ$ to the $x$-axis).",
        "tags": ["polarization states", "circular polarization", "elliptical polarization", "linear polarization", "phase difference"]
    }
]
